### ISSUE TITLE
Question about GPT topk sampling

### ISSUE THREAD

**Issue by smallv0221** [NVIDIA/FasterTransformer#109]
It seem GPT topk sampling decoding strategy only support k = 1, 2, 4. I dont understand the design here. And is there anyway to use other value for GPT topk sampling decoding like k=50?

**Comment by byshiue** [comment]
I think FT supports k = 50. Have you tried it?

**Comment by smallv0221** [comment]
I tried k=3 and got an error. I tracked the error here.
![image](https://user-images.githubusercontent.com/33639025/125461111-93c8a09e-eb8c-42f6-81da-5090b89252bd.png)

**Comment by smallv0221** [comment]
I used FT 3.1 by the way.

**Comment by byshiue** [comment]
Please refer the latest code here https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/cuda/topk_kernels.cu#L762, which support at most 64. 
The constraint is caused by the template. You can also add the k value you need directly.

**Comment by smallv0221** [comment]
Thanks! Directly adding `CASE_K(50);` solved my problem. But I'm still a little confused about the design here because I see you have another topk kernel called `topK_kernelLauncher` which accepts general K values.
![image](https://user-images.githubusercontent.com/33639025/126126563-125fdeac-2be0-47f3-8c1d-e95f6fea06fa.png)
It uses `TopK_2<T>` instead of `TopK<T, MAX_K>` so it has no constraint. So why set constraint for `topK_sampling_kernel_kernelLauncher` and not for `topK_kernelLauncher`.

**Comment by byshiue** [comment]
General case would be slower.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
