### ISSUE TITLE
Question about the result of run FasterTransformer encoder under FP32 on TensorFlow

### ISSUE THREAD

**Issue by js19950726** [NVIDIA/FasterTransformer#112]
I have run the tensorflow/encoder_sample.py on my RTX3080 GPU with the step **Build the FasterTransformer** 1,2,3.2 -dms=86 and **Execute the encoder demos** 2.1
python tensorflow/encoder_sample.py  --batch_size 64  --max_seq_len 80  --head_number 12  --size_per_head 64  --num_layer 12  --data_type fp32   --test_time 1   --allow_gemm_test False

But I just got the TF-while-time is less than the FT-OP-while-time, TF time divide FT-OP time is about 0.71. It shows like TF operate cost less time.

And the EFF-OP-while-time is less than TF-while-time, TF time divide EFF-OP time is about 1.195. It shows like FT with remove_padding operate cost less time.

I think it not operate normally because the margin of speedup is very small.

Could you plz give me some advice to improve the execution time？or if you know what is the problem, just tell me.

thanks a lot

**Comment by byshiue** [comment]
By default, TF will use TF32 to compute when the precision is FP32, while FT also run on FP32. 
You can use `export NVIDIA_TF32_OVERRIDE=0` to disable the TF32.
The reason that we don't support TF32 is because if users can use TF32, then they should use FP16 directly.

**Comment by js19950726** [comment]
It works, thx a lot
