### ISSUE TITLE
GPT generated negative token id

### ISSUE THREAD

**Issue by makai281** [NVIDIA/FasterTransformer#113]
I trained a gpt2 model using megatron-LM. The vocab-size is 30000, while the eos token id is 7.

when i set the start_id and end_id to 7, the fastertransformer generate a negative id。

 after some time debug, cannot figure out, so What is the possible reason for that?

**Comment by byshiue** [comment]
We don't have any idea. We don't fix the number of token, and the decoding module can also use different end id (2 in tf sample). 
Can you provide any public model to reproduce this problem?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
