### ISSUE TITLE
Any benchmarks of the cuda kernels

### ISSUE THREAD

**Issue by feihugis** [NVIDIA/FasterTransformer#115]
I'm wondering if there are any benchmarks to compare the speed of the kernels developed by FasterTransformer and PyTorch (e.g., TopK) ?

**Comment by byshiue** [comment]
We have compared internally during development. But we won't show these details in this repo. 
If you need, you can use nsight systems to compare them.

**Comment by feihugis** [comment]
Thanks @byshiue  for your quick reply. I compared [topK](https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/cuda/cuda_kernels.cu#L549-L559) with PyTorch's topK. FasterTransformer's implementation is around 20% slower than PyTorch's. I'm not sure if it is because I misuse something. I'm wondering if your internal comparisons cover this one and if yes, what's the benchmarking results?

**Comment by byshiue** [comment]
Can you provide the details about which kernel you compare, what hyper-parameters you use?

**Comment by feihugis** [comment]
I compared this one ([topK](https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/cuda/cuda_kernels.cu#L549-L559)) with PyTorch's [TopK](https://pytorch.org/docs/stable/generated/torch.topk.html). 

The input tensor is `input = torch.rand((128, 8192), device='cuda')` and K = 1.

**Comment by byshiue** [comment]
This kernel is deprecated and we don't call it in FasterTransformer. If you want to test top k in FT, you can refer https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/gpt.h#L766.

**Comment by feihugis** [comment]
@byshiue For the tensor size [18, 29824], the top-k kernel took around 37% of the pytorch top-k. Does it align with your internal benchmark?

**Comment by byshiue** [comment]
We don't have the profiling of these parameters.

**Comment by byshiue** [comment]
We only compare the speed in FT. We don't compare it with PyTorch.

**Comment by feihugis** [comment]
That's ok. Thanks for your help. I will close this issue.
