### ISSUE TITLE
How to use FT to speed up the predict of bert?

### ISSUE THREAD

**Issue by js19950726** [NVIDIA/FasterTransformer#117]
I already have my own bert model and weight, so I just wanna know how to use my weight in the fast_transformer encoder?

**Comment by js19950726** [comment]
and how to store it?

**Comment by byshiue** [comment]
Please provide more details.
The model is fully same to bert? 
What's framework you use?

**Comment by js19950726** [comment]
the model is the bert model , and the framework I used is tensorflow

**Comment by byshiue** [comment]
You can refer https://github.com/NVIDIA/FasterTransformer/blob/main/sample/tensorflow/encoder_sample.py and https://github.com/NVIDIA/FasterTransformer/blob/main/sample/tensorflow/utils/encoder.py.
