### ISSUE TITLE
using INT 8 Tensor Core

### ISSUE THREAD

**Issue by haihai-00** [NVIDIA/FasterTransformer#119]
Hi, 
I m just try to figure out the using of INT 8 Tensor Core in this great project.

- In int8_mode=2 part of Fig. 3, it shows batch Gemm 1 gives a int32 data, but in the code implemantaion, i think a "cublasLtMM_withAlgo_int8IO" is called in this step, which means a int8 result should be outputed. So I m wondering is this a mistake in Fig. 3 or I understand the implementation in a wrong way?

- And also, I m curious that in "cublasLtMM_withAlgo_int8IO", if A B C are all int8 type, C=A*B can be easily overflowed. How you take care of that issue?

**Comment by byshiue** [comment]
1. The graph shows the workflow under fused multi-head attention. In this kernel, the output type of gemm 1 is int32. While `cublasLtMM_withAlgo_int8IO` is called by unfused multi-head attention, which uses INT32 as output type of gemm1. 
2. In cuBLASLt, it will compute by `int8 * int8 -> int32`, and then `dequantize + quantize` the `int32` to `int8`. so it can prevent overflow.

**Comment by haihai-00** [comment]
Thank you for your quick reply!
So you mean cublasltmatmul API itself can prevent overflow, so user doesn’t have to worry about overflow, right?

**Comment by byshiue** [comment]
Yes, you are right.

**Comment by haihai-00** [comment]
Thank you very much.
But I m still confused about "dequantize + quantize the int32 to int8" output. 
Since I tested with a simple example:
alpha=0.015
beta=0.1
-----------A------------
  10   18   26
  50   59   68
 -11  -20  -29
 -52  -59  -68
  91  100  108
  16  122  127
[ CUDACharType{6,3} ]
-----------B------------
  20   37   47   62   79
  86   99  113  127   15
  16   17   18   20   21
[ CUDACharType{3,5} ]
-----------C------------
  16   32   48   32   48
  95  111  127   32   48
 -16  -32  -48   32   48
 -16  -32  -48   32   48
 -16  -32  -48   32   48
 -16  -32  -48   32   48
[ CUDACharType{6,5} ]
 and I got the result D from cublasLtMatmul:
-----------D------------
  34   42   49   55   29
 117  127  127  127   99
 -38  -46  -54  -54  -22
-110 -128 -128 -128  -92
 127  127  127  127  127
 127  127  127  127   91
[ CUDACharType{6,5} ]
But in torch.addmm, D should be 
--------------D in fp16------------------
tensor([[  34.0625,   42.0938,   49.3750,   54.5938,   28.8906],
        [ 116.9375,  **143.7500,  166.2500,  182.5000**,   98.7500],
        [ -37.6562,  -46.4062,  -54.2812,  -53.8438,  -21.8750],
        [-109.6250, **-137.0000, -159.8750, -178.0000**,  -91.5000],
        [ **180.6250,  223.3750,  258.0000,  310.7500,  169.1250**],
        [ **191.0000,  219.2500,  247.5000,  288.5000**,   91.1875]],
       device='cuda:0', dtype=torch.float16)
----------------------------------------------------
so we can see some elements of D is overflowed, and truncated to a max 128 and min -127.
But as you said if it is quantized from int 32 to int8, it should not be like this.  
So I m confused, could you please explain more about this result?

**Comment by byshiue** [comment]
Even we compute by INT32, when we quantize from INT32 to INT8, the values larger than 128 would be cropped to 128.
For example, 
D[1,1] = 143.75 at fp16 in torch, 
and it may be 142 at INT32 in FT, and be quantized to 128 at INT8.

**Comment by haihai-00** [comment]
ok, i got it , thank you so much
