### ISSUE TITLE
Any examples to accelerate hugging face model such as MBART, bart ?

### ISSUE THREAD

**Issue by leoozy** [NVIDIA/FasterTransformer#122]
Hello, thank you for your work. I wish to accelerate MBART with ft. But I am still confused about how to load a pretrained hugging face model with ft and use it to accelerate.

**Comment by byshiue** [comment]
You can refer https://github.com/NVIDIA/FasterTransformer/blob/main/sample/pytorch/run_glue.py, which shows how to use huggingface bert to run on FT.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
