### ISSUE TITLE
Never name a tag and a branch the same name! 

### ISSUE THREAD

**Issue by pmixer** [NVIDIA/FasterTransformer#124]
Although contributors may always working on master branch, it may be troublesome if someone want to fix former branches like me.

Pls consider renaming tags like v1.0_tag, v2.0_tag etc.

For more details, pls see
geedew.com/fixing-git-branch-and-tag-name-collision/

https://stackoverflow.com/questions/32609195/git-tags-with-the-same-name-with-a-branch

etc.

**Comment by byshiue** [comment]
Thanks for your suggestions. We have rename the tags.

**Comment by pmixer** [comment]
> Thanks for your suggestions. We have rename the tags.

dalao 666
