### ISSUE TITLE
why do we need forward_context?

### ISSUE THREAD

**Issue by Zjhzzzzz** [NVIDIA/FasterTransformer#126]
it seems that forward_context don't change any variable in global, in forward_context there are some local variable created and used in here, and then in the end.
I try to **delete forward_context and find result don't change**

**Comment by byshiue** [comment]
It is used for GPT with input context.

**Comment by Zjhzzzzz** [comment]
> It is used for GPT with input context.

from the code architecture I had thought it is used with input context, but I find forward_context don't change any variable related with forward(),  variable like from_tensor and other in forward_context is local, it seems that forward_context don't send information with input_context to next forward function.
I also change code in gpt_sample and remake it
like this
`for(....){
    gettimeofday();
// forward_context;
    forward();
}`
and result don't change.
I'm refused, plz and thx ( ;
