### ISSUE TITLE
why we need gather after recv

### ISSUE THREAD

**Issue by Zjhzzzzz** [NVIDIA/FasterTransformer#127]
after nccl_recv we get value from all tensor_paraller rank to from_tensor[in_id] in range [+ite * m * h_1, +(ite + 1) * m * h_1] and set successfully

but ncclAllGather do the same thing to set from_tensor[in_id] in range [+ite * m * h_1, +(ite + 1) * m * h_1] 

I now don't have multi GPUs machine to verify it, I'm confused to the code all2all_gather after nccl_recv.

**Comment by byshiue** [comment]
I am not sure which part you ask.
I guess you ask https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/gpt.h#L560, and the reason is because we only send part to data for nccl_send, and each gpu in tensor parallel only recv part of the results. So, they need a allGather to get other parts from other GPUs.

**Comment by Zjhzzzzz** [comment]
> https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/gpt.h#L560

I'm sry I forget to tell you where I say, it's in https://github.com/NVIDIA/FasterTransformer/blob/33a632ee6414a7778fec8d9893a7733b79880abd/fastertransformer/gpt.h#L371
it seems in that range in from_tensor[in_id], it divided to tensor_parallel_param.world_size parts, and each rank in tensor_parallel_rank has one size, all are world_size * size.

**Comment by Zjhzzzzz** [comment]
> I am not sure which part you ask.
> I guess you ask https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/gpt.h#L560, and the reason is because we only send part to data for nccl_send, and each gpu in tensor parallel only recv part of the results. So, they need a allGather to get other parts from other GPUs.

I mean that if tensor_parallel has two rank, from_tensor[in_id] in range [+ite * m * h_1, +(ite + 1) * m * h_1] is divided into two parts, and part0([+ite * m * h_1, +ite * m * h_1 + m * h_1 / 2]) recv data from rank0, part1([+ite * m * h_1 + m * h_1 / 2, +ite * m * h_1 + m * h_1]) recv data from rank1.

so it seems that all in this range recv data in nccl_recv, not part of it.

**Comment by byshiue** [comment]
> > I am not sure which part you ask.
> > I guess you ask https://github.com/NVIDIA/FasterTransformer/blob/main/fastertransformer/gpt.h#L560, and the reason is because we only send part to data for nccl_send, and each gpu in tensor parallel only recv part of the results. So, they need a allGather to get other parts from other GPUs.
> 
> I mean that if tensor_parallel has two rank, **from_tensor[in_id]** in range [+ite * m * h_1, +(ite + 1) * m * h_1] is divided into two parts, and part0([+ite * m * h_1, +ite * m * h_1 + m * h_1 / 2]) recv data from rank0, part1([+ite * m * h_1 + m * h_1 / 2, +ite * m * h_1 + m * h_1]) recv data from rank1.
> 
> so it seems that all in this range recv data in nccl_recv, not part of it.

part0 recv data from rank0, part1 recv data from rank1. And we need to send the data of rank0 to rank1 (same as rank1 to rank0). Otherwise, they only have `m * h_1/2` data, but not `m * h_1` data.

**Comment by Zjhzzzzz** [comment]
> part0 recv data from rank0, part1 recv data from rank1. And we need to send the data of rank0 to rank1 (same as rank1 to rank0). Otherwise, they only have `m * h_1/2` data, but not `m * h_1` data.

thx, but I have another question, why we need set tensor_para rank0 and rank1 have all `m * h_1` data, it seems don't need set tensor_parallel rank have all `m * h_1` data.

**Comment by byshiue** [comment]
The input of decoder should be the full input. So, we need the all `m * h_1` data.

**Comment by Zjhzzzzz** [comment]
> The input of decoder should be the full input. So, we need the all `m * h_1` data.

I'm not very understand, input is **from_tensor[in_id]**, and it got from layer_parallel.rank in **nccl_recv**, 
but all2all_gather just set all tensor_parallel rank like rank0 and rank1 have all `m * h_1` data, I'm confused about why make tensor_parallel rank have `m * h_1` data
