### ISSUE TITLE
Pytorch Translation demo failure due to onmt import errors

### ISSUE THREAD

**Issue by HamidShojanazeri** [NVIDIA/FasterTransformer#129]
Running the Translation demo
```
python pytorch/run_translation.py --batch_size 128 --beam_size 4 --model_type decoding_ext --data_type fp32
```
It fails with error:
```
Traceback (most recent call last):
  File "pytorch/run_translation.py", line 20, in <module>
    from utils.translation_model import load_test_model
  File "/workspace/FasterTransformer/build/pytorch/utils/translation_model.py", line 25, in <module>
    from onmt.modules import Embeddings, VecEmbedding, CopyGenerator
ImportError: cannot import name 'VecEmbedding' from 'onmt.modules' (/opt/conda/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/modules/__init__.py)
```
#### GPU = T4
I haven't been able to find the "VecEmbedding" on the onmt repo anymore, any workaround would be appreciated.

**Comment by byshiue** [comment]
The example is based on opennmt-py==1.1.1, please check https://github.com/NVIDIA/FasterTransformer/blob/main/docs/decoder_guide.md#decoder-and-decoding-process.

**Comment by HamidShojanazeri** [comment]
@byshiue Thanks for the pointer, I was wondering if there is an example using both FT encoder decoder in a model such as BERT for QA or Translation models, it seems in translation demo, only decoder is been replaced with FT and in squad only encoder. I would appreciate any guide, pointer on that front as well.

**Comment by byshiue** [comment]
https://github.com/NVIDIA/FasterTransformer/blob/main/sample/tensorflow/translate_sample.py
This examples uses both encoder and decoder of FT.

**Comment by HamidShojanazeri** [comment]
@byshiue I see, is this encoder+decoder available for Pytorch as well?

**Comment by byshiue** [comment]
Currently no. You need to add a pytorch op of encoder.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
