### ISSUE TITLE
what is the difference of rm-padding = True and rm-padding = False?

### ISSUE THREAD

**Issue by js19950726** [NVIDIA/FasterTransformer#130]
what is the difference of rm-padding = True and rm-padding = False?

**Comment by js19950726** [comment]
why rm-padding = True is faster than rm-padding = False

**Comment by byshiue** [comment]
When setting the flag to be true, it will remove the useless padding. Details are in https://github.com/NVIDIA/FasterTransformer/blob/main/docs/encoder_guide.md#standard-bert-and-effective-fastertransformer.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
