### ISSUE TITLE
torch compile error.

### ISSUE THREAD

**Issue by ChenCongGit** [NVIDIA/FasterTransformer#131]
error: no matching function for call to ‘torch::class_<torch_ths::FasterTransformerEncoder>::class_(const char [25])’
   torch::jit::class_<torch_ths::FasterTransformerEncoder>("FasterTransformerEncoder")

**Comment by ChenCongGit** [comment]
Building CXX object fastertransformer/th_op/CMakeFiles/ths_fastertransformer.dir/ft_ths_op.cc.o

**Comment by byshiue** [comment]
Please provide more details. 
FasterTransformer version, environment, docker image and scripts for building repo.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Comment by lss15151161** [comment]
add a parameter like this:
torch::jit::class_<torch_ths::FasterTransformerEncoder>("FasterTransformerEncoder", "FasterTransformer")
