### ISSUE TITLE
GPT model question

### ISSUE THREAD

**Issue by ifromeast** [NVIDIA/FasterTransformer#133]
Hi, I read the code in `gpt.py` and found that it imports `torch.classes.FasterTransformer.GPT`. 
While I try to run `import torch
gpt = torch.classes.FasterTransformer.GPT()`, it will occur error that 
>>>RuntimeError: Tried to instantiate class 'FasterTransformer.GPT', but it does not exist! Ensure that it is registered via torch::class_

Why this happen, and how to learn the model in detail?

Many thanks!

**Comment by byshiue** [comment]
It is a custom op. You can see the source code in `fastertransformer/th_op/gpt.cc`.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
