### ISSUE TITLE
Support of Vision Transformer

### ISSUE THREAD

**Issue by liyilui** [NVIDIA/FasterTransformer#134]
Hi,
I am looking at whether it would be possible to leverage FasterTransformer in vision transformers, where attention modules are the same but embedding layer is different. There will also be some extra operators in between attention modules.
Thanks!

**Comment by byshiue** [comment]
The encoder module does not contains the embedding layer, so you can use any embedding implementation. 
However, if you need extra operations between attention modules, you need to modify the source codes.

**Comment by byshiue** [comment]
The latest release supports ViT and SwinTransformer.
