### ISSUE TITLE
Accuracy issue with CustomEncoder

### ISSUE THREAD

**Issue by feihugis** [NVIDIA/FasterTransformer#136]
When running the  CustomEncoder pytorch sample (section 3.2 of https://github.com/NVIDIA/FasterTransformer/blob/main/docs/encoder_guide.md):

- If I use the random weights (run command `python pytorch/encoder_sample.py 1 6 32 8 64`), the outputs of FT and HuggingFace (HF) are almost the same as below:
```
FT Mean diff: 4.987276952306274e-06
FT Max diff:  6.219744682312012e-05
FT Min diff:  0.0
```

- However, when I switch to my model weights (run command `python pytorch/encoder_sample.py 1 6 32 8 64 --weight_path PATH`), the output differences between FT and HF are obvious as below and the final model outputs are different as well.
```
FT Mean diff: 0.000707874889485538
FT Max diff:  0.15046310424804688
FT Min diff:  0.0
```

I'm wondering if anyone has any ideas about the above issue?

The model weight can be found [here](https://drive.google.com/file/d/1klEVEsF3mmy7rnDh8hlPSYCPWRwmIegy/view?usp=sharing).

**Comment by byshiue** [comment]
You can try to compare the relative difference because the absolute difference may be large when the values of output are large.

**Comment by feihugis** [comment]
After using `diff = torch.abs(hf_output - ft_output) / ( hf_output + 0.000001)` to compute the relative difference, I got the below differences:

- For random weights:
```
FT Mean diff: 6.356652011163533e-05
FT Max diff:  0.02380697801709175
FT Min diff:  0.0
```
- For the actual model weight:
```
FT Mean diff: 0.058397240936756134
FT Max diff:  230.2880859375
FT Min diff:  0.0
```

**Comment by byshiue** [comment]
The reason is because that FasterTransformer uses approximated gelu, while pytorch uses original gelu function. 
You can solve it by modifying 
```bash
conf = BertConfig(hidden_size=hidden_dim, intermediate_size=4*hidden_dim, num_attention_heads=head_num, num_hidden_layers=layer_num)
```
of https://github.com/NVIDIA/FasterTransformer/blob/main/sample/pytorch/utils/encoder.py#L210 to
```bash
conf = BertConfig(hidden_size=hidden_dim, intermediate_size=4*hidden_dim, num_attention_heads=head_num, num_hidden_layers=layer_num, hidden_act='gelu_new')
```

**Comment by feihugis** [comment]
Thanks so much for your help, @byshiue! I'm curious how you find the root cause? Could you share some experience of how to debug the code of FasterTransformer, especially the cuda kernel code?

**Comment by byshiue** [comment]
I only compare the results of FasterTransformer and PyTorch layer by layer.

**Comment by feihugis** [comment]
Thanks @byshiue!
