### ISSUE TITLE
[Tensorflow Serving][solved] failed: Not found: Op type not registered 'OpenEncoder' in binary running

### ISSUE THREAD

**Issue by dongdaoking** [NVIDIA/FasterTransformer#137]
Related to running fastertransformer within tensorflow serving.
I compile FasterTransformer v4 and obtain all library files like ”libtf_fastertransformer.so“. And based on these files, i can quickly run fastertransformer by tf.load_op_library.
But when i export the model and run in tensorflow serving, it produce the error "Op type not registered 'OpenEncoder' in binary running". It’s clear default tensorflow doesn't exist custom op in fastertransformer.
In order to add operations, I recompile the tensorflow serving 1.15.0 with these library files.
Root dir: serving-1.15.0
I create directory named ”custom_ops“ in serving-1.15.0/tensorflow_serving and move all library files into the dir.
A BUILD file in it following [adding-dependencies-on-precompiled-libraries](https://docs.bazel.build/versions/0.24.0/cpp-use-cases.html#adding-dependencies-on-precompiled-libraries).
```
licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fastertransformer_lib",
    srcs = [
        "libtf_fastertransformer.so",
        "libtf_decoding_beamsearch.so",
    ],
    alwayslink = 1,
)
```
Add [SUPPORTED_TENSORFLOW_OPS](https://github.com/tensorflow/serving/blob/1.15.0/tensorflow_serving/model_servers/BUILD#L296)
```
SUPPORTED_TENSORFLOW_OPS = if_v2([]) + if_not_v2([
    "@org_tensorflow//tensorflow/contrib:contrib_kernels",
    "@org_tensorflow//tensorflow/contrib:contrib_ops_op_lib",
    "//tensorflow_serving/custom_ops:fastertransformer_lib"
])
```
I try to check the link by `ldd tensorflow_model_server`
```
libtf_fastertransformer.so => .cache/_bazel_root/1a2eae45fce063f61bb89c04dfa8d9b4/execroot/tf_serving/bazel-out/k8-opt/bin/tensorflow_serving/model_servers/./../../_solib_local/_U_S_Stensorflow_Userving_Scustom_Uops_Cfastertransformer_Ulib_Uenc___Utensorflow_Userving_Scustom_Uops/libtf_fastertransformer.so (0x00007f9f9a92c000)
libtf_decoding_beamsearch.so =>.cache/_bazel_root/1a2eae45fce063f61bb89c04dfa8d9b4/execroot/tf_serving/bazel-out/k8-opt/bin/tensorflow_serving/model_servers/./../../_solib_local/_U_S_Stensorflow_Userving_Scustom_Uops_Cfastertransformer_Ulib_Udec___Utensorflow_Userving_Scustom_Uops/libtf_decoding_beamsearch.so (0x00007f9f99aa0000)
...
```
**But it doesn't work.**
I'm not sure fastertransformer cannot support tensorflow serving essentially or I do something wrong(i think i'm wrong).
So can someone give me some advice, i need help.

**update**
Actually, it does work and need one more operation.
```
patchelf --remove-needed libtensorflow_framework.so.1 libtf_decoding_beamsearch.so
patchelf --remove-needed libtensorflow_framework.so.1 libtf_fastertransformer.so
```

**Comment by ghtwht** [comment]
你好，想问下这里的
patchelf --remove-needed libtensorflow_framework.so.1 libtf_decoding_beamsearch.so
patchelf --remove-needed libtensorflow_framework.so.1 libtf_fastertransformer.so
是要在什么路径下运行呢？

**Comment by dongdaoking** [comment]
> 你好，想问下这里的 patchelf --remove-needed libtensorflow_framework.so.1 libtf_decoding_beamsearch.so patchelf --remove-needed libtensorflow_framework.so.1 libtf_fastertransformer.so 是要在什么路径下运行呢，以及这个是在bazel编译之前就运行的吗？

1. anywhere you can run "patchelf"; 2. yes, before compiling

**Comment by ghtwht** [comment]
after **patchlf** , my ldd results is OK since no "libtensorflow_framework.so.1 => /data/venv/tf1/lib/python3.6/site-packages/tensorflow_core/libtensorflow_framework.so.1 (0x00007f74e04d7000)"  shows anymore, but when serving model , it still occurs:
 "E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: trans version: 1} failed: Invalid argument: No OpKernel was registered to support Op 'BuildMaskRemovePadding' used by {{node transformer/encoder/BuildMaskRemovePadding}}with these attrs: [T=DT_FLOAT, _output_shapes=[[?,512], [?]]]"
 and this os should be included in "**libtf_fastertransformer.so**" according to the code below:
`transformer_op_module = tf.load_op_library(os.path.join('./lib/libtf_fastertransformer.so'))
    if remove_padding == True:
        inputs, sequence_id_offset = transformer_op_module.build_mask_remove_padding(inputs, sequence_length)
        trt_seq_len = tf.cumsum(tf.concat([[0], sequence_length], axis=0), axis=0)
`
did you meet this error?

**Comment by dongdaoking** [comment]
No, maybe you need check your compiling.

**Comment by ghtwht** [comment]
> your

OK, I will try to recompile it ~~ thanks
