### ISSUE TITLE
Do you have an plan to merge the ft into nvidia tf directly. it maybe more convenient and accessible.

### ISSUE THREAD

**Issue by ssbuild** [NVIDIA/FasterTransformer#142]

**Comment by byshiue** [comment]
FasterTransformer not only provides the TensorFlow op, it also provides PyTorch op and Triton backend. So, we don't plan to merge FasterTransformer into TensorFlow.

**Comment by ssbuild** [comment]
> FasterTransformer not only provides the TensorFlow op, it also provides PyTorch op and Triton backend. So, we don't plan to merge FasterTransformer into TensorFlow.

I hope load weight by pb graph automatically ，hope export and import like normal bert .  if merge ft into tf ,  Whether need to modify the tf pb  ? can you provide any advise. @byshiue

**Comment by byshiue** [comment]
You can write a parser to replace the all nodes of BERT in pb by FT's op.
