### ISSUE TITLE
forward_context seems useless because cross-multi-head attention is not used.

### ISSUE THREAD

**Issue by Zjhzzzzz** [NVIDIA/FasterTransformer#144]
it seems context information are not used in **decoder->forward** in https://github.com/NVIDIA/FasterTransformer/blob/dd4c071755b1b5206c6987add6145eac03f6814d/fastertransformer/gpt.h#L595 
because is_cross_attention is false. and I delete this forward_context and remake it, then run demo again find result not changed. https://github.com/NVIDIA/FasterTransformer/blob/dd4c071755b1b5206c6987add6145eac03f6814d/fastertransformer/gpt.h#L395

so what need I do if I want to use context-information, set global variable in forward_context?

**Comment by byshiue** [comment]
I don't know what demo you run. If the demo does not contains the context, then removing the forward_context is fine. 
forward_context is used to compute the k/v cache of context, which are used in self attention, but not cross attention.

**Comment by Zjhzzzzz** [comment]
> I don't know what demo you run. If the demo does not contains the context, then removing the forward_context is fine.
> forward_context is used to compute the k/v cache of context, which are used in self attention, but not cross attention.

thank you for help, I run gpt_sample demo with head_num=96,layers=1,batch=1, maybe in this demo k/v cache influence not enought.

**Comment by byshiue** [comment]
Can you provide all hyper-parameters you use? 
batch_size=1
input_len=?
output_len=?
Environment=?(TF/PyTorch/C/Triton)
scripts=?

**Comment by Zjhzzzzz** [comment]
> Can you provide all hyper-parameters you use?
> batch_size=1
> input_len=?
> output_len=?
> Environment=?(TF/PyTorch/C/Triton)
> scripts=?

input_len=512
output_len=32
environment=c
scripts=./bin/gpt_sample

**Comment by byshiue** [comment]
This example uses the cache. If you remove the forward_context, the results should be wrong.

**Comment by Zjhzzzzz** [comment]
> Can you provide all hyper-parameters you use?
> batch_size=1
> input_len=?
> output_len=?
> Environment=?(TF/PyTorch/C/Triton)
> scripts=?

yes it uses the cache, but whether I used decoder->forward_context, out is "464 968 8221 2732 286 15198 318 464 968 1971 12056 423 257 649 1182 464 968 1971 3782 468 3199 663 5079"

**Comment by Zjhzzzzz** [comment]
> This example uses the cache. If you remove the forward_context, the results should be wrong.

my gpu is 2080ti, when use forward_context it is 6.6ms, not use forward_context is 1.6ms

**Comment by byshiue** [comment]
> > This example uses the cache. If you remove the forward_context, the results should be wrong.
> 
> my gpu is 2080ti, when use forward_context it is 6.6ms, not use forward_context is 1.6ms

The time makes sense, and it seems that there is no any problem.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
