### ISSUE TITLE
Compare with beam search of opennmt translation

### ISSUE THREAD

**Issue by baoyu-yuan** [NVIDIA/FasterTransformer#146]
I found that the beam search results gotten by comparing with your own implemented version but not with the opennmt version beam search. And your code imports BeamSearch Class from opennmt but it's not used. Do you plan to add results compare with the BeamSearch from opennmt, which will be more convincing..

**Comment by byshiue** [comment]
The implementation of beam search refers the opennmt. The reason we write a kernel by ourselves because we have to demonstrate the usage of op_decoder.

**Comment by baorave** [comment]
> The implementation of beam search refers the opennmt. The reason we write a kernel by ourselves because we have to demonstrate the usage of op_decoder.

OK，thank you.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
