### ISSUE TITLE
ft-tensorflow-quantization cannot work with tensorflow==1.14.0

### ISSUE THREAD

**Issue by zhuango** [NVIDIA/FasterTransformer#150]
I recently run PTQ with bert-tf-quantization tool. Following FasterTransformer [README](https://github.com/NVIDIA/FasterTransformer), I have tensorflow==1.14.0 in my environment, which should be sopported. But I got an error saying "Dense object has no attribute _compute_dtype". Then I installed tensorflow==1.15.0, and problem solved. Is the README out of date or something wrong with my environment ?

**Comment by byshiue** [comment]
Thanks for your feedback. In the document, we mean that the FT TensorFlow op should support on TensorFlow 1.13, 1.14 and 1.15. 

But we don't verify all workflows on different environment. We will modify the document to distinguish the "verified environment" and "possible environment" in the future.

**Comment by zhuango** [comment]
Thanks ! @byshiue
