### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by daeing** [NVIDIA/FasterTransformer#158]
when i build the project with pytorch:
cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..

it shows:
CMake Error at cmake/Modules/FindNCCL.cmake:153 (message): Found NCCL header version and library version do not match! (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so) Please set NCCL_INCLUDE_DIR and NCCL_LIB_DIR manually.

how to solve this problem?

**Comment by byshiue** [comment]
Can you try the docker image we suggest?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Comment by hamza-alethea** [comment]
> Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.



> when i build the project with pytorch: cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..
> 
> it shows: CMake Error at cmake/Modules/FindNCCL.cmake:153 (message): Found NCCL header version and library version do not match! (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so) Please set NCCL_INCLUDE_DIR and NCCL_LIB_DIR manually.
> 
> how to solve this problem?

i also got this error
