### ISSUE TITLE
Is GPU A10 supported?

### ISSUE THREAD

**Issue by lianoid** [NVIDIA/FasterTransformer#159]
Hi，when i compile faster-transformer on GPU A10（Not A100），use command：“cmake -DSM=xx ...”，

I have few questions：
1、In this command(cmake -DSM=xx ...), what is the value of xx?

2、I didn't find the "Compute Capability" of A10 in Nvidia official website, does faster-transformer support A10?
https://developer.nvidia.com/zh-cn/cuda-gpus

-------------------中文---------------
你好，我们在A10显卡上编译 faster-transformer 时，使用命令：“cmake -DSM=xx ...”，
有几个问题咨询：
1、xx的值应该设置多少？
2、我在Nvidia官网也没有找到这块显卡的算力值，请问faster-transformer支持A10显卡吗？

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
