### ISSUE TITLE
is Normalize after structure for decoder  supported?

### ISSUE THREAD

**Issue by HamidShojanazeri** [NVIDIA/FasterTransformer#161]
I am looking into converting a Fairseq decoder to FT version, the model has not been trained with "normalize_before=True" and was wondering if support for Normalize after structure for decoder  is available or on the roadmap?

**Comment by byshiue** [comment]
We don't have such plan now.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
