### ISSUE TITLE
Why dev/v5.0_beta is not merged?

### ISSUE THREAD

**Issue by amantalion** [NVIDIA/FasterTransformer#162]
Hi @byshiue, thanks for the great work! I just wanted to ask why `dev/v5.0_beta` hasn't been merged yet? Is there anything wrong with that branch?

**Comment by byshiue** [comment]
No correctness issue now. The reason is because we plan to modify some API recently. 
To prevent the users modify their API to integrate FT, we do merge the beta branch.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
