### ISSUE TITLE
[ERROR][BertEncoderTransformer] int8 mode only works with sm >= 75.

### ISSUE THREAD

**Issue by flygragon** [NVIDIA/FasterTransformer#163]
could encoders be run on V100, P100, P40 in int8 mode？

**Comment by byshiue** [comment]
These GPUs do not contain the INT8 tensor cores. They may be runnable, but may be slower.

**Comment by flygragon** [comment]
> These GPUs do not contain the INT8 tensor cores. They may be runnable, but may be slower.

I had a try, but gemm test failed. I think this maybe result from that int8 weights are stored on tensor cores that don't support int8 calculations.

**Comment by byshiue** [comment]
FasterTransformer does not provide the feature to run INT8 on cuda core (Namely, on GPU before Turing).

**Comment by flygragon** [comment]
> FasterTransformer does not provide the feature to run INT8 on cuda core (Namely, on GPU before Turing).

It was proved to be true after I tried to comment codes "exit(-1)" behind the sm judgement.

**Comment by 520jefferson** [comment]
what's the means of SM,  and have you resolved it ?

**Comment by byshiue** [comment]
No. It is a limitation due to hardware.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
