### ISSUE TITLE
 the difference between the decoding in the models folder and the decoding in th_op folder

### ISSUE THREAD

**Issue by cjt222** [NVIDIA/FasterTransformer#167]
Thans for great jobs! In the dev/v5.0beta version, what is the difference between the decoding in the models folder and the decoding in th_op? Is it possible to output the cum_log_probs_ value? How to call the code in the models folder?

**Comment by byshiue** [comment]
The decoding in the models folder contains the source codes of decoding module. 
The decoding in th_op encapsulate the decoding modules by pytorch op API. 
Currently, it does not support to return the `cum_log_probs`.
You can see `example/cpp/decoding_example.cc` to understand how to call the decoding.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
