### ISSUE TITLE
No speedup with int8 comparing to fp16 when seqlen and batchsize are small

### ISSUE THREAD

**Issue by woskii** [NVIDIA/FasterTransformer#171]
Hi,
As shown in the [figure](https://github.com/NVIDIA/FasterTransformer#encoder-performance-on-pytorch), on PyTorch, FasterTransformer int8 doesn't speedup better comparing to  FasterTransformer  fp16 when sequence length and batch size are small. As computation with int8 precision is faster, why FasterTransformer int8 does not perform as expected?
Thanks in advance!

**Comment by byshiue** [comment]
Because we need additional quantization/dequantization when we use INT8 mode.

**Comment by woskii** [comment]
Thank you for the quick reply!

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
