### ISSUE TITLE
There is a problem with the accuracy of fp16

### ISSUE THREAD

**Issue by dingjingzhen** [NVIDIA/FasterTransformer#172]
hi，
   when I use gpt fp16 to do inference, I find that there is a problem with accuracy and the generated result is not correct. Is there a problem with faster transformer's support for gpt fp16?

**Comment by byshiue** [comment]
Can you describe the details of the problem you encounter? 
The results of FP16 may be little different to FP32, this is a common behavior. But the results of FP16 should still make sense.

**Comment by dingjingzhen** [comment]
![image](https://user-images.githubusercontent.com/21244263/146371446-56f330c6-ad80-49ca-91db-688d7c114df3.png)

![image](https://user-images.githubusercontent.com/21244263/146371650-a68904df-f80c-4956-b31f-6bdaefbd6837.png)

Hello.
    As shown in the picture.And I don't think there should be such a big difference between fp32 and fp16. Because when I reason with other frameworks, fp16 and fp32 can maintain very good accuracy.This model is the one you provide, which is relatively small, and if it were a bigger model, the difference might not be acceptable.

**Comment by byshiue** [comment]
If you use the public model we use in the guide, then it should generate correct sentences. We have verified the correctness. 
Can you provide the reproduce steps? Including the docker image, converting model and running script.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
