### ISSUE TITLE
CUDA Error when running pytorch/encoder_sample.py

### ISSUE THREAD

**Issue by zyh3826** [NVIDIA/FasterTransformer#177]
When I use  python3 pytorch/encoder_sample.py 32 12 32 12 64 --time, I find some cuda error

> CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238
CUDA Error: (null) /root/opensource/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243

but the program does'n abort, is this info normal?
My environments:
cpu: Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
cuda: 10.2
gpu: RTX 2080Ti
sys: ubuntu 18.04

**Comment by byshiue** [comment]
Do you use the docker in the guide?

**Comment by zyh3826** [comment]
> Do you use the docker in the guide?
I use docker but not in the guide,  in my docker: pytorch 1.7.1, nccl 2.11.4, openmpi 4.0.7

**Comment by byshiue** [comment]
Can you try the docker and steps in the guide first?

**Comment by ustcdane** [comment]
Hi,   @byshiue  @zyh3826   I encountered similar mistakes. 
When I use python3 pytorch/encoder_sample.py 32 12 32 12 64 --time,  it is ok~
But, when I use python3 pytorch/encoder_sample.py 32 12 32 12 64 --time **--int8_mode 2**, I find some cuda error

My environment:
CPU: Intel-4214R-2400-12*2	
CUDA: 11.1
GPU: Nvidia-Tesla-A10-24G*4	
Sys: centos-7.6-x86_64
FT :  nccl_dependent_refine

Log message:
CUDA Error: (null) /search/odin//FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 
CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558

**Comment by byshiue** [comment]
> Hi, @byshiue @zyh3826 I encountered similar mistakes. When I use python3 pytorch/encoder_sample.py 32 12 32 12 64 --time, it is ok~ But, when I use python3 pytorch/encoder_sample.py 32 12 32 12 64 --time **--int8_mode 2**, I find some cuda error
> 
> My environment: CPU: Intel-4214R-2400-12_2 CUDA: 11.1 GPU: Nvidia-Tesla-A10-24G_4 Sys: centos-7.6-x86_64 FT : nccl_dependent_refine
> 
> Log message: CUDA Error: (null) /search/odin//FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 232 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 238 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention.h 243 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558 CUDA Error: (null) /search/home/FasterTransformer/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 558

Which docker do you use?

**Comment by ustcdane** [comment]
hi， @byshiue   I didn't use  docker,  just build on   centos-7.6-x86_64


cmake -DBUILD_THS=ON -DBUILD_TRT=ON -DBUILD_THE=ON -DBUILD_PYT=ON -DBUILD_GPT=OFF -DCXX_STD=14  -DTRT_PATH=/search/home/TensorRT-7.2.3.4  -DSM=86 -DCMAKE_BUILD_TYPE=Release   ..  make -j

My environment:
CPU: Intel-4214R-2400-122
CUDA: 11.1
GPU: Nvidia-Tesla-A10-24G4
Sys: centos-7.6-x86_64
FT  version : nccl_dependent_refine
gcc 5.4

**Comment by byshiue** [comment]
If you don't use docker, we cannot reproduce your problem. 
You can try the v5.0-dev branch first, and also try to disable the fused mha module of encoder first.

**Comment by ustcdane** [comment]
Thanks for reply.  I will try.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Comment by yklidelong** [comment]
> Thanks for reply. I will try.

hi，I‘ve got the same error log，have you got any idea about this problem？
