### ISSUE TITLE
Benchmarking models

### ISSUE THREAD

**Issue by bharatv007** [NVIDIA/FasterTransformer#179]
I am interested in benchmarking models of different sizes from millions of parameters to billions of parameters. These models are not of standard sizes but the architecture is vanilla gpt/bert.

For initial benchmarking I would like to just run them without loading any weights (vocab size is about the same as gpt2). For GPT sampling, I would like to benchmark for different input context, output context length and batch. For BERT, it will be just be batch and input context length. The benchmarking can be on tf/pytorch/c. 

What is the best approach to benchmarking?

**Comment by bharatv007** [comment]
I commented out the model.load() to not reload any checkpoint and I am running this command
`python ./pytorch/gpt_sample.py --output_len=919 --time --max_batch_size=1 --sample_input_file=" " --max_seq_len=1024`
It gives me giberrish (it is expected, since they are random weights).
But when I add fp16 flag like shown below the tensors are all -1, I get a key error in the decoding.
`python ./pytorch/gpt_sample.py --output_len=919 --time --max_batch_size=1 --sample_input_file=" " --max_seq_len=1024 --fp16`

> =============== Arguments ===============
layer_num: 24
output_len: 100
head_num: 16
size_per_head: 64
vocab_size: 50304
top_k: 1
top_p: 0.0
temperature: 1.0
tensor_para_size: 1
layer_para_size: 1
layer_para_batch_size: 1
ckpt_path: ../models/megatron-models/c-model/345m/1-gpu
lib_path: ./lib/libpyt_fastertransformer.so
vocab_file: ../models/gpt2-vocab.json
merges_file: ../models/gpt2-merges.txt
start_id: 50256
end_id: 50256
max_batch_size: 1
max_seq_len: 1024
fp16: True
time: True
sample_input_file:
sample_output_file: None
=========================================

> /workspace/FasterTransformer/build/pytorch/gpt_sample.py(106)main()
-> if args.sample_input_file:  # conditional case
(Pdb) c
[INFO] batch size: 1
[WARNING] decoding_gemm_config.in is not found
[WARNING] decoding_gemm_config.in is not found
Traceback (most recent call last):
  File "./pytorch/gpt_sample.py", line 168, in <module>
    main()
  File "./pytorch/gpt_sample.py", line 106, in main
    if args.sample_input_file:  # conditional case
  File "/workspace/FasterTransformer/build/pytorch/utils/gpt_token_encoder.py", line 142, in decode
    text = ''.join([self.decoder[token] for token in tokens])
  File "/workspace/FasterTransformer/build/pytorch/utils/gpt_token_encoder.py", line 142, in <listcomp>
    text = ''.join([self.decoder[token] for token in tokens])
KeyError: -1

**Comment by bharatv007** [comment]
I also get this warning
`[WARNING] decoding_gemm_config.in is not found`
can this be ignored?

**Comment by byshiue** [comment]
I think that's because the useless position is set to -1. You can comment the decode part. 
In fact, you can only keep the part of args.time because we don't use decode in this part. The first block of codes are used to demo how to use.

**Comment by bharatv007** [comment]
Thanks for the quick reply :)
what do you mean by `useless position is set to -1`. I also dont understand why this occurs only for fp16 and not fp32.

**Comment by byshiue** [comment]
For example, the output tensor length is set to 128, but the length of generated sentence is only 100, then we need to add 28 padding. In such cases, we often add some "impossible" values (like -1 here). This is only a concept. For the real reason of this case, I need to review the codes in details.

**Comment by bharatv007** [comment]
Sorry, my bad, the command I posted earlier was wrong (fixed now), I am doing unconditional generation. I havn't made any changes to the code other than skipping weights restoration.

**Comment by bharatv007** [comment]
Closing this for now, thanks for the quick help @byshiue
