### ISSUE TITLE
Batched sampling is slower

### ISSUE THREAD

**Issue by bharatv007** [NVIDIA/FasterTransformer#180]
I am running my experiments on pytorch ngc container. (nvcr.io/nvidia/pytorch:20.12-py3)
Followed all the steps to set up gpt_sample
1. Downloaded vocab
2. Downloaded 345m ckpt from megatron
3. Running gpt_sample 

`python ./pytorch/gpt_sample.py --output_len=<output_len> --time --max_batch_size=<batch> --max_seq_len=1024 --fp16 --sample_input_file=<text_file>`

Hvnt made any changes to the code. My context is of size [Batch, 105]

Noticed that as the batch size increases (more inputs), the sampling time scales propotional to the batch (there is no parallelization?). Are there any flags that need to be added here?

Timing results of gpt sampling (in ms)
|         | Batch=1      | Batch=8      |  Batch=1      | Batch=8      |
| ------- | ------------ | ------------ |------------ | ------------ |
| Next\_n | 355m-FT-fp32 | 355m-FT-fp32 | 355m-FT-fp16 | 355m-FT-fp16 |
| 128     | 346          | 2706          | 252 | 1967 |
| 256     | 702          | 5521          | 505 | 3977 |
| 512     | 1430         | 11337         | 1048 | 8242 |
| 919    | 2641         | 21022         | 1992 | 15613 |

**Comment by bharatv007** [comment]
I get the following warning, but may be not relevant?
>[WARNING] decoding_gemm_config.in is not found                                                                                                                                                                                                                
>[WARNING] decoding_gemm_config.in is not found

**Comment by byshiue** [comment]
How do you control the batch size and output length? The batch size is determined by the context (input file) directly, and the output length is controled by `--output_len`.
Besides, what GPU do you use?

**Comment by bharatv007** [comment]
I am using a 1 A100 GPU. I get the same time even if there is no context.

```
1. python ./pytorch/gpt_sample.py --output_len=256 --time --max_batch_size=1 --max_seq_len=1024 --fp16
2. python ./pytorch/gpt_sample.py --output_len=256 --time --max_batch_size=8 --max_seq_len=1024 --fp16
```
Step time for 1 is 478 ms
Step time for 2 is 3720 (~8x) ms.

**Comment by byshiue** [comment]
The reason is because the "layer_para_batch_size" is set to 1 by default. 
This will split your "max_batch_size" to multiple "layer_para_batch_size". 
You should get reasonable performance by 
```
python ./pytorch/gpt_sample.py --output_len=256 --time --max_batch_size=8 --max_seq_len=1024 --fp16 --layer_para_batch_size 8
```

**Comment by bharatv007** [comment]
@byshiue  that works, thanks for the tip. A follow up question.
 Does fastertranformer support variable batching?
 For example, requests can range from batch size of 1 to batch 100

**Comment by byshiue** [comment]
Yes.

**Comment by bharatv007** [comment]
Hey, I am trying to understand this better
`torch.classes.FasterTransformer.GPT` takes model hparams (head_num, vocab_size etc), sampling params(top_p, top_k) and batching params (tensor_para_size, layer_para_size, layer_para_batch_size) to instantiate the model. So after the model is initiated, the batching params can not be updated? its not yet clear to me how dynamic batching is still supported? Also sampling params are also fixed, is that also fixed or dynamic?

**Comment by byshiue** [comment]
Currently, only support dynamic batch size.

**Comment by bharatv007** [comment]
Thanks for the quick reply. Is there a plan to make sampling/decoding params dynamic?

**Comment by byshiue** [comment]
We will add the feature when next beta update.
