### ISSUE TITLE
Separate Input and Output Embeddings and Output embedding bias

### ISSUE THREAD

**Issue by bharatv007** [NVIDIA/FasterTransformer#186]
Looking at the megatron and openAI ckpt conversion, the input and final layers embeddings are shared and it seems that FasterTransformer does not support final layer output_projection (as in GPT3, Gopher etc). But the change log says that it supports GPT3.

```
wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/megatron_lm_345m/versions/v0.0/zip -O megatron_lm_345m_v0.0.zip
mkdir -p models/megatron-models/345m
unzip megatron_lm_345m_v0.0.zip -d models/megatron-models/345m
git clone https://github.com/NVIDIA/Megatron-LM.git
python ../sample/pytorch/utils/megatron_ckpt_convert.py -head_num 16 -i ./models/megatron-models/345m/release/ -o ./models/megatron-models/c-model/345m/ -t_g 1 -i_g 1
```

When I checked the directory of the weights, there are transformer layer weights, layer norm weights and `model.wpe.bin` and `model.wte.bin`, I was also expecting a `model.final_projection.bin` or `model.output_emeddding.bin`

**Comment by byshiue** [comment]
Since the embedding is shared, FT uses `model.wte.bin` directly. Please refer https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/gpt/GptWeight.cc#L133.

**Comment by bharatv007** [comment]
I see, thanks for pointint that out. Usually the final logit layer projection also has a bias variable to it. Are there any easy tips or steps to add this to final layer?

**Comment by byshiue** [comment]
You need to modify the op or backend, adding the bias into "weight class", and put the bias as an input of dynamic_decode layer. 
You can compare the `ParallelGpt.cc` source code and `Decoding.cc`. The latter one contains the bias.

**Comment by bharatv007** [comment]
Hey, I couldn't fint `ParallelGPT.cc` is this on `dev/v_5.0` branch and do you mean GPTJ?

**Comment by byshiue** [comment]
That is the model of GPT. Please find more models in `src/fastertransformer/models`.

**Comment by bharatv007** [comment]
Correct me if I am wrong
https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/decoding/Decoding.cc#L459
But there is no bias add after the final layer projection. There is a Cuda Kernel, InvokeBiasAdd, but I dont see it being used here

**Comment by bharatv007** [comment]
After adding the post decoder embedding bias weight to GPTWeight.cc, I added the invokeaddbias after the final projection layer.

```
invokeAddBias(logits_buf_,
gpt_weights->post_decoder_embedding.bias,
 batch_size * beam_width_,
vocab_size_padded_,
stream_);
```

But I get an error like this, its a bit hard to interpret what it is.
`[FT][ERROR] CUDA runtime error: an illegal memory access was encountered /workspace/FasterTransformer/src/fastertransformer/utils/memory_utils.cu:82`

**Comment by byshiue** [comment]
Please refer https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/decoding/Decoding.cc#L380 and https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/decoding/Decoding.cc#L477.

**Comment by bharatv007** [comment]
@byshiue Thanks for the quick response, that helps!

**Comment by byshiue** [comment]
Can you provide the environment, reproduce step for the problems you encounter?

**Comment by bharatv007** [comment]
Hi, I fixed this issue! on dev_5.0 branch the temperature penalty kernel does not work when bias is passed in fp16. Instead I use invokeAddBias and pass a null pointer to temeprature penalty kernel.
