### ISSUE TITLE
Passing sampling parameters at runtime

### ISSUE THREAD

**Issue by bilal2vec** [NVIDIA/FasterTransformer#188]
Hi, Looking at the state of the gpt decoding in the repo right now, it looks like it requires you to define the sampling hparams (top_k, top_p, next_n, etc) when creating the model itself, and those sampling parameters would apply to all elements in the batch.  It would be nice to be able to pass in sampling params in the `forward()` and to be able to specify those parameters on a per-element basis.

**Comment by byshiue** [comment]
Thanks for your suggestion. We will move these runtime parameters to forward function in next release.

**Comment by byshiue** [comment]
These features are supported in latest release.
