### ISSUE TITLE
gpu utilization 100%

### ISSUE THREAD

**Issue by 520jefferson** [NVIDIA/FasterTransformer#189]
Firstly, I compile FT4.0 , then i join the enc dec so library into tensorflow serverint 1.15 to compile,  but when i start the serving. and access by grpc, then the gpu utilization become 100%.
![image](https://user-images.githubusercontent.com/5691554/153379198-8de0e6b1-f18e-4d4e-87d7-c5f772b51fe3.png)

**Comment by byshiue** [comment]
Sorry. I don't understand your question.

**Comment by 520jefferson** [comment]
I mean, After i compile the  tensorflow serving with custom FT4.0  library libtf_decoding_beamsearch.so libtf_decoding_sampling.so libtf_fastertransformer.so. 
 Then i start the serving with batch decoding function and load FT4.0 optimized model , then the gpu utilization will suddenly increate to nearly 100%, then the service cannot be access.
I cannot figure out what's wrong.

**Comment by byshiue** [comment]
We don't test the TF serving although I heard some users use FT in TF serving successfully. 
You can try the nsight systems to log the process to check that do we run any FT kernel? Or Add some debug information into FT TF Ops.

**Comment by byshiue** [comment]
Do you use single thread?

**Comment by byshiue** [comment]
It may be some bugs of multi-thread. We don't test of multi-threads, and some private resources may be shared under multi-thread.

**Comment by Sunxxlo** [comment]
> I mean, After i compile the tensorflow serving with custom FT4.0 library libtf_decoding_beamsearch.so libtf_decoding_sampling.so libtf_fastertransformer.so. Then i start the serving with batch decoding function and load FT4.0 optimized model , then the gpu utilization will suddenly increate to nearly 100%, then the service cannot be access. I cannot figure out what's wrong.

Hi, @520jefferson 
I'm trying to build TF Serving with FasterTransformers, what I know as so far:
1. compile FasterTransformers to get 'libtf_fastertransformer.so' file

**Comment by Sunxxlo** [comment]
> I mean, After i compile the tensorflow serving with custom FT4.0 library libtf_decoding_beamsearch.so libtf_decoding_sampling.so libtf_fastertransformer.so.
> Then i start the serving with batch decoding function and load FT4.0 optimized model , then the gpu utilization will suddenly increate to nearly 100%, then the service cannot be access.
> I cannot figure out what's wrong.

Hi @520jefferson 

I'm trying to compile TF serving with FasterTransformers. As far as I know:

step 1: Build FasterTransformers to obtain the "libtf_xxx.so" file. (I tried this with FT v5.3 but got files named "libtf_bert.so" and others, not libtf_fastertransformer.so.)
step 2: Compile TF serving with the .so file obtained in step 1 to get custom ops.
step 3: Serve the saved_model using the compiled TF serving.

Did I miss anything? Do I need to retrain and export a new saved_model with FasterTransformers, or just train with the official bert repo?

I would really appreciate it if you could provide some   help, Thanks!
