### ISSUE TITLE
About gptj-triton guide

### ISSUE THREAD

**Issue by misska1** [NVIDIA/FasterTransformer#193]
https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/docs/gptj_guide.md

I can not access this respository https://gitlab-master.nvidia.com/bhsueh/fastertransformer_backend and the github version https://github.com/triton-inference-server/fastertransformer_backend don`t have the dev-gptj branch.

**Comment by 520jefferson** [comment]
Have you solve the problem?
can you use  FasterTransformer-dev-v5.0_beta_2021.11_tag/src/fastertransformer/triton_backend/gptj ?

**Comment by byshiue** [comment]
Sorry, this is a bug for document. Please refer the latest document in main branch.
