### ISSUE TITLE
Minor change needed in gpt_sample.py

### ISSUE THREAD

**Issue by FarzanMemarian** [NVIDIA/FasterTransformer#195]
If one follows the instructions under the **GPT Demo** section to run` python ./pytorch/gpt_sample.py`, they'll encounter a directory address error. To fix this, the file `/workspace/FasterTransformer/build/pytorch/gpt_sample.py` needs to be modified. In this file, wherever `../models` is written, it needs to be replaced with `./models`

**Comment by byshiue** [comment]
This problem is fixed in latest v5.0_beta branch.
