### ISSUE TITLE
Minor change needed in instructions

### ISSUE THREAD

**Issue by FarzanMemarian** [NVIDIA/FasterTransformer#196]
The instructions suggest to run `python ../sample/pytorch/utils/megatron_ckpt_convert.py -i ./models/megatron-models/345m/release/ -o ./models/megatron-models/c-model/345m/ -t_g 1 -i_g 1`, however, when running this, `head_num` is a required argument which the instructions do not mention. `head_num` determines the number of attention heads and it needs to be mentioned as a command line argument.

**Comment by byshiue** [comment]
This problem is fixed in latest v5.0_beta branch.
