### ISSUE TITLE
Minor change needed in instructions

### ISSUE THREAD

**Issue by FarzanMemarian** [NVIDIA/FasterTransformer#197]
The instructions for running GPT on PyTorch is to run `mpirun -n 8 --allow-run-as-root python ./pytorch/gpt_sample.py --tensor_para_size=8 --layer_para_size=1 --ckpt_path="/workspace/fastertransformer/models/megatron-models/c-model/345m/8-gpu"`, but `fastertransformer` should be written as `FasterTransformer` for it to work, since the repo name is `FasterTransformer`.

**Comment by byshiue** [comment]
This problem is fixed in latest v5.0_beta branch.
