### ISSUE TITLE
FusedMultiHeadAttention

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/FasterTransformer#200]
Thank you for open sourcing this great project. I am wondering how you generated these precompiled cubin's 
https://github.com/NVIDIA/FasterTransformer/tree/main/fastertransformer/trt_fused_multihead_attention

Are there any source code for them?

**Comment by jiajuns** [comment]
It comes directly from tensorRT plugin repo: https://github.com/NVIDIA/TensorRT/tree/master/plugin/bertQKVToContextPlugin/fused_multihead_attention_v2/src

**Comment by peisun1115** [comment]
Thank you.  Anyway to support more size_per_head (e.g. 16)?

**Comment by byshiue** [comment]
You can try it directly. From our testing, FT BERT can support size_per_head 16 although FT cannot use fused mha.

**Comment by peisun1115** [comment]
Thank you. I will try. I am interested in using it for another model (that doesn't need large size_per_head) instead of BERT. Do you expect smaller size_per_head to be integrated the fused version which I guess is much faster in the future releases? Any materials for me to read if I want to add support for it on my own if that makes sense at all?

**Comment by byshiue** [comment]
If you want to use the encoder fused mha, the cores is not open source and I cannot provide any suggestion.

**Comment by peisun1115** [comment]
I see. thanks for the information. It will be great if that will be open sourced sometime in the future :)
