### ISSUE TITLE
Request for documentation: FasterTransformer vs TensorRT

### ISSUE THREAD

**Issue by sam-writer** [NVIDIA/FasterTransformer#211]
Sorry if this is covered somewhere; I looked through the docs and issues and couldn't find it.

From what I can tell, FasterTransformer lets you run PT or TF transformer models, but by swapping out and optimizing low-level primitives, allows it to go much faster. NVIDIA also makes TensorRT, which is a different format, but has the same goal of speeding up transformer inference.

So my request is: can you explain in the docs if FT and TRT compete (or am I mistaken and both can be used), and if so, when to pick one or the other? If I have a PyTorch BERT model and I am going to serve it with Triton, when would I choose to use FT vs converting it to TRT?

Thank you!

**Comment by byshiue** [comment]
The goal of FT and TRT are different. TRT provides stable and automatically acceleration, while FT hopes to support latest model and feature in short time. Important features of FT will also be supported in TRT in the future, but it require longer time. 
So, no simple solution to reply which one is better. If users want to use some models which are supported well in TRT, then using TRT is better. Bert is an example here. 
On the other hand, if users want to use some models which are not supported in TRT or the optimization of TRT is still not good enough, then using FT is better in short time.

**Comment by sam-writer** [comment]
This is great information, and I really appreciate the prompt response. I'm happy to open a PR to the README with that information — I think it would help.

**Comment by dashesy** [comment]
One advantage of TensorRT is that it can be used as the Execution Provider for OnnxRuntime. If TRT could support FasterTransformer automatically ONNX would benefit from the optimizations.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
