### ISSUE TITLE
Would welford algorithm help accelerating the layer norm kernel?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/FasterTransformer#214]
Hello! I'm reading the layer norm implement of FasterTransformer. Some frameworks like pytorch use the Welford algorithm to compute mean and variance in one-pass. But it seems that FasterTransformer doesn't compute mean and variance in this way ( I'm a bit confused about it...). Would welford algorithm help accelerating the layer norm kernel?

**Comment by byshiue** [comment]
Thanks for your suggestion. We don't observe obvious performance difference from testing.
