### ISSUE TITLE
Help using cpp vit example for inference on images with trained .npz model

### ISSUE THREAD

**Issue by jwhg** [NVIDIA/FasterTransformer#217]
First of all thank you very much for all the hard work on making this project available. I have been trying to use the CPP example of the VIT transformer to load a trained model (npz file format). But like the TensorRT (Python) version I haven't been able to find any information on how to load a trained model.

Also I have been trying to expand the CPP example of the VIT transformer code to inference on images, without any success (especially on retrieving the inference results). By any chance is there anyone working on expanding the cpp example of the VIT transformer to do inference on images?

Any help is welcome~ Thanks in advance!

**Comment by byshiue** [comment]
You can found how to load model in `ViTPlugin.cpp`. We don't load the real model in cpp example because we don't have real input in cpp example.
We don't have work to run cpp end to end example.

**Comment by jwhg** [comment]
Thank you very much for the quick reply. Then by any chance could u also tell me how to parse the Output Tensor. So that I can receive the classification result from the cpp output tensor?

**Comment by byshiue** [comment]
You can get, print or store the output tensor of vit_example.cc directly

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
