### ISSUE TITLE
找不到你们的安装文档

### ISSUE THREAD

**Issue by p517332051** [NVIDIA/FasterTransformer#218]
我想使用你们的框架，但是找不到你们的编译文档。所以我自己编译出了好多难搞的问题。所以你们有安装文档吗？

**Comment by byshiue** [comment]
Please refer the guides in https://github.com/NVIDIA/FasterTransformer/tree/main/docs.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
