### ISSUE TITLE
ViT TensorRT INT8?

### ISSUE THREAD

**Issue by lingffff** [NVIDIA/FasterTransformer#222]
In Support matrix, it says:

Models | Framework | FP16 | INT8 (after Turing)
ViT        | TensorRT    | Yes    | Yes

However, I can't find INT8 support for ViT-TensorRT. 
Can you help me with it?

**Comment by byshiue** [comment]
Sorry, this is a miss. We don't provide ViT tensorrt plugin under INT8.

**Comment by lingffff** [comment]
> Sorry, this is a miss. We don't provide ViT tensorrt plugin under INT8.

OK, maybe you can update README.
