### ISSUE TITLE
Online service related

### ISSUE THREAD

**Issue by 520jefferson** [NVIDIA/FasterTransformer#223]
Now FT support TensorFlow, PyTorch and Triton backend. And the tensorflow and triton backend can support online inference with custom op and baching capability.
1,Tensorlfow custom op can be added into tf model server's compile to support ft model  online serving with batching capability 
2,Triton backend total have baching capability (T5, gpt)

Because i haven't find that the transformer（pytorch version) is supported by triton backed, if i have pytorch model, how should i support the online inference with batching and pytorch custom op?

**Comment by byshiue** [comment]
Sorry, but I think this is a issue or enhancement for pytorch. 
A possible solution is loading the pytorch model in triton backend. We have provide converter for some huggingface model. If you use different libraries or framework, you may need to implement a converter by referring the converter FT provides.

**Comment by 520jefferson** [comment]
Does the triton backend  support  transformer ?
![image](https://user-images.githubusercontent.com/5691554/168561636-75f860be-32a7-4192-afca-54f6f0e7e170.png)

**Comment by byshiue** [comment]
I am not sure the meaning of "Does the triton backend support transformer ?". The FT triton backend supports the models we list in the table.

**Comment by 520jefferson** [comment]
Is there any plan to support transformer ( encoder + decoding)  with FT triton backend?

**Comment by byshiue** [comment]
We will discuss and consider to support this feature.
