### ISSUE TITLE
T5 v1.1(mT5) support

### ISSUE THREAD

**Issue by wantsjean** [NVIDIA/FasterTransformer#225]
It seems that the current version only supports T5 v1.0 (shared word embedding version)，any plan to support T5 v1.1?

**Comment by byshiue** [comment]
If you mean mT5, it is on our roadmap. We plan to support it by integrated into Nemo Megatron.

**Comment by byshiue** [comment]
Not yet, it is planned in next release in Sep.

**Comment by byshiue** [comment]
mt5 is supported in latest release. You can refer https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md#running-mt5.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
