### ISSUE TITLE
Question: How to use bad_words_list and stop_word_list

### ISSUE THREAD

**Issue by shimoshida** [NVIDIA/FasterTransformer#227]
I do not understand how to use `bad_words_list` and `stop_word_list` even thought seeing sample scripts. 

```
        bad_words_list = np.concatenate([np.zeros([input_start_ids.shape[0], 1, 1]).astype(
            np.int32), (-1 * np.ones([input_start_ids.shape[0], 1, 1])).astype(np.int32)], axis=1)
        stop_word_list = np.concatenate([np.zeros([input_start_ids.shape[0], 1, 1]).astype(
            np.int32), (-1 * np.ones([input_start_ids.shape[0], 1, 1])).astype(np.int32)], axis=1)
```
https://github.com/triton-inference-server/fastertransformer_backend/blob/571a1fce438409087f5d3889237541828cc24ba5/tools/identity_test.py#L98

How to modify the above scripts to avoid outputting `......` whose token id is `357` for example?

**Comment by byshiue** [comment]
You can refer https://github.com/triton-inference-server/fastertransformer_backend/blob/571a1fce438409087f5d3889237541828cc24ba5/all_models/gptj/preprocessing/1/model.py#L106. 
The default demo "identity_test.py" does not use bad word and stop word (these settings disable them).
