### ISSUE TITLE
List of images with supported Pytorch versions

### ISSUE THREAD

**Issue by HamidShojanazeri** [NVIDIA/FasterTransformer#229]
I am looking into converting a Fariseq decoder model to FasterTransformer version which requires PT 1.10.1. I was wondering if there is a list of docker images with supported PT versions somewhere in the doc?

I was not able to located it and appreciate your help.

**Comment by byshiue** [comment]
The pytorch op of FasterTransformer is based on the custom op of pytorch. In general, you should be able run it when pytorch >= 1.5. 
For docker images with pytorch, you can try the nvcr.io/nvidia/pytorch:21.12 or newer version of docker.

**Comment by HamidShojanazeri** [comment]
Thanks @byshiue for clarification. I think it would be helpful for Pytorch users, if could have a section in main readme or Pytorch section to list the images/ link to ducker hub that provide more info on different containers.

**Comment by HamidShojanazeri** [comment]
one more question @byshiue, last time I tried the docker image, it was making a "libpyt_fastertransformer.so" file that I could add to my script for conversion. Now what I am getting is the screenshot below, so was wondering which is the right ".so" file now, it seems each model has a separate one now?

<img width="1258" alt="Screen Shot 2022-05-17 at 12 46 40 PM" src="https://user-images.githubusercontent.com/9162336/168917086-965eec9e-21f4-46a0-81ae-db1ed9df987d.png">

**Comment by byshiue** [comment]
> Thanks @byshiue for clarification. I think it would be helpful for Pytorch users, if we could have a section in main readme or Pytorch section to list the images/ link to ducker hub that provide more info on different containers.

We have provided the link (https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) of supported matrix in the document.

**Comment by byshiue** [comment]
> one more question @byshiue, last time I tried the docker image, it was making a "libpyt_fastertransformer.so" file that I could add to my script for conversion. Now what I am getting is the screenshot below, so was wondering which is the right ".so" file now, it seems each model has a separate one now?
> 
> <img alt="Screen Shot 2022-05-17 at 12 46 40 PM" width="1258" src="https://user-images.githubusercontent.com/9162336/168917086-965eec9e-21f4-46a0-81ae-db1ed9df987d.png">

You should choose the .so you need. Each model has each .so file.
