### ISSUE TITLE
Run and query a finetuned / custom T5 model in Triton Inference Server

### ISSUE THREAD

**Issue by Valterrsj** [NVIDIA/FasterTransformer#237]
Hi guys! I have two questions, can you help me?

1) It is possible to use triton inference server for a finetuned / custom T5 model with vocabulary with different size from the original (eg MODEL_VOC_SIZE = 32100). Do you have any guide or repository with example?

2) How do I send query to triton server with a  finetuned / customT5 model? Do you have any guide or repository with example?

**Comment by byshiue** [comment]
1. It is possible. When you convert the model successfully, the model configuration will be saved in a config file and the backend will read it, like [here](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/all_models/t5/fastertransformer/1/config.ini).
2. Please refer [triton t5 guide](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/t5_guide.md).

**Comment by Valterrsj** [comment]
@byshiue, thanks a lot for the quick response. I will check the mentioned guides in detail.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
