### ISSUE TITLE
Performance comparison with cudnnMultiHeadAttn

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/FasterTransformer#243]
Is there any comparison with cudnn's multi head attention? 

Thanks!

**Comment by byshiue** [comment]
No. Their motivation are different. FT's kernel only focus on inference, while cudnn also considers the training.

**Comment by peisun1115** [comment]
thanks. I understand the inference part. cudnn also has inference. [This paper's Table 2](https://proceedings.mlsys.org/paper/2021/file/c9e1074f5b3f9fc8ea15d152add07294-Paper.pdf) reported terrible performance on cudnn8.0.4. Hence i was wondering whether there is any benchmarks for that esp for latest versions.
