### ISSUE TITLE
Is allow_gemm_test flag effective in the BERT example? 

### ISSUE THREAD

**Issue by dontloo** [NVIDIA/FasterTransformer#255]
[bert_guide.md](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/bert_guide.md) section 1.1.2 mentioned this allow_gemm_test flag, but it seems this flag is not effective and not used in the bertExample method in [bert_example.cc](https://github.com/NVIDIA/FasterTransformer/blob/6fddeac5f59ce4df380002aa945da57a0c8e878c/examples/cpp/bert/bert_example.cc#L71).

Output shows "using default GEMM algo" with `allow_gemm_test=1`
```
root@e6efb0f86068:/workspace/FasterTransformer/build# ./bin/bert_example 32 12 32 12 64 0 0 1
[INFO] Device: Tesla T4 
[WARNING] gemm_config.in is not found; using default GEMM algo
[FT][INFO] batch_size 32 seq_len 32 layer 12 FT-CPP-time 42.36 ms (10 iterations)

**Comment by byshiue** [comment]
Hi, dontloo. Thank you for the feedback and sorry for the confusion. We have removed this feature but not update the document. We will fix it in the next update.

**Comment by byshiue** [comment]
> [bert_guide.md](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/bert_guide.md) section 1.1.2 mentioned this allow_gemm_test flag, but it seems this flag is not effective and not used in the bertExample method in [bert_example.cc](https://github.com/NVIDIA/FasterTransformer/blob/6fddeac5f59ce4df380002aa945da57a0c8e878c/examples/cpp/bert/bert_example.cc#L71).
> 
> Output shows "using default GEMM algo" with `allow_gemm_test=1`
> 
> ```
> root@e6efb0f86068:/workspace/FasterTransformer/build# ./bin/bert_example 32 12 32 12 64 0 0 1
> [INFO] Device: Tesla T4 
> [WARNING] gemm_config.in is not found; using default GEMM algo
> [FT][INFO] batch_size 32 seq_len 32 layer 12 FT-CPP-time 42.36 ms (10 iterations) 
> ```

This bug is fixed in latest release.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
