### ISSUE TITLE
mt5 support？

### ISSUE THREAD

**Issue by Elisewyh** [NVIDIA/FasterTransformer#256]
### Description

```shell
Is it possible to support mt5 acceleration by changing the activation function of mt5 to relu? Are there other things to pay attention to?
```

### Reproduced Steps

```shell
1、I changed the activation function of mt5 from gated-gelu to relu, 
2、then finetuned my model, the evaluation index did not drop, 
3、and then accelerated with FT, the generated results became worse，
4、I want to ask if there are other things I didn't notice.
```

**Comment by byshiue** [comment]
Please refer https://github.com/NVIDIA/FasterTransformer/issues/225.

**Comment by byshiue** [comment]
mt5 is supported in latest release. You can refer https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md#running-mt5.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
