### ISSUE TITLE
Should the package name be **ml_collections** instead of ml_collection in /examples/pytorch/requirement.txt ?

### ISSUE THREAD

**Issue by dontloo** [NVIDIA/FasterTransformer#259]
the second last package name in [/examples/pytorch/requirement.txt ](https://github.com/NVIDIA/FasterTransformer/blob/6fddeac5f59ce4df380002aa945da57a0c8e878c/examples/pytorch/requirement.txt), should it be **ml_collections** instead of ml_collection? 

Pip says "No matching distribution found for ml_collection" on my machine.

**Comment by byshiue** [comment]
Hi, dontloo. Thank you for the feedback. Yes, it should be `ml_collections`.
