### ISSUE TITLE
BLEU for machine translation v4.0 vs v5.0

### ISSUE THREAD

**Issue by dongdaoking** [NVIDIA/FasterTransformer#262]
I get a question.

For version 4.0, FasterTransformer can't support len_penalty and FasterTransformer v5.0 can change the value of len_penalty.
But when setting the len_penalty as "1.0", v4.0 and v5.0 can achieve consistent quality.
why? In theory, v4.0 and v5.0 get same quality only when the len_penalty is 0.0.

**Comment by byshiue** [comment]
Only beam search support length penalty now. Sampling is not supported, yet.
Besides, there are some issues for the length penalty now. It is not applied correctly.

**Comment by dongdaoking** [comment]
OK. Thanks.
