### ISSUE TITLE
Sharding Input Embeddings

### ISSUE THREAD

**Issue by bharatv007** [NVIDIA/FasterTransformer#264]
Currently when we use tensor parallel sharding for GPT, we do not shard the input embeddings. If we split the embeddings into different devices based on tensor parallel degree, we can save memory on each device and then applying an all gather step after. Is there a reason why this approach wasn't considered?

**Comment by byshiue** [comment]
Because this embedding is not very large, and it costs is not really high. Split them into different devices mean that we need a all-gather operation, which introduce additional communication overhead for latency.

**Comment by bharatv007** [comment]
yeah I understand, we need to do all gather, but in GPT3 like models, the embedding matrices are pretty large (not as large as the layers), so it will still save some memory on device and the all gather should be insginificant compared to the time taken on transformer layers. So wondering if there have been any analysis done on this trade off in terms of throughput and latency for really large models.

**Comment by byshiue** [comment]
We don't do estimation. However, the embedding table size is 12288*51200*2 = 1GB, which is much smaller than the transformer block. 
On the other hand, in the embedding lookup, we only gather batch_size * 12288 elements, which is also small.

**Comment by bharatv007** [comment]
Thanks!
