### ISSUE TITLE
Wrong latency data in BertPerformance

### ISSUE THREAD

**Issue by luoyu-intel** [NVIDIA/FasterTransformer#276]
### Description

```shell
There are two tables in docs/bert_guide.md:
Performance on FP16 sparsity, and Performance on INT8-v2 sparsity. 
They have the same data of FT Dense (ms), FT Sparse (ms), Dense EFF (ms), and Sparse EFF (ms). 
I don't think this is the right case.
```

### Reproduced Steps

```shell
just check the data
```

**Comment by byshiue** [comment]
Hi, @luoyu-intel. Thank you for the nice catch. We only update the speedup number but not update the latency number.

The performance of int8-v2 sparsity should be 
| <batch_size, seq_len> | FT Dense (ms) | FT Sparse (ms) | Dense EFF (ms) | Sparse EFF (ms) | FT Sparse Speedup | EFF Sparse Speedup |
| :-------------------: | :-----------: | :------------: | :------------: | :-------------: | :---------------: | :----------------: |
|        <1, 32>        |     1.32      |      1.58      |      1.35      |      1.62       |       0.84        |        0.83        |
|       <1, 128>        |     1.37      |      1.59      |      1.37      |      1.61       |       0.86        |        0.85        |
|       <1, 384>        |     1.52      |      1.60      |      1.40      |      1.62       |       0.95        |        0.86        |
|        <8, 32>        |     1.39      |      1.61      |      1.39      |      1.63       |       0.86        |        0.85        |
|       <8, 128>        |     1.70      |      1.62      |      1.61      |      1.63       |       1.05        |        0.99        |
|       <8, 384>        |     3.38      |      2.78      |      2.10      |      1.89       |       1.22        |        1.11        |
|       <32, 32>        |     1.70      |      1.63      |      1.50      |      1.65       |       1.04        |        0.91        |
|       <32, 128>       |     3.62      |      2.94      |      2.28      |      2.04       |       1.23        |        1.12        |
|       <32, 384>       |     10.10     |      8.60      |      5.77      |      5.38       |       1.17        |        1.07        |

We have fixed this issue now, please check again.
