### ISSUE TITLE
Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Bingo851** [NVIDIA/FasterTransformer#285]
I try to repro the swin-t tensorrt engine build, but get a problem as below,

```
(base) root@96a8e43b1bd4:/home/tac/FasterTransformer/examples/tensorrt/swin# sh run_builder_fp16.sh 
Traceback (most recent call last):
  File "builder_fp16.py", line 77, in <module>
    handle = ctypes.CDLL("../../../build/lib/libswinTransformer_plugin.so", mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../../../build/lib/libswinTransformer_plugin.so: cannot open shared object file: No such file or directory
```

and in the `run_builder_fp16.sh ` , there is an option `   --th-path ../../../build/lib/libpyt_swintransformer.so \` and this lib is also can not find. 

Can you help about this ?

**Comment by byshiue** [comment]
Have you built the project by following [Setup](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/longformer_guide.md#setup)?

**Comment by Bingo851** [comment]
ok, I got it, Thanks
