### ISSUE TITLE
CUDA runtime error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by cdj0311** [NVIDIA/FasterTransformer#287]
Hi, 
  I encountered a problem when run megatron model with gpt_example.py, the script is:

python gpt_example.py \
    --layer_num 24 \
    --output_len 32 \
    --head_num 16 \
    --size_per_head 64 \
    --vocab_size 50304 \
    --beam_width 3 \
    --ckpt_path ../models/megatron-models/c-model/345m/1-gpu \
    --lib_path ./build/lib/libth_gpt.so \
    --vocab_file ../models/gpt2-vocab.json \
    --merges_file ../models/gpt2-merges.txt \
    --start_id 50256 \
    --end_id 50256 \
    --max_batch_size 4 \
    --max_seq_len 1024 \
    --sample_input_file sample_input.txt \
    --sample_output_file sample_output.txt

**Environment:**
cuda: 11.1
driver: 470.42.01 
cudnn: 8.2
pytorch: 1.8+cu111

**The problem:**

layer_num: 24
output_len: 4
head_num: 16
size_per_head: 64
vocab_size: 50304
beam_width: 1
top_k: 1
top_p: 0.0
temperature: 1.0
len_penalty: 0.0
beam_search_diversity_rate: 0.0
tensor_para_size: 1
pipeline_para_size: 1
ckpt_path: ../models/megatron-models/c-model/345m/1-gpu
lib_path: ./build/lib/libth_gpt.so
vocab_file: ../models/gpt2-vocab.json
merges_file: ../models/gpt2-merges.txt
start_id: 50256
end_id: 50256
max_batch_size: 1
repetition_penalty: 1.0
max_seq_len: 1024
data_type: fp32
time: False
sample_input_file: sample_input.txt
sample_output_file: sample_output.txt
enable_random_seed: False
sparse: False
weights_data_type: fp32
return_cum_log_probs: 0

[INFO] batch size: 1
[INFO] WARNING: Have initialized the process group
[FT][ERROR] CUDA runtime error: CUBLAS_STATUS_EXECUTION_FAILED /home/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc:296 

**I use "cuda-memcheck" check CUDA, get an error:**

[INFO] batch size: 1
[INFO] WARNING: Have initialized the process group
Internal Memcheck Error: Initialization failed
    Saved host backtrace up to driver entry point at error
    Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x24a63b]
.......
[FT][ERROR] CUDA runtime error: CUBLAS_STATUS_EXECUTION_FAILED /home/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc:296 
ERROR SUMMARY: 1 error 

**gemm_config.ini is:**
batch_size, seq_len, head_num, size_per_head dataType ### batchCount, n, m, k, algoId, customOption, tile, numSplitsK, swizzle, reductionScheme, workspaceSize, stages, exec_time
3 32 16 64 1 ### 1 3072 96 1024 30 0 18 1 0 0 0 0 0.033985
3 32 16 64 1 ### 48 32 32 64 103 -1 -1 -1 -1 -1 -1 -1 0.006710
3 32 16 64 1 ### 48 64 32 32 105 -1 -1 -1 -1 -1 -1 -1 0.005660
3 32 16 64 1 ### 1 1024 96 1024 5 0 21 5 0 4 983040 7 0.015219
3 32 16 64 1 ### 1 1024 96 1024 5 0 21 5 0 4 983040 7 0.015254
3 32 16 64 1 ### 1 1024 96 1024 5 0 21 5 0 4 983040 7 0.015195
3 1 16 64 1 ### 1 3072 3 1024 108 -1 -1 -1 -1 -1 -1 -1 0.014220
3 1 16 64 1 ### 1 1024 3 1024 21 0 5 1 0 0 0 20 0.006821
3 1 16 64 1 ### 1 1024 3 1024 21 0 5 1 0 0 0 20 0.006825
3 1 16 64 1 ### 1 1024 3 1024 21 0 5 1 0 0 0 20 0.006840
3 1 16 64 1 ### 1 50048 3 1024 100 -1 -1 -1 -1 -1 -1 -1 0.190770

**Comment by byshiue** [comment]
I think this is an issue for environment settings. 

Do you use the docker image we recommend in the document? If not, can you try running in docker first?

**Comment by cdj0311** [comment]
Install mpi and solved it.
