### ISSUE TITLE
Beam search result

### ISSUE THREAD

**Issue by jellysnack** [NVIDIA/FasterTransformer#300]
Hi! 
Is it true that with beam search decoding the most likely answer will always be in the first row of the tokens tensor, or is it necessary to take cum_log_probs, find the row with the highest probability, and extract the answer from the corresponding row of the tokens tensor?

**Comment by jellysnack** [comment]
Suppose we are decoding with batch_size=1 and beam_size=2. As a result, we got a tensor of the shape [1, 2, max_seq_len] with two sequences. My question is about the position of the most probable sequence in this tensor. Will the tensor always be sorted with the most probable sequence in the first row? Or should I find the row with the highest probability value in the cum_log_probs tensor and then select the sequence from the corresponding row of the resulting tensor?

**Comment by byshiue** [comment]
The tensor is always sorted.
