### ISSUE TITLE
pretrained-SwinTransformer doesn't pass the output difference check

### ISSUE THREAD

**Issue by cpm0722** [NVIDIA/FasterTransformer#301]
## Problem Description
 Hello. I try to apply FasterTransformer to Swin-Transformer.
 When I follow [tutorial](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/swin_guide.md#run-with-pytorch-op), it works well. But it doesn't works well with pretrained model Swin-Transformer model weight.
 In tutorial, `swin_tiny_patch4_window7_224` model is selected. I tried to apply many Swin-Transformer model in [official SwinTransformer repo](https://github.com/microsoft/Swin-transformer). In my case, when I use `swin_base_patch4_window7_224` model and apply `swin_base_patch4_window7_224.pth` weight, it works well. But when I use a pretrained(imagenet22k) weight (`swin_base_patch4_window7_224_22k.pth`), It's output diff is exceed to threshold value(FP32: 0.001, FP16: 0.001, BF16: 0.003). It doesn't make sense because they use exactly same model, and the only diffrence between them is the parameter's weight.

## reproduce
I added the code `model.head = torch.nn.Identity()` to `infer_swintransformer_op.py`.

* GPU: A100 80GB
* CUDA: 11.4
* python: Python 3.8.12
* pytorch: 1.10.0a0+0aef44c

### `swin_base_patch4_window7_224`
* command
    ```bash
    wget https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window7_224.pth
    python infer_swintransformer_op.py \
        --eval \
        --data-path /workspace \
        --cfg Swin-Transformer-Quantization/SwinTransformer/configs/swin_base_patch4_window7_224.yaml \
        --resume swin_base_patch4_window7_224.pth \
        --th-path ../../../build/lib/libpyt_swintransformer.so \
        --batch-size 32
    ```
* result
    ```
    => merge config from Swin-Transformer-Quantization/SwinTransformer/configs/swin_base_patch4_window7_224.yaml
    [WARNING] gemm_config.in is not found; using default GEMM algo
    FP32 op time :  78.93490791320801 ms
    FP32 torch trace time :  47.1761155128479 ms
    FP32 torch time :  47.21857786178589 ms
    [WARNING] gemm_config.in is not found; using default GEMM algo
    FP16 op time :  10.140132904052734 ms
    FP16 torch trace time :  31.79196834564209 ms
    FP16 torch time :  32.128446102142334 ms
    [WARNING] gemm_config.in is not found; using default GEMM algo
    BF16 op time :  15.144646167755127 ms
    BF16 torch trace time :  33.18215847015381 ms
    BF16 torch time :  33.73210668563843 ms
    FP32_torch_traced_output vs FP32_op_output , avg diff :  0.00077520445 max diff :  0.006266892
    FP16_torch_traced_output vs FP16_op_output , avg diff :  0.00050622656 max diff :  0.0034179688
    BF16_torch_traced_output vs BF16_op_output , avg diff :  0.0017746952 max diff :  0.009765625
    [INFO] SWIN Op TEST PASS !
    ```
### `swin_base_patch4_window7_224` (pretrained to imagenet22k)
* command
    ```bash
    wget https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window7_224_22k.pth
    python infer_swintransformer_op.py \
        --eval \
        --data-path /workspace \
        --cfg Swin-Transformer-Quantization/SwinTransformer/configs/swin_base_patch4_window7_224_22k.yaml \
        --resume swin_base_patch4_window7_224_22k.pth \
        --th-path ../../../build/lib/libpyt_swintransformer.so \
        --batch-size 32
    ```
* result
    ```
    => merge config from Swin-Transformer-Quantization/SwinTransformer/configs/swin_base_patch4_window7_224_22k.yaml
    [WARNING] gemm_config.in is not found; using default GEMM algo
    FP32 op time :  78.98651599884033 ms
    FP32 torch trace time :  47.215163707733154 ms
    FP32 torch time :  47.247796058654785 ms
    [WARNING] gemm_config.in is not found; using default GEMM algo
    FP16 op time :  10.17827033996582 ms
    FP16 torch trace time :  31.782407760620114 ms
    FP16 torch time :  32.15790510177612 ms
    [WARNING] gemm_config.in is not found; using default GEMM algo
    BF16 op time :  15.167841911315918 ms
    BF16 torch trace time :  33.23885679244995 ms
    BF16 torch time :  33.78366470336914 ms
    FP32_torch_traced_output vs FP32_op_output , avg diff :  0.0013119188 max diff :  0.0072986633
    Traceback (most recent call last):
      File "infer_swintransformer_op.py", line 228, in <module>
        main(args, config)
      File "infer_swintransformer_op.py", line 87, in main
        validate_with_random_data(args, config, model)
      File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
        return func(*args, **kwargs)
      File "infer_swintransformer_op.py", line 209, in validate_with_random_data
        assert diff.mean() < 0.001, "[ERROR] SWIN FP32 Op TEST FAIL !"
    AssertionError: [ERROR] SWIN FP32 Op TEST FAIL !
    ```

**Comment by byshiue** [comment]
> FP32_torch_traced_output vs FP32_op_output , avg diff :  0.0013119188 max diff :  0.0072986633
Traceback (most recent call last):
  File "infer_swintransformer_op.py", line 228, in <module>
    main(args, config)
  File "infer_swintransformer_op.py", line 87, in main
    validate_with_random_data(args, config, model)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "infer_swintransformer_op.py", line 209, in validate_with_random_data
    assert diff.mean() < 0.001, "[ERROR] SWIN FP32 Op TEST FAIL !"
AssertionError: [ERROR] SWIN FP32 Op TEST FAIL !

Such difference makes sense. Different model and input have different threshold. We only make sure they are on same level, but not same values.

**Comment by cpm0722** [comment]
Thank you for your quick reply. But I still have a few question.
1. How can I get a proper threshold values for my pretrained-model?
2. If there is no way to get threshold values, how can I check if my model has been properly converted?
    I think my pretrained-model is not properly converted because avg diff is too large in FP16 and BF16.
    ```
    FP32_torch_traced_output vs FP32_op_output , avg diff :  0.0028308618 max diff :  0.026235402
    FP16_torch_traced_output vs FP16_op_output , avg diff :  0.20213783 max diff :  1.9990234
    BF16_torch_traced_output vs BF16_op_output , avg diff :  0.53565735 max diff :  3.3496094
    ```
4. I applied FasterTransformer to my pretrained-ViT model which worked very well(output difference is very very small). Why does this problem situation occur in Swin-Transformer and not in ViT?

**Comment by byshiue** [comment]
> I think my pretrained-model is not properly converted because avg diff is too large in FP16 and BF16.
What's the absolute values for your output? For example, the output may be like 1000.123. In such cases, the difference around 0.2 is reasonable.

**Comment by cpm0722** [comment]
### FP32
<details>
<summary> torch_traced_output </summary>
<div markdown="1">

```python
[[ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]
 [ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]
 [ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]
 ...
 [ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]
 [ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]
 [ 0.27292982 -0.8217072  -0.65891767 ...  0.1056321  -0.07595748
  -0.29556143]]
```

</div>
</details>
<details>
<summary> op_output </summary>
<div markdown="1">

```python
[[ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]
 [ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]
 [ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]
 ...
 [ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]
 [ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]
 [ 0.27261376 -0.82405376 -0.6581842  ...  0.10523997 -0.07864143
  -0.2926416 ]]
```


</div>
</details>

* diff
    ```python
    FP32_torch_traced_output vs FP32_op_output , avg diff :  0.0028308618 max diff :  0.026235402
    ```

### FP16
<details>
<summary> torch_traced_output </summary>
<div markdown="1">

```python
[[ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]
 [ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]
 [ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]
 ...
 [ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]
 [ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]
 [ 0.27319336 -0.8222656  -0.6616211  ...  0.10491943 -0.07525635
  -0.2956543 ]]
```

</div>
</details>
<details>
<summary> op_output </summary>
<div markdown="1">

```python
[[ 0.13305664 -0.4736328  -0.22070312 ... -0.0980835   0.04214478
   0.00974274]
 [ 0.13500977 -0.47460938 -0.22314453 ... -0.09973145  0.05279541
   0.00564957]
 [ 0.13342285 -0.47338867 -0.21960449 ... -0.09790039  0.04272461
   0.01021576]
 ...
 [ 0.13500977 -0.47460938 -0.22314453 ... -0.09973145  0.05276489
   0.00567627]
 [ 0.13342285 -0.47338867 -0.21960449 ... -0.09790039  0.04269409
   0.01022339]
 [ 0.13464355 -0.47436523 -0.22290039 ... -0.09967041  0.05297852
   0.00617599]]
```

</div>
</details>

* diff
```python
FP16_torch_traced_output vs FP16_op_output , avg diff :  0.20213783 max diff :  1.9990234
```

### BF16
<details>
<summary> torch_traced_output </summary>
<div markdown="1">

```python
[[ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]
 [ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]
 [ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]
 ...
 [ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]
 [ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]
 [ 0.27148438 -0.8203125  -0.66796875 ...  0.10400391 -0.07470703
  -0.28515625]]
```

</div>
</details>
<details>
<summary> op_output </summary>
<div markdown="1">

```python
[[-0.17089844 -0.21777344 -1.         ... -1.3203125   0.27734375
  -0.00564575]
 [-0.06445312 -0.06005859 -0.78515625 ... -0.98828125  0.04345703
  -0.11572266]
 [-0.171875   -0.21875    -1.         ... -1.3203125   0.27734375
  -0.00622559]
 ...
 [-0.06542969 -0.06054688 -0.78515625 ... -0.98828125  0.04321289
  -0.11669922]
 [-0.171875   -0.21875    -1.         ... -1.3203125   0.27734375
  -0.00665283]
 [-0.06494141 -0.06005859 -0.78515625 ... -0.98828125  0.04345703
  -0.11621094]]
```

</div>
</details>

* diff
```python
BF16_torch_traced_output vs BF16_op_output , avg diff :  0.53565735 max diff :  3.3496094
```

**Comment by byshiue** [comment]
So, there are some issues in FP16/BF16 op. Can you reproduce such problem on public model weight?

**Comment by cpm0722** [comment]
I tested with `swin_large_patch4_window12_384_22k`.
config file: `https://github.com/microsoft/Swin-Transformer/blob/main/configs/swin/swin_large_patch4_window12_384_22kto1k_finetune.yaml`
weight file: `https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth`

**Comment by byshiue** [comment]
> I tested with `swin_large_patch4_window12_384_22k`. config file: `https://github.com/microsoft/Swin-Transformer/blob/main/configs/swin/swin_large_patch4_window12_384_22kto1k_finetune.yaml` weight file: `https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth`

Thank you for the reply. This is a bug, and we have fix it in latest main branch. Please try again.

**Comment by cpm0722** [comment]
Thank you for your quick update. I've checked that it's working well.
