### ISSUE TITLE
(GPT-J) (Prompts Learning) - How to transpose the prefix prompt weights?

### ISSUE THREAD

**Issue by ott-fogliata** [NVIDIA/FasterTransformer#308]
Hi all,
I'm using GPT-J model and I just start to explore the soft prompts tuning on it.
FY, to experiment with it I'm following the idea behind this repo https://github.com/exelents/soft-prompt-tuning 
 
I'm looking for an easy way to **transpose the prefix prompt weights to the required shape**, as written in the official documentation [here](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gptj_guide.md)

`[num_layers, 2, num_heads, perfix_seq_len, size_per_head]`

Is there any script or example that you already used for soft prompts tuning and to convert the weights in the desired shape?

Thanks for your help

**Comment by byshiue** [comment]
No. We don't have a public model to demonstrate how to use soft-prompt-tuning in FT. 

For model converting, we use python to convert and reshape/transpose them directly. You can post the shape of your prompt weight and we may be able to provide some ideas.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
