### ISSUE TITLE
Avoid n-gram repeat using FT T5 Decoding

### ISSUE THREAD

**Issue by michaelroyzen** [NVIDIA/FasterTransformer#309]
Huggingface's beam search implementation has a feature called `no_repeat_ngram_size`, which specifies the largest n-gram that should not be repeated (usually `no_repeat_ngram_size=3`). Is there any way to replicate this in FT T5 Decoding? I see a lot of 3-gram repetition with FT even with `repetition_penalty=1`.

Thanks.

**Comment by byshiue** [comment]
> Huggingface's beam search implementation has a feature called `no_repeat_ngram_size`, which specifies the largest n-gram that should not be repeated (usually `no_repeat_ngram_size=3`). Is there any way to replicate this in FT T5 Decoding? I see a lot of 3-gram repetition with FT even with `repetition_penalty=1`.
> 
> Thanks.

Hi, @michaelroyzen . FT does not support `no_repeat_ngram_size` feature now.

**Comment by michaelroyzen** [comment]
Thank you, @byshiue. I think the repeition_penalty might achieve something similar, but unfortunately it appears to be broken for beam search where beam_width > 1. I've made a separate issue: https://github.com/NVIDIA/FasterTransformer/issues/310.

**Comment by songkq** [comment]
@michaelroyzen @byshiue Hi, when I run gpt/mt0 inference through a topk and topp sampling with `repetition_penalty=2`, the model always generates shorter text content comparing to that without using `repetition_penalty`.  Does this make sense? Could you please give some advice about the value range of repetition_penalty?
