### ISSUE TITLE
repetition_penalty broken when beam width > 1

### ISSUE THREAD

**Issue by michaelroyzen** [NVIDIA/FasterTransformer#310]
### Description

```shell
Master branch, Docker container is pytorch:22.07, GPU is A100-80GB.
```

### Reproduced Steps

```shell
1. Follow the steps here to clone and compile FasterTransformer for T5: https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md.
2. Run the summarization example with t5v1.1, replacing beam_width=1 with beam_width>1 and repetition_penalty != 1.0 (e.g. beam_width = 2, repetition_penalty=0.7) in the summarize_ft function: https://github.com/NVIDIA/FasterTransformer/blob/565ef23bef2573fa3c9a99db58c2a36f5f78fefb/examples/pytorch/t5/summarization.py#L224.
3. CUDA illegal memory access.

Interestingly, repetition_penalty works when beam_width=1.
```

**Comment by michaelroyzen** [comment]
> [FT][DEBUG] std::string fastertransformer::IAllocator::getAddress(void*) const              
[FT][DEBUG] fastertransformer::cublasMMWrapper::~cublasMMWrapper()                          
[FT][DEBUG] virtual void fastertransformer::Allocator<fastertransformer::AllocatorType::TH>$
:free(void**) const                                                                         
[FT][DEBUG] std::string fastertransformer::IAllocator::getAddress(void*) const              
[FT][DEBUG] virtual fastertransformer::Allocator<fastertransformer::AllocatorType::TH>::~Al$
ocator()                                                                                    
Traceback (most recent call last):                                                          
  File "../examples/pytorch/t5/summarization.py", line 378, in <module>                     
    main()                                                                                  
  File "../examples/pytorch/t5/summarization.py", line 283, in main                         
    summary_ft, _ = summarize_ft(datapoint)                                                 
  File "../examples/pytorch/t5/summarization.py", line 235, in summarize_ft
    output, ft_output_len = ft_t5(line_tokens,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _c
all_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/t5/uti
ls/ft_decoding.py", line 355, in forward
    results = self.decoding.forward(beam_size,  # optional, can be None
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/t5/uti
ls/ft_decoding.py", line 329, in forward
    results = self.decoding.forward(beam_width, max_seq_len,
RuntimeError: [FT][ERROR] CUDA runtime error: an illegal memory access was encountered /home
/michael/FasterTransformer/src/fastertransformer/layers/beam_search_layers/BaseBeamSearchLay
er.cu:234

[FT][DEBUG] torch_ext::FTT5Encoder<T>::~FTT5Encoder() [with T = __nv_bfloat16]
[FT][DEBUG] T5EncoderWeight ~T5EncoderWeight start
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight start
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight end
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight start
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight end
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight start
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight end
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight start
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight end
[FT][DEBUG] T5EncoderLayerWeight ~T5EncoderLayerWeight start`

**Comment by byshiue** [comment]
Hi, @michaelroyzen. Thank you for the feedback.
We have tried to fix this issue in branch https://github.com/NVIDIA/FasterTransformer/tree/fix/t5-beamsearch-repetition-penalty, can you try again on this branch?

**Comment by michaelroyzen** [comment]
Yes, it appears to work now. Thanks.
