### ISSUE TITLE
GPT model with fp16, the result when batch input is very different from single input

### ISSUE THREAD

**Issue by kevinlee819** [NVIDIA/FasterTransformer#312]
### Description

```shell
GPT model with fp16, the result when batch input is very different from single input
FT version: v5.1;
model: CPM https://huggingface.co/TsinghuaAI/CPM-Generate
docker:  nvcr.io/nvidia/pytorch:22.07-py3
device: rtx 3090
```

### Reproduced Steps

```shell
input : ['1','1','I love you']
ouput : [' 研究目的\n1.1.2 研究意义<eod>题目:基于FPGA的卷积神经网络加速器的设计与实现\n关键词:FPGA;卷积;神经</s></s></s></s></s></s>', ' 研究目的\n1.1.2 研究意义<eod>题目:基于FPGA的卷积神经网络加速器的设计与实现\n关键词:FPGA;卷积;神经</s></s></s></s></s></s>', '\n4.3.2 “<unk>”的语义分析\n4.3.3 “<unk>”与“<unk>”的比较\n\n题目:现代汉语“']

but 
input: ['I love you']
output: ['\n4.2.2 I hope you can be a better man\n\n题目:基于语料库的留学生“连']

It looks quite different
params:{
    "output_len": 50,
    "beam_width": 1,
    "top_k": 1,
    "top_p": 0.9,
    "temperature": 1.0,
    "len_penalty": 0,
    "beam_search_diversity_rate": 0.0,
    "repetition_penalty": 1.1,
    "enable_random_seed": False,
    "max_batch_size": 32
  }
```

**Comment by byshiue** [comment]
Hi, @kevinlee819. This is a known behavior. The reason is because cublas chooses different GEMM kernel for different input shape.

We don't have idea to solve this issue now, but it does not affect the quality.

**Comment by kevinlee819** [comment]
But I changed the order and the result has changed, they should be the same shape

**Comment by kevinlee819** [comment]
Hi, @byshiue Let me try to describe this problem more clearly.

First, When the input is:

input : ["1","1",a]

output: [' 系统的功能需求分析\n3.2.2 系统的性能需求分析', ' 系统的功能需求分析\n3.2.2 系统的性能需求分析', '\n第3章 :《边城》中的意象\n3.2 《边城》中的意象\n中图分类:I207.2;TP391.1']

a = "生命从来不曾离开过孤独而独立存在。无论是我们出生、我们成长、我们相爱还是我们成功失败，直到最后的最后，孤独犹如影子一样存在于生命一隅，唯孤独永恒"

However, when I make the input look like this:

input : ["1","2",a]

output: [' 系统的功能需求分析\n3.2.2 系统的性能需求分析', ' 系统功能模块设计', '\n第3章 《孤独》中的孤独主题分析\n3.2 《孤独》中孤独主题的表现形式\n中图分类:I207.2;TP391.41']

I have only made little changes to the data. Two inputs should be the same shape. But the results have changed a lot. These two outputs seem to make sense here , but there are times when the output doesn’t make sense. This confuses me.

**Comment by byshiue** [comment]
What are the meaning of `["1", "1", a]` and `["1", "2", a]? 
Do you use same random seed, topk and topp values?

**Comment by byshiue** [comment]
What are the meaning of `["1", "1", a]` and `["1", "2", a]`?
Can you help reproduce by public model? 

I try megatron 345m model at https://api.ngc.nvidia.com/v2/models/nvidia/megatron_lm_345m/versions/v0.0/zip, running with input ids `[[198], [818]]` and `[[818], [198]]`, with topk 1, topp 0. The results are

```
818 262 1613 11 262 1230 468 587 18416 284 787 262 2458 11 33188 326 340 561 307 1775 355 257 2372 284 262 1499 338 2324 13 198 198 464 1230 
198 198 464 717 640 314 2497 262 3807 373 287 262 13766 13 314 373 287 262 3504 286 257 3807 290 314 373 4964 262 3807 290 314 373 588 11 
```

and

```
198 198 464 717 640 314 2497 262 3807 373 287 262 13766 13 314 373 287 262 3504 286 257 3807 290 314 373 4964 262 3807 290 314 373 588 11 
818 262 1613 11 262 1230 468 587 18416 284 787 262 2458 11 33188 326 340 561 307 1775 355 257 2372 284 262 1499 338 2324 13 198 198 464 1230 
```

respectively.

**Comment by kevinlee819** [comment]
Here are two examples：

example1:

input:
[
    "1",
    "1",
    "The capital of USA is",
]

start_ids(after padding):
tensor([[   16, 50256, 50256, 50256, 50256],
        [   16, 50256, 50256, 50256, 50256],
        [  464,  3139,   286,  4916,   318]], dtype=torch.int32)

data shape is [3, 5]

start_lengths:
tensor([1, 1, 5], dtype=torch.int32)

output:
[
    '.5 million in the first quarter of 2012,<|endoftext|><|endoftext|><|endoftext|><|endoftext|>', 
    '.5 million in the first quarter of 2012,<|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
    ' USA.\n\n"I\'m not sure what'
 ]

--------divider--------
example2:

input:
[
    "1",
    "The capital of USA is",
    "1",
]

start_ids(after padding):
tensor([[   16, 50256, 50256, 50256, 50256],
        [  464,  3139,   286,  4916,   318],
        [   16, 50256, 50256, 50256, 50256]], dtype=torch.int32)

data shape is [3, 5]

start_lengths:
tensor([1, 5, 1], dtype=torch.int32)

output:
[
    '.5 million in the first quarter of 2012,<|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
    ' the largest city in the world, with a population', 
    '.5 million in the first quarter of 2012,<|endoftext|><|endoftext|><|endoftext|><|endoftext|>'
]


The input of example 1 and the input of example 2 only change the position between the data, but their output is very different, data shape are the same.

The model is megatron 345m model.
input params are both 
{
    "output_len": 10,
    "beam_width": 1,
    "top_k": 1,
    "top_p": 0.,
    "temperature": 1.0,
    "len_penalty": 0,
    "beam_search_diversity_rate": 0.0,
    "repetition_penalty": 1.1,
    "enable_random_seed": False,
    "max_batch_size": 32
  }

**Comment by byshiue** [comment]
Hi. Thank you for the feedback and example. This helps us reproduce the problem. 

This is a bug caused by shared context optimization. We have tried to fix it in branch `fix/attn_mask_with_shared_context`. Can you try it?

**Comment by kevinlee819** [comment]
Branch `fix/attn_mask_with_shared_context` works. Problem solved, thx

**Comment by changleilei** [comment]
你好 @kevinlee819， 想知道你是用的哪个脚本将 CPM hg 模型或者 megatron 模型转换成 fastertransformer 模型的吗？我使用的转换后启动 Triton 的时候会报  what():  [FT][ERROR] Assertion fail: /workspace/fastertransformer_backend/build/_deps/repo-ft-src/src/fastertransformer/layers/attention_layers/DecoderSelfAttentionLayer.cc:202 的错误。可以分享一下 config.pbtxt 文件吗
