### ISSUE TITLE
 masked_multihead_attention_kernel  of size_per_head is 32  is faster than masked_multihead_attention_kernel  of size_per_head is 64

### ISSUE THREAD

**Issue by p517332051** [NVIDIA/FasterTransformer#313]
### Description

```shell
gpt2 and size_per_head*head==1024,  input token num is 1792 output token num is 2048
layer.  size_per_head is 32.    size_per_head is 64
12	550ms	                630ms
24	980ms	                1130ms
48	1900ms	                2200ms
```

### Reproduced Steps

```shell
dddd
```

**Comment by p517332051** [comment]
top_p=1 ; p value for top p sampling
temperature=1.0 ; Use for sampling
repetition_penalty=2.0 ; Use for sampling
len_penalty=0.0
beam_search_diversity_rate=0.0
data_type=fp16
sparse=0
model_name=self_defined
; model_name=megatron_345M
; model_name=megatron_6.7B
; model_name=gpt_175B
; model_name=self_defined
; model_dir=./models/megatron-models/c-model/6.7b/
model_dir=models/openai-gpt-models/c-model/124m/1-gpu/
shared_contexts_ratio=1.0

[request]
request_batch_size=1   ; determine by the request
request_output_len=256   ; determine by the request
return_log_probs=false  ; return the output log probs and cumulative log probs.
context_log_probs=false ; include input contexts in the cumulative log probability computation.

[gpt_124M]
head_num=12
size_per_head=64
vocab_size=50257
decoder_layers=12

[gpt_175B]
head_num=96
size_per_head=128
vocab_size=51200
decoder_layers=96

[self_defined]
head_num=16
size_per_head=64
vocab_size=30000
decoder_layers=12

[megatron_345M]
head_num=16
size_per_head=64
vocab_size=51200
decoder_layers=20
#rotary_dim=32

[megatron_6.7B]
head_num=32
size_per_head=128
vocab_size=51200
decoder_layers=32

**Comment by byshiue** [comment]
If you mean that under the constraint `size_per_head * head_num = 1024`, the latencies of `size_per_head` 32 and 64 are little different, this is an expected behavior because their gemm shape of attention are different.

**Comment by p517332051** [comment]
Only the masked_multihead_attention_kernel. and other kernel, 64 is faster than 32 .

**Comment by byshiue** [comment]
For other kernels, if you keep `size_per_head * head_num = 1024`, they should be same.

For MHA, this is an expected result.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
