### ISSUE TITLE
fastertransformer/kernels/add_bias_transpose_kernels.cu(161): error: identifier "uint32_t" is undefined           detected during instantiation of "void fastertransformer::invokeTransposeMultiHeadToSingle(T *, T *, int, int, int, int, cudaStream_t) [with T=half]" (215): here

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/FasterTransformer#315]
### Description

```shell
fastertransformer/kernels/add_bias_transpose_kernels.cu(161): error: identifier "uint32_t" is undefined
          detected during instantiation of "void fastertransformer::invokeTransposeMultiHeadToSingle(T *, T *, int, int, int, int, cudaStream_t) [with T=half]"
(215): here
```

### Reproduced Steps

```shell
cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
make -j8
```

**Comment by byshiue** [comment]
Please provide the docker you use.

If you don't use docker, then this should be a issue for environment setting. We suggest using the docker first.

**Comment by jinfagang** [comment]
@byshiue I have to using customized docker, (which might not same as fastertransformer env). So I tested it locally first. (I assume this code shouldn't so creepy only can run on serveral certain envs)

My nvcc:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

Any further instructions?

**Comment by byshiue** [comment]
We recommend using docker first because you can compare the environment of recommended docker and customized docker to find the reason of issue. And we can also help reproducing the issue from our side. It is not a limitation, but only a convenient way to develop and debug.

From the debug message, the program cannot find the `uint32_t` data type, which should be a fundamental data type of C++. It should be a issue of C++ environment setting.

**Comment by jinfagang** [comment]
@byshiue hi. I am using a docker works. I searched a little bit, seems there someone report also simillar error in nccl repo and claims it's a bug of CUDA11.5.

Should I using cuda 11.6?

**Comment by byshiue** [comment]
If you guess this is a issue of CUDA 11.5, you can try the `nvcr.io/nvidia/pytorch:21.12-py3` docker image to build the FT. This docker image contains CUDA 11.5.

**Comment by jinfagang** [comment]
@byshiue hi, will try this docker. meanwhile, my system env is CUDA 11.5, g++10, can u give me a loose version requirements to build? (I get confused by this build error, very confused....)

**Comment by byshiue** [comment]
> @byshiue hi, will try this docker. meanwhile, my system env is CUDA 11.5, g++10, can u give me a loose version requirements to build? (I get confused by this build error, very confused....)

CUDA version should not be a issue. We have verified on CUDA 11.2 ~ CUDA 11.7 (from 21.02 ~ 22.07), all work. We don't check the version of g++ for these docker images.

**Comment by jinfagang** [comment]
add #include <stdint.h> solved above error.........
now:

```
/kernels/quantize_weight.cu(113): error: identifier "printf" is undefined
```

**Comment by byshiue** [comment]
The reason may be because the packages of `uint32_t`, `printf` are included in path of docker we recommend, but not included in your environment.

**Comment by jinfagang** [comment]
@byshiue that could be a reason. But why not just support `/usr/include/' ? its default system include path...... at least it should able include STL....

**Comment by jinfagang** [comment]
I included #inlcude "stdio.h" can't solve printf undefined error.....

**Comment by jinfagang** [comment]
@byshiue Can u please provide me a doable solution? ... this is the strangest include behavior I have ever seen in c++ projects....
Can not even include stdio....

**Comment by byshiue** [comment]
Can you try the recommended docker first?

**Comment by jinfagang** [comment]
@byshiue ..........
I have built in docker already, now I want build on local.....

**Comment by byshiue** [comment]
Can you post the message after cmake and the building log?

**Comment by jinfagang** [comment]
@byshiue like this:

```
cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..

-- The CXX compiler identification is GNU 10.3.0
-- The CUDA compiler identification is NVIDIA 11.6.124
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "11.6", minimum required is "10.2")
CUDA_VERSION 11 is greater or equal than 11, enable -DENABLE_BF16 flag
-- Add DBUILD_MULTI_GPU, requires MPI and NCCL
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found NCCL: /usr/local/include
-- Determining NCCL version from /usr/local/include/nccl.h...
-- Looking for NCCL_VERSION_CODE
-- Looking for NCCL_VERSION_CODE - not found
-- Found NCCL (include: /usr/local/include, library: /usr/local/lib/libnccl.so)
-- Assign GPU architecture (sm=70,75,80,86)
CMAKE_CUDA_FLAGS_RELEASE: -O3 -DNDEBUG -Xcompiler -O3 --use_fast_math
-- COMMON_HEADER_DIRS: /home/xx/dev/codes/work/toolchains/accformer/ft;/usr/local/cuda/include
-- Found CUDA: /usr/local/cuda (found version "11.6")
-- Caffe2: CUDA detected: 11.6
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.6
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found cuDNN: v8.5.0  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 4dd39364
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
CMake Warning at /home/xx/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/xx/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:209 (find_package)


-- Found Torch: /home/xx/.local/lib/python3.10/site-packages/torch/lib/libtorch.so
-- USE_CXX11_ABI=False
-- Configuring done
-- Generating done
-- Build files have been written to:
```

**Comment by byshiue** [comment]
What's the error message?

**Comment by jinfagang** [comment]
I have solved it.

**Comment by maxhgerlach** [comment]
What was your workaround @lucasjinreal ?

**Comment by Zerrun** [comment]
> I have solved it.

same problem ，would you share us how did you solved it ?

**Comment by maxhgerlach** [comment]
I ended up sticking an `export CUDAFLAGS="-include stdio.h"` in front of the `cmake` call.
