### ISSUE TITLE
undefined reference to `cublasLtMatmulDescCreate'

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/FasterTransformer#319]
### Description

```shell
CUDA 11.6
cudnn 11.x 8.5
```

### Reproduced Steps

```shell
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmulDescCreate'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmulAlgoConfigSetAttribute'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatrixLayoutDestroy'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtCreate'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmulAlgoInit'
/usr/bin/ld: ../../../lib/libGptJTritonBackend.so: undefined reference to `cublasLtMatmulDescCreate'
/usr/bin/ld: ../../../lib/libGptNeoXTritonBackend.so: undefined reference to `cublasLtMatmulDescCreate'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmulDescDestroy'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmul'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatmulDescSetAttribute'
/usr/bin/ld: ../../../lib/libParallelGptTritonBackend.so: undefined reference to `cublasLtMatrixLayoutCreate'

```
```


## cmake output

```
CUDA_VERSION 11 is greater or equal than 11, enable -DENABLE_BF16 flag
-- Assign GPU architecture (sm=70,75,80,86)
CMAKE_CUDA_FLAGS_RELEASE: -O3 -DNDEBUG -Xcompiler -O3 --use_fast_math
-- COMMON_HEADER_DIRS: /home/xx/dev/codes/work/toolchains/accformer/ft;/usr/local/cuda/include
-- Caffe2: CUDA detected: 11.6
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.6
-- Found cuDNN: v8.5.0  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 4dd39364
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
CMake Warning at /home/xx/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/xx/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:210 (find_package)

-- USE_CXX11_ABI=False
-- Configuring done
-- Generating done
-- Build files have been written to:
```

**Comment by byshiue** [comment]
Can you reproduce this issue in recommended docker? 
If not, please check that the so files of cublasLt are included in your `LD_LIBRARY_PATH`.

**Comment by jinfagang** [comment]
@byshiue Hi, my cudnn and cuda are a very typical path on ubuntu, `/usr/local/cuda` without any fancy, why it can not found? Please have a look on my cmake ouptut, it says found cdnn, why said cudnn link error??

**Comment by jinfagang** [comment]
Does fasterransformer didn't support CUDA11.6 && cudnn8.5???? these undefined APIs are outdated. There should be `cublasLtCreate_v2` on new one.

**Comment by byshiue** [comment]
Try 
```
ldd lib/libGptJTritonBackend.so
```

**Comment by jinfagang** [comment]
@byshiue hi.

```
ldd lib/libGptJTritonBackend.so                                                                                                                  130 ↵
	linux-vdso.so.1 (0x00007f45ad363000)
	libcublas.so.11 => /usr/local/cuda/lib64/libcublas.so.11 (0x00007f459a000000)
	libcudart.so.11.0 => /usr/local/cuda/lib64/libcudart.so.11.0 (0x00007f4599c00000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f45999d6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4599f19000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f45a37fa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45997ae000)
	libcublasLt.so.11 => /usr/local/cuda/lib64/libcublasLt.so.11 (0x00007f4584600000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f45a37f5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f45a37f0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f45a37eb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f45ad365000)

```

**Comment by jinfagang** [comment]
@byshiue Can u please try on cuda11.6 && cudnn8.5?? I suspect your code didn't support this combination at all.............. It's really creepy for this code.

**Comment by jinfagang** [comment]
@byshiue Also, please give me an suggestion how to disable this triton backbone, Id on't need it at this moment...... I un bale to disbale it no matter what I do, when change cmakelist, it will change **a lot** thing........

**Comment by jinfagang** [comment]
@byshiue I don't konw how did u develop this lib:

```
 nm -D /usr/local/cuda/lib64/libcublas.so | grep cublasCreate
00000000001ca6e0 T cublasCreate_v2@@libcublas.so.11

```

Like I said new cudnn8.5 didn't have your code API calling, could u tell me how to run on cudnn8.5??

**Comment by jinfagang** [comment]
solved.

**Comment by vgarimellaTuring** [comment]
Hi @jinfagang, @byshiue I am also facing the same issue of undefined reference to cublasLtMatmulDescCreate while running make on latest main branch, using CUDA 10.2 on A100 GPU. Can you please let me know what the fix was to this.

**Comment by byshiue** [comment]
This means the program cannot find correct cublaslt .so files in your `LD_LIBRARY_PATH`. You should check where are for your libcublaslt.so, and add the path into your environment variable. 

That's why we suggest using the docker we list first because all environment are setup in the docker image.

**Comment by vgarimellaTuring** [comment]
okay, got it. Where can we locate libcublaslt.so in our system

**Comment by byshiue** [comment]
By default, it should be at `/usr/local/cuda/lib64/libcublasLt.so`.
