### ISSUE TITLE
Coredump occur when I use T5 model inference chinese sentences length > 205 in TensorRT FP16 mode.

### ISSUE THREAD

**Issue by sunkenQ** [NVIDIA/FasterTransformer#329]
### Description

```shell
branch: main
docker_images: I use docker file provided by https://github.com/NVIDIA/TensorRT/tree/main/docker, build command "./docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu18.04-cuda11.6"
gpu : v100

I use T5-base model for inference, FP32 works fine, but in FP16, no matter what the input is, once the input exceeds 205  the program will core dump. The same problem occurs with both the T5-base model provided by Transformer Model Zoo and my own T5 Chinese model. 
I also tried debugging and found that if line 499 in src/fastertransformer/kernels/beam_search_topk_kernels.cu is commented out, it can be inferred successfully even if the result is wrong, and core dump will not occur, but I don't know how to solve this problem.

```

### Reproduced Steps

```shell
1. git clone https://github.com/NVIDIA/TensorRT.git
2. cd docker && ./docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu18.04-cuda11.6
3. docker run -it -p 43010:43010 --ipc=host -v /my_project:/my_project--name cuda-lastest tensorrt-ubuntu18.04-cuda11.6:lastest /bin/bash
4. git clone https://github.com/NVIDIA/FasterTransformer.git
5. cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_TRT=ON -DBUILD_MULTI_GPU=ON ..
6. make -j12
7. change input in testT5Plugin.py to a Chinese sentence longer than 205
8. CUDA_VISIBLE_DEVICES=0 python ../examples/tensorrt/t5/testT5Plugin.py \
        --batch_size 1 \
        --beam_width 2 \
        --max_seq_len 128 \
        --data_type fp16 \
        --ckpt_path ./t5-base/1-gpu
```

**Comment by byshiue** [comment]
Can you try the docker `nvcr.io/nvidia/pytorch:22.07-py3`? 

Besides, please provide the script to reproduce the error. 

And, how do you ensure the tokenizer of T5 can handle the Chinese sentence?

**Comment by sunkenQ** [comment]
> 

Thank you for reply

In fact, I implemented BART model by referring to your T5 code, for some reason I use BertTokenizer and it works well in fp32 but core dump in fp16, I wonder T5 may work fine with BertTokenizer in fp16. I see t5-base vocab size is 30000+ and my bert vocab size is 21128, so I think the vector that I put in should get wrong inference result and at least it should be able to complete the inference instead of get a core dump. I just tried to change the BertTokenizer back to T5Tokenizer and T5 work fine!

I'll try ` nvcr.io/nvidia/pytorch:22.07-py3` docker image and give you exact reply layer. Thanks again for your work.

**Comment by sunkenQ** [comment]
> Can you try the docker `nvcr.io/nvidia/pytorch:22.07-py3`?
> 
> Besides, please provide the script to reproduce the error.
> 
> And, how do you ensure the tokenizer of T5 can handle the Chinese sentence?

In fact, I implemented BART model by referring to your T5 code, for some reason I use BertTokenizer and it works well in TensorRT fp32 but core dump in fp16, I wonder T5 may work fine with BertTokenizer in fp16. I see t5-base vocab size is 30000+ and my bert vocab size is 21128, so I think the vector that I put in should get wrong inference result but at least it should be able to complete the inference instead of get a core dump. I just tried to change the BertTokenizer back to T5Tokenizer and T5 work fine, now I think there's something wrong with my code.

I'll try ` nvcr.io/nvidia/pytorch:22.07-py3` docker image and give you exact reply later. Thank you for your work, it worked very well.

**Comment by byshiue** [comment]
I am not sure can we use the T5 tokenizer for BART. 

You can run the codes like 
```
FT_DEBUG_LEVEL=DEBUG FT_LOG_LEVEL=DEBUG python ../examples/tensorrt/t5/testT5Plugin.py ...
```
and post the error messages here.

**Comment by sunkenQ** [comment]
> I am not sure can we use the T5 tokenizer for BART.
> 
> You can run the codes like
> 
> ```
> FT_DEBUG_LEVEL=DEBUG FT_LOG_LEVEL=DEBUG python ../examples/tensorrt/t5/testT5Plugin.py ...
> ```
> 
> and post the error messages here.

Sorry for the ambiguity in my words. I mean T5 with T5 Tokenizer will not core dump in inference a Chinese long sentences, if use BertTokenizer will core dump instead. Currently I can only use BertTokenizer with Bart, there is debug screenshot.
![image](https://user-images.githubusercontent.com/41413441/192513813-0ca0f6b5-fc72-4441-b797-ba498014c038.png)

**Comment by sunkenQ** [comment]
> I am not sure can we use the T5 tokenizer for BART.
> 
> You can run the codes like
> 
> ```
> FT_DEBUG_LEVEL=DEBUG FT_LOG_LEVEL=DEBUG python ../examples/tensorrt/t5/testT5Plugin.py ...
> ```
> 
> and post the error messages here.

I add the code and there is debug screenshot. It looks like a memory problem.
![image](https://user-images.githubusercontent.com/41413441/192513813-0ca0f6b5-fc72-4441-b797-ba498014c038.png)

**Comment by sunkenQ** [comment]
> I am not sure can we use the T5 tokenizer for BART.
> 
> You can run the codes like
> 
> ```
> FT_DEBUG_LEVEL=DEBUG FT_LOG_LEVEL=DEBUG python ../examples/tensorrt/t5/testT5Plugin.py ...
> ```
> 
> and post the error messages here.

我发现我们可以用中文交流？我在您实现的T5上配合T5Tokenizer输入中文长句确实没问题了，我使用自己实现的BART配合BertTokenizer输入长句仍然core dump，所有的Error message贴入后发现无法换行，所以我上传了debug.log文件，希望您看后能给我一些指点，谢谢！
[debug_bart.log](https://github.com/NVIDIA/FasterTransformer/files/9655127/debug_bart.log)

**Comment by byshiue** [comment]
Then it means that there are some bugs in your implementation. For core dump, a possible reason is you miss some inputs. We cannot locate the error position by current log now. You can add some debug message to help locate the point, find where the program crash. And then check all inputs are valid before entering the function.

**Comment by sunkenQ** [comment]
> Then it means that there are some bugs in your implementation. For core dump, a possible reason is you miss some inputs. We cannot locate the error position by current log now. You can add some debug message to help locate the point, find where the program crash. And then check all inputs are valid before entering the function.
