### ISSUE TITLE
GPT Megatron345m FasterTransformer [WARNING] file ./models//model.wte.bin only has 206045184, but request 209715200, loading model fails! when running cpp_benchmarks.sh 

### ISSUE THREAD

**Issue by vgarimellaTuring** [NVIDIA/FasterTransformer#330]
### Description

Hi, when I try to run the cpp_benchmark.sh on V100, I see a warning message saying 
[FT][WARNING] file ./models//model.wte.bin only has 206045184, but request 209715200, loading model fails! 

However, the results do get generated in the all-log.log file. Request you to guide me if the warning message is a hint of something unusual or it is an known issue.

### Reproduced Steps

Followed the steps in GPT guide https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md to build a C++ project and run cpp_benchmark.sh

**Comment by byshiue** [comment]
`cpp_benchamrk.sh` is only used to run benchmark on random checkpoint. So, we fix the `vocab_size` as 51200. The default vocab size of the checkpoint Megatron 345M is 50304, but not 51200.

**Comment by vgarimellaTuring** [comment]
thanks a lot!, I changed the vocab_size to 50304 and the warning goes away.
