### ISSUE TITLE
GPT Megatron345m FasterTransformer cpp_benchmark.sh produces latency benchmark result with batch_size 1 latency > batch_size 4 latency

### ISSUE THREAD

**Issue by vgarimellaTuring** [NVIDIA/FasterTransformer#331]
### Description

Hi, when I run the cpp_benchmark.sh on GPT Megatron 345m model, I see the following results:

<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1664341992976' ccp_infra_user_hash='3095310291' ccp_infra_copy_id='5540bc15-cc39-4f32-9ece-8d723b837e6c' data-ccp-timestamp='1664341992976'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"></head><body link="#0563C1" vlink="#954F72">

model_size | batch_size | input_length | output_length | decode_value | precision | FT latency (ms)
-- | -- | -- | -- | -- | -- | --
345m | 1 | 60 | 80 | beamsearch, 4 | FP16 | 233.83ms
345m | 4 | 60 | 80 | beamsearch, 4 | FP17 | 223.45ms
345m | 16 | 60 | 80 | beamsearch, 4 | FP18 | 302.59ms
345m | 1 | 60 | 80 | sampling, 4 | FP19 | 159.83ms
345m | 1 | 60 | 80 | sampling, 0.5 | FP20 | 166.38ms
345m | 4 | 60 | 80 | sampling, 4 | FP21 | 233.82ms
345m | 4 | 60 | 80 | sampling, 0.5 | FP22 | 239.12ms
345m | 16 | 60 | 80 | sampling, 4 | FP23 | 228.40ms
345m | 16 | 60 | 80 | sampling, 0.5 | FP24 | 233.45ms

</body></html></div>
</body>
</html>
Here I am not sure why batch size 1 for beamsearch has greater latency than batch_size 4 (233.83ms vs 223.45ms). Request to guide me on this.

### Reproduced Steps

Followed the steps in GPT guide https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md to build a C++ project and run cpp_benchmark.sh

**Comment by byshiue** [comment]
For bs 1 and 4, they have almost same latency we cannot fully use GPU in such problem size. 
So, the difference is caused by noise. You can lock the frequency of GPU clock and run more iterations to get more stable number.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
