### ISSUE TITLE
Deberta Support

### ISSUE THREAD

**Issue by yaysummeriscoming** [NVIDIA/FasterTransformer#335]
Deberta is now the SOTA encoder model and is seeing a lot of uptake. It's currently in the top 10 most downloaded models on HF model hub, with 5.5M downloads (https://huggingface.co/microsoft/deberta-base). Would be great if it could be supported in FT

**Comment by byshiue** [comment]
Thank you for the suggestion, we will consider it.

**Comment by byshiue** [comment]
The model is supported in latest v5.3 version. Currently, we provide example on TensorFlow 2. More features and examples are developing.

**Comment by yaysummeriscoming** [comment]
Awesome, thank you!
