### ISSUE TITLE
How would I pad inputs during batched inference?

### ISSUE THREAD

**Issue by sdpmas** [NVIDIA/FasterTransformer#344]
Hi,

I am running GPT-J with FasterTransformer with triton (using [this backend](https://github.com/triton-inference-server/fastertransformer_backend/tree/main)). Triton supports dynamic batching, so if I want to batch inputs, how would I pad inputs so that they are the same length? Ideally, we would pad inputs from the right and create an attention mask to give info to the model saying the first `n` tokens are pad tokens. Is there a way of doing so with FasterTransformer?

**Comment by byshiue** [comment]
You only need to pad inputs to same length and provide the real sequence length like
```
input:
[  [a, b, x],
   [a, x, x],
   [a, b, c]
]

seq_len:
[ 2, 1, 3]
```

**Comment by sdpmas** [comment]
Hi @byshiue, thanks for your quick reply! I tried padding inputs like following:
original input: `[27, 91, 29412, 91, 29, 198, 2, 8818, 284, 3440, 257, 2298, 293, 2393, 198, 4299, 3440]`
padded input (to length of 50): `[27, 91, 29412, 91, 29, 198, 2, 8818, 284, 3440, 257, 2298, 293, 2393, 198, 4299, 3440, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256]`
input_len: `17`

Here, `50256` is the pad token. Since I am using [this backend](https://github.com/triton-inference-server/fastertransformer_backend/tree/main), I pass `seq_len` as `input_lengths` tensor as shown [here](https://github.com/triton-inference-server/fastertransformer_backend/blob/5a78164d2449f12dfd23a575cc29d4e8e052f1bf/all_models/gptj/fastertransformer/config.pbtxt#L57) and padded input as `input_ids`. However, doing so gives significantly worse results than one without padding at the end. Am I doing it correctly?

**Comment by byshiue** [comment]
Do you pass sequence length as 17 (length of original input)?

**Comment by sdpmas** [comment]
yes, I set the `input_lengths` tensor to 17

**Comment by byshiue** [comment]
Can you post the results of 
1. original input + output
2. padding input + output

**Comment by sdpmas** [comment]
decoded input (same input ids as above): `<|python|>\n#function to load a pickle file\ndef load`
1. Original input + output
```
[   27    91 29412    91    29   198     2  8818   284  3440   257  2298 293  2393   198  4299  3440    62 27729   293     7 34345  2599   198 50284  4480  1280     7 34345    11   705 26145 11537   355   277    25 198 50280  7783  2298   293    13 2220     7    69     8   198]
```
decoded_output: `_pickle(filename):\n    with open(filename, 'rb') as f:\n        return pickle.load(f)\n`
2. Padding input + output
```
[   27    91 29412    91    29   198     2  8818   284  3440   257  2298 293  2393   198  4299  3440    62   796  2298   293    13  2220     7 9654  7203 27729   293    14 27729   293    13    79 41582  1600   366 26145 48774   198   198     2  8818   284  3613   257  2298   293 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256]
```
decoded_output: `'_ = pickle.load(open("pickle/pickle.pkl", "rb"))\n\n#function to save a pickle'`

Let me know if you have any further questions!

**Comment by byshiue** [comment]
I use your inputs to test on GPT-J model and cannot reproduce your issue. 

The results of my side:
```
topk 1, topp 0
[[[   27    91 29412    91    29   198     2  8818   284  3440   257
    2298   293  2393   198  4299  3440    62 27729   293     7 34345
    2599   198   220   220   220  1303  9654   262  2393   198   220
     220   220   277   796  1280     7 34345    11   705 26145 11537
     198   220   220]]]

[[[   27    91 29412    91    29   198     2  8818   284  3440   257
    2298   293  2393   198  4299  3440    62 27729   293     7 34345
    2599   198   220   220   220  1303  9654   262  2393   198   220
     220   220   277   796  1280     7 34345    11   705 26145 11537
     198   220   220 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256]]]

topk 0, topp 0.75
[[[   27    91 29412    91    29   198     2  8818   284  3440   257
    2298   293  2393   198  4299  3440    62 27729   293     7 34345
    2599   198   220   220   220   277   796  1280     7 34345    11
     705 26145 11537   198   220   220   220  1366   796  2298   293
      13  2220     7]]]

[[[   27    91 29412    91    29   198     2  8818   284  3440   257
    2298   293  2393   198  4299  3440    62 27729   293     7 34345
    2599   198   220   220   220   277   796  1280     7 34345    11
     705 26145 11537   198   220   220   220  1366   796  2298   293
      13  2220     7 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
   50256 50256 50256]]]
```
after setting the `FIXED_START_IDS` of `tools/gpt/identity_test.py` to
```
[27, 91, 29412, 91, 29, 198, 2, 8818, 284, 3440, 257, 2298, 293, 2393, 198, 4299, 3440]
```
and 
```
[27, 91, 29412, 91, 29, 198, 2, 8818, 284, 3440, 257, 2298, 293, 2393, 198, 4299, 3440, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256]
```
(Note that `input_len` are fixed to `17` for both cases)

Do you use the latest codes of `main` branch? If yes, please provide the reproduce steps to reproduce your issue.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
