### ISSUE TITLE
More details about "attention time-limited memory"

### ISSUE THREAD

**Issue by dongdaoking** [NVIDIA/FasterTransformer#345]
Hi, i find a new feature  **attention time-limited memory** in v5.1. 
How does it work ?

**Comment by byshiue** [comment]
Users can set the max length for memory cache. Then FT will forget oldest memory when the sequence length is larger than max length during generation.

**Comment by dongdaoking** [comment]
Thanks for reply.
I download [v5.1 T5 triton bug fix](https://github.com/NVIDIA/FasterTransformer/releases/tag/release%2Fv5.1_bugfix_tag) release code and can't find function parameter for "the max length for memory cache" in tensorflow lib "libtf_decoding.so" with function "decoding".
So which transformer variant can support this feature? It seems standard transformer can't support it.

**Comment by byshiue** [comment]
https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md#interactive-text-generation

**Comment by dongdaoking** [comment]
OK，thanks.
