### ISSUE TITLE
HuggingFace6.7B GPT FT input sequence length 979, output sequence length 45 has lower latency than input sequence length 60 and output sequence length 80. [run via cpp_benchmark.sh]

### ISSUE THREAD

**Issue by vgarimellaTuring** [NVIDIA/FasterTransformer#347]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.03-py3

### GPU name

V10V100-32GB

### CUDA Driver

10.2.89

### Reproduced Steps

```shell
1. docker run -ti --gpus all nvcr.io/nvidia/pytorch:22.03-py3 bash
2. git clone https://github.com/NVIDIA/FasterTransformer.git
3. cd FasterTransformer mkdir build && cd build
4. cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTI_GPU=OFF ..
5. make
6. cd FasterTransformer/benchmarks/gpt/
7. ./cpp_benchmark.sh
```

When I run the cpp_benchmark.sh script for GPT FT HuggingFace 6.7B model. The latency I see for the setting batch size 8, input sequence length 60 and output sequence length 80 is 1.5s. But for the same model, for batch size 8, input sequence length 979 and output sequence length 45 the latency is 0.8s. 

Request you to guide me if the behavior is expected.

**Comment by byshiue** [comment]
This is an possible behavior because input length 979 is much longer than input length 60 (15x), while the output length is only 0.5x (45 v.s. 80).

**Comment by vgarimellaTuring** [comment]
Hi byshiue, yes, but I am observing for input sequence length 979 and output sequence length 45, latency is 0.8s, lower than 1.5s for input sequence length 60 and output sequence length 80. Can the autoregressive generation of 45 tokens vs 80 tokens be the bottleneck (as we won't have the auto-regressive generation for inputs, only the self-attention computation latency will be higher for 979 vs 60).

**Comment by byshiue** [comment]
Ok, I misunderstand your meaning. For autoregressive generation, 45 tokens must faster than 80 tokens. The time grows almost linearly when we increase the generation tokens. 
The question is only how many time we need to handle the input sequence. In most cases, we need fewer time to handle input sequence (like 10% or 20%), this this ratio grows when you increase the batch size.

**Comment by vgarimellaTuring** [comment]
okay, got it. Then doing some back of the envelope calculation if 979 inputs self attention takes x time and 45 output token generation takes y time. Then, would it be possible to assume (1/f(bs)) * x * 60/979 time for 60 input token generation, where f(bs) is a factor (10% or 20% depending on batch size) and for output token generation, it is y * 80/45 (just linear scaling).

Is there a way we can measure the individual breakdown of latencies. Also, is the fewer time to handle the input sequence for smaller batches due to not full GPU utilization.

**Comment by byshiue** [comment]
> Then, would it be possible to assume (1/f(bs)) * x * 60/979 time for 60 input token processing, where f(bs) is a factor
No, it may be non-linear at the beginning. I am not sure when we can fully use the GPU utilization. 

> Is there a way we can measure the individual breakdown of latencies.
We don't expose it now. User need to modify codes or use nvtx and nsight systems to measure.

> Also, is the fewer time to handle the input sequence for smaller batches due to not full GPU utilization.
Correct.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
