### ISSUE TITLE
how to debug a torch op?

### ISSUE THREAD

**Issue by AkiyamaYummy** [NVIDIA/FasterTransformer#364]
I had developed a GPT-NEOx torch op. but when I load the .so lib file and execute the python code, it throws an exception without any additional message or traceback.

```
#python /project/deployment/FTGeneration.py
[INFO] WARNING: Have initialized the process group
Segmentation fault (core dumped)
```

so I want to ask your way to debug torch op when you develop yours. excuse me for I m not familiar with c++. thx.

**Comment by byshiue** [comment]
Add debug/log message into the pytorch op and trace code by code.

**Comment by AkiyamaYummy** [comment]
> Add debug/log message into the pytorch op and trace code by code.

oh, I see. I'll do the same. thx so much.
