### ISSUE TITLE
Using bert unfused zero padding

### ISSUE THREAD

**Issue by yoni64** [NVIDIA/FasterTransformer#366]
Looking at code make me a little confused on how zero padding is handled by Bert fp32 implementation (as an example).
After calculating sequence offset tensor, the padding is removed by **invokeRemovePadding** called in Bert.cc:371.
Then the **unfusedAttentionLayer** forward is called with the zero padded input, it first call is to cublas GEMM (**UnfusedAttentionLayer.cc:100**) .
My question is how can it work? Does the input for this GEMM has padding removed or I missed something? 
If it does, how can the same GEMM work with zero padded and with padded input?
P.S
I tested by padding  input with zeros, according to sequence length, and check execution results with removed padding feature and without. Results were not the same!

**Comment by byshiue** [comment]
In UnfusedAttentionLayer, we will rebuild padding before running batched gemm.

**Comment by yoni64** [comment]
> In UnfusedAttentionLayer, we will rebuild padding before running batched gemm.

I followed the flow of  UnfusedAttentionLayer, in gdb  for the first entry. 
The "if_batch_QKV" in line 70 is false, so it go first to GEMM in line 100 (and not the batch GEMM).
The input for this GEMM is derived from  "bert_input_ptr" in Bert.cc:456 as for the first layer (l=0). 
The "bert_input_ptr" is compressed (zero pad) by **invokeRemovePadding**  in Bert.cc:371
So it seems zero pad data is input  to cublas GEMM. Is this a bug?

**Comment by byshiue** [comment]
For normal cublas, we can use normal GEMM.

**Comment by yoni64** [comment]
> For normal cublas, we can use normal GEMM.

Yes, but for the first iteration (l=0) this GEMM is receiving compressed zero pad input. It seems it would not result correct output.

**Comment by byshiue** [comment]
For normal GEMM with zero data, we can use cublas.

**Comment by yoni64** [comment]
> For normal GEMM with zero data, we can use cublas.

The input for the Gemm is compressed (pad removed). How can a normal GEMM give correct results in this case? Please elaborate.

**Comment by byshiue** [comment]
For padded input, the input shape is `[bs, seq_len, hidden]`. For zero pad input, the input shape is `[token_num, hidden]`. For GEMM view, there are no difference except the number of rows.

**Comment by yoni64** [comment]
> For padded input, the input shape is `[bs, seq_len, hidden]`. For zero pad input, the input shape is `[token_num, hidden]`. For GEMM view, there are no difference except the number of rows.

Thank you for this explanation
