### ISSUE TITLE
duplicating loading model to gpu  resulted in 4x gpu memory cost.

### ISSUE THREAD

**Issue by dearowen** [NVIDIA/FasterTransformer#367]
in the __init__(),wo do self.cuda(). and in init__(),you move float32 model to gpu when your model is just in float16.
https://github.com/NVIDIA/FasterTransformer/blob/9770d307b17b178f1ef31b157aabcf5c8b1fedb2/examples/pytorch/gpt/utils/gpt.py#L342
if you have to load ,do .cuda here again.
https://github.com/NVIDIA/FasterTransformer/blob/9770d307b17b178f1ef31b157aabcf5c8b1fedb2/examples/pytorch/gpt/utils/gpt.py#L347
if you have float16 moel,do .cuda the third times.
https://github.com/NVIDIA/FasterTransformer/blob/9770d307b17b178f1ef31b157aabcf5c8b1fedb2/examples/pytorch/gpt/utils/gpt.py#L351.
so at last your gpu memory will meet "out of memory" problem.
why do we doing such kind of thing?We can do it just one time at last.

https://github.com/NVIDIA/FasterTransformer/issues/367#tasklist-block-b2f2d581-f6a3-4ba4-8e1c-954a4ab1d14b

**Comment by dearowen** [comment]
if you have to load ,do .cuda here again.
https://github.com/NVIDIA/FasterTransformer/blob/9770d307b17b178f1ef31b157aabcf5c8b1fedb2/examples/pytorch/gpt/utils/gpt.py#L347
if you have float16 moel,do .cuda the third times.
https://github.com/NVIDIA/FasterTransformer/blob/9770d307b17b178f1ef31b157aabcf5c8b1fedb2/examples/pytorch/gpt/utils/gpt.py#L347.
and in __inin__(),you move float32 model to gpu when your model is just in float16.
so at last your gpu memory will meet "out of memory" problem.

**Comment by byshiue** [comment]
The example is only a demo about how to use FT's op. We don't optimize all cases in the framework side. We assume these are handled by framework. 
You can try to add some empty cache to clean the useless weights.
