### ISSUE TITLE
The memory have large gap between pytorch and C++

### ISSUE THREAD

**Issue by cdj0311** [NVIDIA/FasterTransformer#371]
hi,
I use gpt2 to generate text, but the memory is large gap between pytorch and C++, model information as follows:

Parameters: 1.3B(24L-16A-2048H)
GPU: TITAN RTX, 24G
Data_type: FP16
Memory-Pytorch: 14GB(gpt_example.py)
Memory-C++: 3.9GB(gpt_example.cc)

And the speed is almost the same(input_len=512, output_len=32, time=200ms)

**Comment by byshiue** [comment]
There are some possible reasons.
1. We do some model preprocessing in pytorch and we don't free them. You can use `torch.cuda.empty_cache` to release the resource before starting forward. 
2. Pytorch uses memory pool, and it often allocate larger memory buffer to prevent allocating buffer many times.

**Comment by cdj0311** [comment]
> There are some possible reasons.
> 
> 1. We do some model preprocessing in pytorch and we don't free them. You can use `torch.cuda.empty_cache` to release the resource before starting forward.
> 2. Pytorch uses memory pool, and it often allocate larger memory buffer to prevent allocating buffer many times.

Thanks! It's work when loaded model with `torch.cuda.empty_cache()`.
