### ISSUE TITLE
layernorm_kernels's result comparing to torch's result is about 0.0x diffreence in fp16 model .

### ISSUE THREAD

**Issue by dearowen** [NVIDIA/FasterTransformer#375]
### Branch/Tag/Commit

default

### Docker Image Version

default

### GPU name

v100

### CUDA Driver

10.0

### Reproduced Steps

```shell
when weight'type is fp16,torch layernorm'result is different from cuda kernel's result.
THe difference is about 0.0x.how can i decrease the difference?
```

**Comment by byshiue** [comment]
If you mean that the difference between cuda layernorm and torch layernorm is about 0.01 under fp16, this is a common behavior.

**Comment by dearowen** [comment]
The 0.01 difference will make big difference at last for model with Dozens of layers. So i hack the code to do layernorm in fp32 and save the result in fp16，in this way the difference is 0.001.but even 0.001 difference result in different token after the difference increased by many layers. So do you have any suggestion for this problem?

**Comment by byshiue** [comment]
If you use `OPT_TYPE = 2`, you can try `OPT_TYPE=1`.

Also, even for FP16 kernels, you can cast to FP32 to higher accuracy during computing.

**Comment by dearowen** [comment]
the computing following  layernorm is in fp16.I have to cast fp32 normal  val to fp16 in this way:
val.x         = float2type<T1>(float_x_valmul2);
Can you tell me the the way in detail?Thank you.

**Comment by byshiue** [comment]
Sorry, I don't get your question.

**Comment by dearowen** [comment]
“Also, even for FP16 kernels, you can cast to FP32 to higher accuracy during computing.”  can you explain it in detail?

**Comment by byshiue** [comment]
Something like
```c
layernorm(half *out, half *in, half *gamma, half* beta) {
    float val = (float)(in[idx]);
    float mean = reduceMean(val);
    float stddev = reduceMean((val - mean) * (val - mean));
    out_val = (val - mean) / stddev * (float)(gamma[idx]) + (float)(beta[idx]);
    out[idx] = (half)(out_val);
}
```

**Comment by dearowen** [comment]
> Sorry, I don't get your question.
> 
> For `OPT_TYPE`, I mean the setting here https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/kernels/layernorm_kernels.cu#L709

what is the difference between opt and opt2?

**Comment by byshiue** [comment]
opt uses standard formula to compute the mean and variance. 
opt2 uses `E[(X - E[X])^2]  = E[X^2] - (E[X])^2` to compute the variance.

**Comment by byshiue** [comment]
Generate different token is common. We only verify the final qualities.

**Comment by dearowen** [comment]
> Generate different token is common. We only verify the final qualities.

ok,I got it.Thank you for your  reply.
