### ISSUE TITLE
GPT latency problem.

### ISSUE THREAD

**Issue by cdj0311** [NVIDIA/FasterTransformer#377]
Hi,
I inference GPT-2 with python (gpt_example.py) and C++ (gpt_example.c), but the latency is different from [gpt_guide](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md).

model(1.3B): layer_num=24, head_num=32, size_per_head=64
input_len: 512
output_len: 32
batch_size: 1
data_type: fp16
beam_size: 1

**my latency = 210ms (both python and C++)
gpt_guide latency = 135ms**

**Comment by byshiue** [comment]
Can you share the environment (GPU, docker) and your reproduced steps?

**Comment by byshiue** [comment]
The number we show in the document are run by A100. More details are shown in https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md#performance. So, the differences are caused by hardware.
