### ISSUE TITLE
Error: 3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h:5393:62: error: ‘kernel’ was not declared in this scope

### ISSUE THREAD

**Issue by Tripton** [NVIDIA/FasterTransformer#383]
### Branch/Tag/Commit

release/v5.2_tag

### GPU name

Jetson Orin, RTX 3060

### CUDA Driver

L4T 35.1.0, 515.65.01

### Reproduced Steps

```shell
When using the latest release of FasterTransformer it can not be complied because of the following error:

FasterTransformer/3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h:5393:62: error: ‘kernel’ was not declared in this scope
 5393 |         assert(kernelMeta.mD == 64 || kernelMeta.mD == 32 || kernel.mD == 40 || kernel.mD == 80 || kernel.mD == 128
```

Steps to reproduce:
1. git clone https://github.com/NVIDIA/FasterTransformer.git --recursive --branch release/v5.2_tag
2. cd FasterTransformer/
3. mkdir build && cd build/
4. cmake ..
5. make -j

Potential Fix:
Change line 5393 in 3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h to:
```
assert(kernelMeta.mD == 64 || kernelMeta.mD == 32 || kernelMeta.mD == 40 || kernelMeta.mD == 80 || kernelMeta.mD == 128 || kernelMeta.mD == 160 || kernelMeta.mD == 256);
```
or disable the assertion.

**Comment by byshiue** [comment]
Sorry. I don't get your meaning. In https://github.com/NVIDIA/FasterTransformer/blob/release/v5.2_tag/3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h#L5393, the full assertion is
```c
assert(kernelMeta.mD == 64 || kernelMeta.mD == 32 || kernel.mD == 40 || kernel.mD == 80 || kernel.mD == 128
               || kernel.mD == 160 || kernel.mD == 256);
```
what's difference between current implementation and your fixing?

**Comment by Tripton** [comment]
The only difference is that "kernelMeta" is used everywhere and not "kernel".
At the code you linked, after the second || operator "kernel" is used instead of "kernelMeta".
Maybe the variable was called "kernel" before and was forgotten to be updated to "kernelMeta"?

**Comment by byshiue** [comment]
Got it. Nice catch. We have fixed it now. Thank you.

**Comment by Oh-Cest-la-vie** [comment]
Hello, bro. I see your GPU name are Jetson Orin and 3060，so I want to know did you use cross compilation to deploy FT on jetson Orin ? Thanks in advance. @Tripton
