### ISSUE TITLE
Swin Transformer Submodule is outdated

### ISSUE THREAD

**Issue by Tripton** [NVIDIA/FasterTransformer#384]
### Branch/Tag/Commit

release/v5.2_tag

### GPU name

RTX 3060

### CUDA Driver

515.65.01

### Issue

The submodule for the swin transformer in "examples/pytorch/swin/Swin-Transformer-Quantization/" is outdated. The current enforced commit hash is cbaa0d8 from 7 months ago, where the SwinV2 models weren't even released yet. Since then, Microsoft introduced subfolders for the different models in the original repo and this new structure seems also to be used in this repo (e.g. https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/swin/run_test_v1.sh#L4).

However, in the version of the submodule, this folder structure didn't exist yet, which is why none of the scripts are working anymore. It seems like that somebody in development uses a new version of the original Swin Repo, but missed updating the submodule.
Because of this, a lot of the swin examples for FasterTransformer aren't working anymore (when using the old commit hash for the submodule).
Bumping the submodule to a newer commit should solve this problem.

**Comment by byshiue** [comment]
Thank you for the catching. We have updated the commit of SwinTransformer submodule to `b720b4191588c19222ccf129860e905fb02373a7`.
