### ISSUE TITLE
random_seed issue in torch example

### ISSUE THREAD

**Issue by appleeji** [NVIDIA/FasterTransformer#390]
### Branch/Tag/Commit

main

### Docker Image Version

https://nvcr.io/nvidia/pytorch:20.12-py3

### GPU name

V100

### CUDA Driver

418.67

### Reproduced Steps

```shell
1. docker run -it --gpus all nvcr.io/nvidia/pytorch:22.03-py3 bash
2. git clone https://github.com/NVIDIA/FasterTransformer.git
3. cd FasterTransformer && mkdir build && cd build
4. cmake -DSM=70,75,80 -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTI_GPU=ON -DBUILD_PYT=ON .. && make -j32
5. mpirun --allow-run-as-root -np 2  python ../examples/pytorch/gpt/multi_gpu_gpt_example.py --enable_random_seed --top_k 32 --max_batch_size 1 --tensor_para_size 2 --ckpt_path ../models/megatron-models/c-model/345m/2-gpu
```

## Promble
1. Random seed is fixed and does not change.
2. Each gpu has a different random seed, when tensor_para_size is 2 or more.

## Promblem-1
https://github.com/pytorch/pytorch/issues/5059
I haven't been able to find the exact cause, but I suspect it's something similar to the one above.
I confirmed that it can be solved by simply using `random.randint()`

## Promblem-2
Since the random seed between processes is different, the generation of tokens between GPUs is different, resulting in strange sentence generation.

```
[INFO] batch 0, beam 0:
[Context]
<|endoftext|>

[Output]
T'll be with by a, in my nod and the post (I had to do a bit of a: it's no subject of an new discussion,
```

**Comment by appleeji** [comment]
## Fixed Result
```
[Context]
<|endoftext|>

[Output]
The's about excitingscriptistically good year for the NFL. particularly is to way. But Jaguars lost Bucs were still only two teams in NFL with are under .
```

**Comment by byshiue** [comment]
> 1. Random seed is fixed and does not change.
> 2. Each gpu has a different random seed, when tensor_para_size is 2 or more.

I don't get your meaning for question 1. But for question 2, we have fixed the random seed of torch in https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/multi_gpu_gpt_example.py#L143. So, all processes should generate same random seed in https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/multi_gpu_gpt_example.py#L194. Do you verify that they generate different seeds on different processes?

**Comment by appleeji** [comment]
ok thank you i missed it.
For randomness, it seems necessary to change the parameter of torch.manual_seed() every time. 
At this time, isn't sync between gpu required?

**Comment by appleeji** [comment]
Thank you for your confirmation.I understood what you meant.
Thank you for your confirmation.
