### ISSUE TITLE
Faster Transformer swin transformer int8 quantization

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/FasterTransformer#393]
Hi, I'm looking at the code and find that for PatchEmbed class, the __init__ takes do_quant with False as default value. There is a check afterwards saying that 
```
if QUANT and do_quant:
            self.proj = QuantizedConv2d(in_chans, embed_dim, patch_size, patch_size, bias=True)
```

It seems that only QUANT and do_quant both set to true, it will use quantized conv2d. However, I don't think do_quant is set to true anywhere? Is this intended feature?

The file I am reading is: https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/swin/Swin-Transformer-Quantization/models/swin_transformer.py

![image](https://user-images.githubusercontent.com/104115572/207265905-c8ff2427-05c5-4896-a817-0b8b46658a8c.png)

**Comment by byshiue** [comment]
The option is always false because we don't really quantize this operation although we have considered during developing.
