### ISSUE TITLE
Hardcoded OPT model size in huggingface_opt_convert

### ISSUE THREAD

**Issue by chenho74** [NVIDIA/FasterTransformer#395]
### Branch/Tag/Commit

v5.2_bug_fix_tag

### Docker Image Version

na

### GPU name

na

### CUDA Driver

na

### Reproduced Steps

In GPT guide to run OPT in floating point and int8, it shows that we can use OPT of various sizes. However, in the script to convert OPT to Fastertransformer format https://github.com/NVIDIA/FasterTransformer/blob/cc524cd7ecbb40e4bdbd8d611daa7d779174e68d/examples/pytorch/gpt/utils/huggingface_opt_convert.py#L254, the tokenizer used was hardcoded to 125m. Is this acceptable or do we need to change this according to the model size we use?

**Comment by byshiue** [comment]
The tokenizers of OPT should be same under different model size, but using `args.in_file` would be better. We will update it in next release.
