### ISSUE TITLE
`masked_multihead_attention_kernel` got incorrectly output bug with `params.masked_tokens` defined

### ISSUE THREAD

**Issue by so2bin** [NVIDIA/FasterTransformer#400]
### Branch/Tag/Commit

v5.1.1

### Docker Image Version

custom linux cuda docker-image with cudnn-11.4

### GPU name

Tesla 2080Ti

### CUDA Driver

470.63.01

### Reproduced Steps

I am an fresher of GPU programe, now i am encoutering an problem with incorrect fasttrransformer output with `FtDecoder` module.

The code here: 
https://github.com/NVIDIA/FasterTransformer/blob/release/v5.1.1/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L1219

seems to implement the same logic of masking like `onmt.modules.multi_headed_attn.MultiHeadedAttention` here: 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/multi_headed_attn.py#L233

I want to call this function with a mask like the `onmt.modules.multi_headed_attn.MultiHeadedAttention` does, so i modified the fasttransformer code and added a parameter: `enc_mask` like this:

1. Line: https://github.com/NVIDIA/FasterTransformer/blob/release/v5.1.1/src/fastertransformer/models/decoder/Decoder.cc#L253 add the input tensor with `enc_mask`:

```C++
std::vector<Tensor> cross_attention_input_tensors{
            Tensor{MEMORY_GPU, data_type, {batch_size, hidden_units_}, normed_self_attn_output_},
            input_tensors->at(1),  // encoder_output [B, seqlen, EbedDim]
            input_tensors->at(2),  // encoder_sequence_length [B]
            input_tensors->at(3),  // finished [B]
            input_tensors->at(4),  // step [1]
            enc_mask,  // enc_mask [B, 1, seqlen]
        };
```

2. Add a line before: https://github.com/NVIDIA/FasterTransformer/blob/release/v5.1.1/src/fastertransformer/layers/attention_layers/DecoderCrossAttentionLayer.cu#L498 

```C++
        params.masked_tokens = enc_mask;

        cross_multihead_attention(params, stream);
```

3. Add a print log after do `cross_attention_dispatch` here: [FasterTransformer/DecoderCrossAttentionLayer.cu at release/v5.1.1 · NVIDIA/FasterTransformer (github.com)](https://github.com/NVIDIA/FasterTransformer/blob/release/v5.1.1/src/fastertransformer/layers/attention_layers/DecoderCrossAttentionLayer.cu#L977)

```C++
    cross_attention_dispatch<T>(q_buf_,
                                attention_weights->query_weight.bias,
                                key_mem_cache,
                                attention_weights->key_weight.bias,
                                value_mem_cache,
                                attention_weights->value_weight.bias,
                                memory_sequence_length,
                                context_buf_,
                                finished,
                                batch_size,
                                batch_size,
                                head_num_,
                                size_per_head_,
                                step,
                                mem_max_seq_len,
                                is_batch_major_cache_,
                                q_scaling_,
                                enc_mask,   // here add enc_mask parameter
                                output_attention_param,
                                stream_);
    sync_check_cuda_error();

    if (step <= 2) {  
        FT_LOG_INFO("------------->>>>>>>decoder-layer cross-attn before finnal linear  step: %d, shpae: [B,1,%d]", step, hidden_units_);
        printMatrix((T*)context_buf_, batch_size, std::min(16, (const int)hidden_units_), hidden_units_, true);
        printf("\n");
    }
```

Now the code is prepared, and when i passed the `enc_mask` parameter with a tensor like this:

```python
# mask: [10, 1, 55], here 10 is batch, 55 is max_seq_len
[
 [[[False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False]]],
 ..., # another same 4 tensor as the above one
 [[[True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
           False, False, False, False, False, False, False, False, False, False,
           False, False, False, False, False]]],  # the last 15 tokens is effectived
 ..., # another same 4 tensor as the above one
]
```

the output of print log is:

![](http://zh-ai-group.ks3-cn-beijing.ksyun.com/aiTest/Snipaste_2022-12-19_17-17-28.png)

Now, you can see the first 5 rows is correct, but the last 5 rows is wrong. As the mathmatic is this:

$$masked(Softmax(\frac {QK^T}{\sqrt {d}}))* V$$

it shoud not be zero on the previous columns of the last 5 rows.

**Comment by byshiue** [comment]
The shape of the mask is `[bs, seq_len]`, which means that it is only used when q, k and v have same length. 
But in cross attention, q and k/v have different length. So, your results are wrong.

**Comment by so2bin** [comment]
@byshiue
Thanks for your reply.  Firstly, i must apologise for the mistake of the QKV formula: the wrong order of `Softmax` and `masked`, the correct formula should be:
$$Softmax(masked(\frac {QK^T}{\sqrt {d}}))* V$$

For your answer, i don't understand what your mean: "A mask with shape: `[bs, seq_len]` is only used when q,k,v have same shape."

Here let me take an example:

For a `K`, `V` with shape: `[bs, h_num, seq_len, h_size]`, and the `Q` with a shape: `[bs, h_num, 1, h_size]`. 

So the result of the following formula should be: `[bs, h_num, 1, seq_len]`
$$\frac {QK^T}{\sqrt {d}}$$

Now a mask with shape: `[bs, 1, 1, seq_len]` can worked to this formula before calculate the `Softmax` and got a masked result with shape of `[bs, h_num, 1, seq_len]`:
$$masked(\frac {QK^T}{\sqrt {d}})$$

And the finnal result of QKV should be a shape: `[bs, h_num, 1, h_size]`
$$Softmax(masked(\frac {QK^T}{\sqrt {d}}))* V$$

So, a mask with shape: `[bs, seq_len]` can totally no problem worked when q,k,v have the same shape.

**Comment by so2bin** [comment]
@byshiue 
> The shape of the FT's mask is `[bs, seq_len]`, which means that it is only used when q, k and v have same length. It is different to mask of OpenNMT. In cross attention, q and k/v have different length. So, your results are wrong.

And i want to know whether i am miss understand the role of the parameter: `params.masked_tokens` of `cross_multihead_attention`?  Or how can i get the same result like the onmt's multiheadattention with an mask specified when using the `cross_multihead_attention` cuda kernel?
Thanks.

**Comment by byshiue** [comment]
The parameter `masked_tokens` is only used in self attention, where the sequence length of q, k and v are same. 

For cross attention, please refer the `DecoderCrossAttentionLayer.cu` about how to apply it on cross attention.

**Comment by so2bin** [comment]
> The parameter `masked_tokens` is only used in self attention, where the sequence length of q, k and v are same.
> 
> For cross attention, please refer the `DecoderCrossAttentionLayer.cu` about how to apply it on cross attention.

Thanks, i understand what your means to `masked_tokens` here. 
But i still can not found any information about how to use the `mask` to the cross attention from the `DecoderCrossAttentionLayer.cu` file, and the `masked_multihead_attention_kernel()` in https://github.com/NVIDIA/FasterTransformer/blob/release/v5.1.1/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L774 is too complicate for me to understand what's wrong when the `mask_tokens` is specified.
So, may you give me more help? This problem havs stuck with me for serveral weeks, thanks.

**Comment by byshiue** [comment]
In cross attention, we skip the elements by `params.memory_length_per_sample`, which implies the length of K/V. So, we don't use mask.
If your cross attention is standard, you can refer `DecoderCrossAttentionLayer.cu` to understand how to set the parameters for cross attention.

**Comment by so2bin** [comment]
> In cross attention, we skip the elements by `params.memory_length_per_sample`, which implies the length of K/V. So, we don't use mask. If your cross attention is standard, you can refer `DecoderCrossAttentionLayer.cu` to understand how to set the parameters for cross attention.

@byshiue OK, i seet what your means and i will try to check this,  thanks!

**Comment by so2bin** [comment]
@byshiue I have checked your idea, thank you, and now i'll close this issue.
