### ISSUE TITLE
May I ask why don't u handle 16 Byte of one K  each thread, just like what u did for V?

### ISSUE THREAD

**Issue by butterluo** [NVIDIA/FasterTransformer#401]
https://github.com/NVIDIA/FasterTransformer/blob/83776ae7fefaabaf4fc75063d2a704fbeb84f2be/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L1281
Why don't u handle 16 Byte of one K  each thread, just like what u did for V? Is there any reason or motivation?

**Comment by byshiue** [comment]
I don't understand your question. If you want to ask why the layouts of K and V are different, that's because in the attention module, we need to transpose the K. If the last dimension of K is sequence length, it lead to un-coalesce memory reading when we hope each thread handle multiple elements.

**Comment by butterluo** [comment]
I see. Thank you!
