### ISSUE TITLE
T5 Decoding forward() num_return_sequences parameter

### ISSUE THREAD

**Issue by cpm0722** [NVIDIA/FasterTransformer#407]
### Environment
Branch/Tag/Commit: `main`
Docker Image Version: `nvcr.io/nvidia/pytorch:21.10-py3`
GPU name: `A100 80GB`
CUDA Driver: `450.80.02`

-----

### Issue

I converted huggingface transformers T5 model to FasterTransformer.
As far as I know, the `generate()` method of `transformers` supports many ***gen_mode***.
- `greedy decoding`
- `contrastive search`
- `multinomial sampling`(a.k.a `sampling`)
- `beam-search decoding`
- `beam-search multinomial sampling`(a.k.a `beam-search sampling`)
- `diverse beam-search decoding`
- `constrained beam-search decoding`

> If you want more detail about ***gen_mode***, you can read a great [post](https://huggingface.co/blog/how-to-generate) written by Hugging Face.  
    Also, the parameters of `generate()`suitable for each ***gen_mode*** are described [here](https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig.decoder_start_token_id).

The question is, Is there any way to get many (not just one) sequences for `sampling`(not `beam-search sampling`) in FasterTransformer? In `transformers`, I can get three sequences with `sampling` with this code.
```python
out = model.generate(**input_token,
                     max_length=32,
                     temperature=0.75,
                     top_p=0.6,
                     do_sample=True,
                     num_return_sequences=3)
```
But, FasterTransformer T5 (`torch.classes.FasterTransformerT5Decoding`) doesn't have `num_return_sequences` parameter.

So I tried to change the [`FTT5 forward()` code](https://github.com/NVIDIA/FasterTransformer/blob/83776ae7fefaabaf4fc75063d2a704fbeb84f2be/examples/pytorch/t5/utils/ft_decoding.py#L448-L488) as below by referring to this [code](https://github.com/huggingface/transformers/blob/accad48e5b4a98302ea396b9f15c5f1c987b6f7f/src/transformers/generation/utils.py#L1376-L1382).

<details><summary> my code </summary><div markdown="1">

```python
def forward(self, input_token, inputs_embeds, beam_size, max_seq_len,
            top_k, top_p, beam_search_diversity_rate = 0.0,
            temperature=1.0, len_penalty=0.0, repetition_penalty=1.0, random_seed=0,
            is_return_output_log_probs=False, is_return_cum_log_probs=False, is_return_cross_attentions=False,
            bad_words_list=None, stop_words_list=None, num_return_sequences=1):

    input_ids = input_token.input_ids.to("cuda").type(torch.int32)
    attention_mask = input_token.attention_mask

    assert num_return_sequences > 0
    if num_return_sequences > 1:
        expanded_return_idx = (torch.arange(input_ids.shape[0]).view(-1, 1).repeat(1, num_return_sequences).view(-1)).to("cuda")
        input_ids = input_ids.index_select(0, expanded_return_idx)
        attention_mask = attention_mask.index_select(0, expanded_return_idx)

    mem_seq_len = torch.sum(attention_mask, dim=1).type(torch.int32).to("cuda")

    ft_encoder_outputs = self.encoder.forward(input_ids, mem_seq_len, inputs_embeds)
    results = self.decoding.forward(beam_size,  # optional, can be None
                                    max_seq_len,
                                    top_k,  # optional, can be None
                                    top_p,  # optional, can be None
                                    beam_search_diversity_rate,  # optional, can be None
                                    temperature,  # optional, can be None
                                    len_penalty,  # optional, can be None
                                    repetition_penalty,  # optional, can be None
                                    random_seed,  # optional, can be None
                                    ft_encoder_outputs,
                                    mem_seq_len,
                                    is_return_output_log_probs,  # optional, can be None
                                    is_return_cum_log_probs,  # optional, can be None
                                    is_return_cross_attentions,  # optional, can be None
                                    bad_words_list, # optional, can be None
                                    stop_words_list, # optional, can be None
                                    )
    ft_decoding_outputs = results.pop(0).reshape([-1, beam_size, max_seq_len])
    ft_decoding_seq_lens = results.pop(0).reshape([-1, beam_size])
    if is_return_output_log_probs:
        ft_output_log_probs = results.pop(0)
    if is_return_cum_log_probs:
        ft_cum_log_probs = results.pop(0)
    if is_return_cross_attentions:
        ft_cross_attentions = results.pop(0)
        return ft_decoding_outputs.cpu().numpy(), ft_decoding_seq_lens.cpu().numpy(), ft_cross_attentions.cpu().numpy()

    return ft_decoding_outputs.cpu().numpy(), ft_decoding_seq_lens.cpu().numpy()
```

</div></details>

But the result is, which I did not expect, when I set `num_return_sequences=3`, it returned **exactly the identical three output sequences**.

I tried `beam-search sampling` with `beam_size>1`, and it worked well. But it is `beam-search sampling`, not vanilla `sampling`.

If there is no way to get many sequences with `sampling`, is this considered in your future plans?

Thank you.

**Comment by byshiue** [comment]
Currently, you can pass same inputs with different random seeds to get different results. This method leads to duplicated computing in encoder. If you hope to optimize it, you can duplicate the results of encoder after encoder.

**Comment by cpm0722** [comment]
Thank you for your advice. It is really helpful for me.

But I still have a few questions about FasterTransformer T5 decoding's parameter.

What is the meaning of `num_expert`, `moe_k`, and `moe_layer_index`?
I can't find any information about these in [FasterTransformer T5 Guide Document](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md#prepare).

**Comment by byshiue** [comment]
They are experimental features and not release yet.

**Comment by cpm0722** [comment]
Thank you. I'll close the issue.
