### ISSUE TITLE
T5-Decoding beam-search error in FP16 (misaligned address /root/FasterTransformer/src/fastertransformer/utils/memory_utils.cu:101)

### ISSUE THREAD

**Issue by cpm0722** [NVIDIA/FasterTransformer#409]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:21.10-py3

### GPU name

A100 (80GB)

### CUDA Driver

450.80.02

### Reproduced Steps

I write a test code for reproduction in my [Repo](https://github.com/cpm0722/FasterTransformer/blob/t5-beam-search-bug/examples/pytorch/t5/).
This code converts `google/t5-base` model to FasterTransformer, and runs beam-search for dummy texts.

This is the following step.

1. `apt-get install git-lfs`
2. `git clone https://github.com/cpm0722/FasterTransformer -b t5-beam-search-bug`
3. `mkdir -p FasterTransformer/build && cd FasterTransformer/build`
4. `git submodule init && git submodule update`
5. `cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..`
6. `make -j12`
7. `cd ../examples/pytorch/t5`
8. `pip install -r requirements.txt`
9. `bash run.sh`

It raises the below error.

```bash
[INFO] WARNING: Exception occurred in dist.init_process_group(backend = 'mpi'). Maybe the process group has been initialized somewhere else.
[INFO] WARNING: Exception occurred in dist.init_process_group(backend = 'mpi'). Maybe the process group has been initialized somewhere else.
[FT][WARNING] Skip NCCL initialization since requested tensor/pipeline parallel sizes are equals to 1.
[WARNING] gemm_config.in is not found; using default GEMM algo
[INFO] WARNING: Exception occurred in dist.init_process_group(backend = 'mpi'). Maybe the process group has been initialized somewhere else.
[FT][WARNING] Skip NCCL initialization since requested tensor/pipeline parallel sizes are equals to 1.
[WARNING] gemm_config.in is not found; using default GEMM algo
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Traceback (most recent call last):
  File "test.py", line 136, in <module>
    output_ids, output_seq_len = model.forward(input_token=input_token,
  File "/root/FasterTransformer/examples/pytorch/t5/utils/ft_decoding.py", line 461, in forward
    results = self.decoding.forward(beam_size,  # optional, can be None
  File "/root/FasterTransformer/examples/pytorch/t5/utils/ft_decoding.py", line 433, in forward
    results = self.decoding.forward(beam_width, max_seq_len,
RuntimeError: [FT][ERROR] CUDA runtime error: misaligned address /root/FasterTransformer/src/fastertransformer/utils/memory_utils.cu:101
```

I test a lot of times and found some conditions of error. This error occurred in only FP16, not FP32. And It should be `beam_size > 1`. If `beam_size` is `1`, any error occurred even if in FP16 mode.

**Comment by byshiue** [comment]
Thank you for the feedback. This bug is fixed in https://github.com/NVIDIA/FasterTransformer/pull/410.

**Comment by cpm0722** [comment]
I'm so glad it helped. I'll close the issue.
