### ISSUE TITLE
Unused parameter in Bloom

### ISSUE THREAD

**Issue by lanking520** [NVIDIA/FasterTransformer#436]
https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/bloom_lambada.py#L241

**Comment by byshiue** [comment]
Sorry. I don't get your question.

**Comment by lanking520** [comment]
There is no default value and nowhere to set this parameter. So essentially passing None

**Comment by byshiue** [comment]
It is defined here https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/utils/bloom.py#L109
