### ISSUE TITLE
Hang with GPT and customized weights

### ISSUE THREAD

**Issue by tangbinh** [NVIDIA/FasterTransformer#444]
I would like to run FT with a model similar to GPT where layer norms don't include affine transforms (e.g `elementwise_affine=False` for `nn.LayerNorm`) and linear layers don't include biases. To make it compatible with the weight format used by `ParallelGptOp`, I manually add some weights and biases to the checkpoint after training with PyTorch (e.g. setting $\gamma$ to 1 and $\beta$ to 0 for `LayerNorm` layers).

However, hangs keep happening during the forward pass when I load the weights with `ParallelGptOp` (see [the attached logs](https://github.com/NVIDIA/FasterTransformer/files/10695159/out.txt)). Do you see any issues here? Would it be possible to add some options to disable biases and affine layers?

**Comment by byshiue** [comment]
Can you provide the scripts you run FT?

**Comment by tangbinh** [comment]
Never mind. It turns out to be an issue during the checkpoint conversion. I fixed it and it seems to be working with `int8_mode = 1` now.

Quick question here. Do [these diagrams](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/images/workflow-of-int8-inference.png) apply for GPT? I think for GPT, `int8_mode = 2` is SmoothQuant, and but can you please provide more information about how `int8_mode = 1` works for GPT? I'm struggling to find information about it, in particular how it should perform in comparison with LLM INT8 and SmoothQuant. Is there any paper describing this `int8_mode = 1`?

**Comment by byshiue** [comment]
`int8_mode = 1` is only quantizing the weight, and dequantizing the weight back to fp16 in the gemm, then using FP16 tensor core.
