### ISSUE TITLE
About GPT INT8 Support

### ISSUE THREAD

**Issue by charliezjw** [NVIDIA/FasterTransformer#456]
In the changelog, there is an item:

> Nov 2022
> Initial support for w8a8 int8 mode with GPT (preview)

I am not able to find this commit in the main branch. How can we get access to that preview?

Thank you very much!

**Comment by byshiue** [comment]
You can find reference on int8_mode in gpt_guide.md

**Comment by charliezjw** [comment]
Thank you very much! @byshiue
