### ISSUE TITLE
Cannot convert Hugging face Japanese GPT to FasterTransformer model

### ISSUE THREAD

**Issue by noppayut** [NVIDIA/FasterTransformer#459]
### Branch/Tag/Commit

main
https://github.com/NVIDIA/FasterTransformer/tree/35989aa49e47f9ce820032ff08807b8a228f0b68

### Docker Image Version

tritonserver_with_ft:22.12 (local build)

### GPU name

T4

### CUDA Driver

525.78.01

### Reproduced Steps

1. Build fastertransformer_backend
```shell
# ref. https://github.com/triton-inference-server/fastertransformer_backend/tree/283286958993a5a03d80be956521770cad1fa2be
git clone https://github.com/triton-inference-server/fastertransformer_backend.git
cd fastertransformer_backend
export WORKSPACE=$(pwd)
export CONTAINER_VERSION=22.12
export TRITON_DOCKER_IMAGE=triton_with_ft:${CONTAINER_VERSION}

python3 docker/create_dockerfile_and_build.py --triton-version 22.12
```
2. `git clone https://github.com/NVIDIA/FasterTransformer.git`
3. `docker run -it --rm --gpus=all --shm-size=4G -v $(pwd):/ft_workspace -p 8888:8888 tritonserver_with_ft:latest bash`
4. `cd /ft_workspace/FasterTransformer/examples/pytorch/gpt/utils/`
5. `python3 huggingface_jp_gpt_convert.py -o /ft_workspace/models/rinna-gpt -i rinna/japanese-gpt-1b -i_g 1`

6. You will see this error.
```
Traceback (most recent call last):
  File "huggingface_jp_gpt_convert.py", line 194, in <module>
    split_and_convert(args)
  File "huggingface_jp_gpt_convert.py", line 105, in split_and_convert
    config["gpt"]["model_name"] = "gpt" if hf_config["_name_or_path"] == '' else hf_config["_name_or_path"]
NameError: name 'config' is not defined
```
Simply define `config` to fix it.

That was the first error. `huggingface_jp_gpt_convert.py` has three issues. Please see the comment.

**Comment by noppayut** [comment]
After resolving the config-not-define bug, you will encounter an error for incorrect variable name. The fix is easy. You just rename `output_dir` to `saved_dir`.
```
Traceback (most recent call last):
  File "huggingface_jp_gpt_convert.py", line 195, in <module>
    split_and_convert(args)
  File "huggingface_jp_gpt_convert.py", line 117, in split_and_convert
    with open(output_dir + "/config.ini", 'w') as configfile:
NameError: name 'output_dir' is not defined
```

Finally, after fixing the variable name, the code will run and exit without problem, but it will produce incorrect names for model weights as well as some weights gone missing. The resulting model names are in `model.h.*` pattern, while the correct one should be `model.layers.*`. Here's the step to reproduce.
```
# continue from steps reported above, you're still inside a container of tritonserver_with_ft:latest
1. `mkdir /ft_workspace/models/configs; cp -r /ft_workspace/fastertransformer_backend/all_models/gpt/* /ft_workspace/models/configs
2. `vim /ft_workspace/models/configs/fastertransformer/config.pbtxt`. Change the `string_value` of `model_checkpoint_path` in line 288 to `"/ft_workspace/models/rinna-gpt/1-gpu"`
3. CUDA_VISIBLE_DEVICES=0 /opt/tritonserver/bin/tritonserver  --model-repository=/ft_workspace/models/configs/
```
You will see the following errors because of the incorrect model name pattern.
```
[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.layers.23.mlp.dense_h_to_4h.bias.0.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.layers.23.mlp.dense_4h_to_h.bias.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.layers.23.attention.query_key_value.weight.0.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.layers.23.attention.dense.weight.0.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.layers.23.mlp.dense_h_to_4h.weight.0.bin cannot be opened, loading model fails! 

(and many more)
```
There are two things to fix.
1. Line 176; Use `state_dict().items()` instead of `named_parameters()`.
2. Even tho you fix 1, some weights are still missing. 
```
[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.wpe.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.wte.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.final_layernorm.bias.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.final_layernorm.weight.bin cannot be opened, loading model fails! 

[FT][WARNING] file /ft_workspace/models/rinna-gpt/1-gpu//model.wte.bin cannot be opened, loading model fails!
```
To fix this. Line 24; `from transformers import GPT2LMHeadModel` instead of `GPT2Model`. Also change line 120 to use `GPT2LMHeadModel` instead. `GPT2Model` doesn't load those weights needed for FasterTransformer model.

**Comment by byshiue** [comment]
It is welcome to send a fix PR, thank you.

**Comment by noppayut** [comment]
Thanks! Btw, I'm not sure why you need `FasterTransformer/examples/pytorch/gpt/utils/huggingface_jp_gpt_convert.py` 
 when you have `huggingface_gpt_convert.py`. If it's for converting Japanese models from https://huggingface.co/rinna,  `huggingface_gpt_convert.py` can convert them just fine.

**Comment by byshiue** [comment]
> Thanks! Btw, I'm not sure why you need `FasterTransformer/examples/pytorch/gpt/utils/huggingface_jp_gpt_convert.py` when you have `huggingface_gpt_convert.py`. If it's for converting Japanese models from https://huggingface.co/rinna, `huggingface_gpt_convert.py` works just fine.

I remember there are some differences between them. But if you can convert the checkpoint by `huggingface_gpt_convert.py`, you can also update it in document.
