### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by luliyucoordinate** [NVIDIA/FasterTransformer#468]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

A100

### CUDA Driver

470.57

### Reproduced Steps

An `invalid argument` error is reported when running the GPT Example program (bloom 175b)

```shell
mpirun -n 8 ./bin/multi_gpu_gpt_example
```

The location of the error is cudaH2Dcpy.

**Comment by byshiue** [comment]
Please provide the end to end reproduced steps.

**Comment by luliyucoordinate** [comment]
https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/models/multi_gpu_gpt/ParallelGptWeight.cc#L129

When vocab_size_ * hidden_units_ > INT_MAX integer overflow appears.

```
[bloom_175B]
head_num=112
size_per_head=128
vocab_size=250880
decoder_layers=70
start_id=1
end_id=2
inter_size=57344
model_variant=bloom-pre
```
When testing Bloom 175b, hidden_units_ = 14336, vocab_size_=250880.vocab_size_ * hidden_units_=3,596,615,680
