### ISSUE TITLE
Support BF16 precision in BLOOM checkpoint conversion 

### ISSUE THREAD

**Issue by vdabravolski** [NVIDIA/FasterTransformer#479]
### Branch/Tag/Commit

main

### Docker Image Version

latest

### GPU name

A100

### CUDA Driver

latst

### Reproduced Steps

```shell
Currently, BLOOM checkpoint conversion script (from HF checkpoint to FT checkpoint) only supports two target precisions: FP16 and FP32. It would be good to also support BF16 as target precision. BF16 is becoming more popular as it provides better model accuracy with the same memory footprint compared to FP16.

Reference to checkpoint conversion script: https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/utils/huggingface_bloom_convert.py
```

**Comment by mickaelseznec** [comment]
Hi!

The precision mentioned in the scripts only refers to how weights are stored on disk. At runtime, bf16 is [already supported](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md#supported-features).

Having weights stored in bf16 on disk will only reduce disk usage, is that what you're suggesting?

Thanks!
Mickaël

**Comment by vdabravolski** [comment]
Hi Michael!

> Having weights stored in bf16 on disk will only reduce disk usage, is that what you're suggesting?
Yes, exactly. Right now I run my model in BF16 already. But for this, i have to store in Object Storage service weights in FP32 (100s of GBs). These FP32 weights then need to be downloaded to Triton endpoint at a startup time which takes minutes. I'd like to store weights in BF16 to reduce time to download weights and  whereby to speed up endpoint startup time.

**Comment by mickaelseznec** [comment]
I understand, can you try to apply [this patch](https://gist.github.com/mickaelseznec/8c6e3e22c3ee6b16aa6ac4433cf5226f)? I'll make it available in the next release

**Comment by vdabravolski** [comment]
Thanks for the patch, MIckael! Closing the issue now.
