### ISSUE TITLE
Maybe there is a bug in custom AllReduce?

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/FasterTransformer#480]
the code is: https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/kernels/custom_ar_kernels.cu#L372
In `invokeOneOrTwoShotAllReduceKernel`： 
```cpp
if (elts_total <= DEFALUT_ALGO_AR_SIZE_THRESHOLD) {
        kernel_algo = 0;
    }
```
May need to change to? 
```cpp
if (elts_total * sizeof(T) <= DEFALUT_ALGO_AR_SIZE_THRESHOLD) {
        kernel_algo = 0;
    }
```

**Comment by PerkzZheng** [comment]
thanks. we will fix it soon.

**Comment by byshiue** [comment]
Fixed in https://github.com/NVIDIA/FasterTransformer/commit/f7a4418ac874d751fb5d2540481a6d5b5bcdbe25
