### ISSUE TITLE
Support for sentence-transformer models?

### ISSUE THREAD

**Issue by zoltan-fedor** [NVIDIA/FasterTransformer#486]
### Branch/Tag/Commit

main

### Docker Image Version

n/a

### GPU name

n/a

### CUDA Driver

n/a

### Reproduced Steps

I am wondering if we support the sentence-transformer models (https://huggingface.co/sentence-transformers) like https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-dot-v1?

**Comment by byshiue** [comment]
Hi, zoltan. FT does not support this model yet.

**Comment by zoltan-fedor** [comment]
Thanks for confirming!
