### ISSUE TITLE
convert the SmoothQuant model for w8a8 inference in FT failed

### ISSUE THREAD

**Issue by Anychnn** [NVIDIA/FasterTransformer#490]
convert the SmoothQuant model for w8a8 inference in FT failed when i use int8_mode=2

Traceback (most recent call last):
  File "examples/pytorch/gpt/utils/huggingface_opt_convert.py", line 328, in <module>
    split_and_convert(args)
  File "examples/pytorch/gpt/utils/huggingface_opt_convert.py", line 178, in split_and_convert
    capture_dict[key + ".weight"] = (values["input"], values["output"])
IndexError: too many indices for tensor of dimension 1

The scale.pt is generated by  the repo: https://github.com/mit-han-lab/smoothquant, which is mentioned in the gpt_guide.md.
It seems the format of scale.pt file doesn't match FasterTransformer?

**Comment by JianchaoTan** [comment]
> convert the SmoothQuant model for w8a8 inference in FT failed when i use int8_mode=2
> 
> Traceback (most recent call last): File "examples/pytorch/gpt/utils/huggingface_opt_convert.py", line 328, in split_and_convert(args) File "examples/pytorch/gpt/utils/huggingface_opt_convert.py", line 178, in split_and_convert capture_dict[key + ".weight"] = (values["input"], values["output"]) IndexError: too many indices for tensor of dimension 1
> 
> The scale.pt is generated by the repo: https://github.com/mit-han-lab/smoothquant, which is mentioned in the gpt_guide.md. It seems the format of scale.pt file doesn't match FasterTransformer?

Did you solve this problem?  Thanks.
