### ISSUE TITLE
build  FasterTransformer fail 

### ISSUE THREAD

**Issue by shiqingzhangCSU** [NVIDIA/FasterTransformer#493]
I use asterTransformer 5.3，and build it failed.
gcc version： 5.4
GPU： A30
I want build with PyTorch
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=OFF ..
make -j12

and I find some problems below：
<img width="700" alt="1678871717210" src="https://user-images.githubusercontent.com/44834482/225262629-940258b5-e666-46c7-8b2c-b9863853c2c7.png">
![image](https://user-images.githubusercontent.com/44834482/225262769-f54cd6e2-bf92-42a0-a740-afa690c4fda8.png)
Hope to get your help！

**Comment by byshiue** [comment]
Do you use the pytorch container recommended in document?

**Comment by shiqingzhangCSU** [comment]
> Do you use the pytorch container recommended in document?
I'm using environment which python=3.7.12 torch=1.12.1.

**Comment by byshiue** [comment]
> > Do you use the pytorch container recommended in document?
> > I'm using environment which python=3.7.12 torch=1.12.1.

I don't ask the version, but ask the docker image you use.

**Comment by shiqingzhangCSU** [comment]
> > > Do you use the pytorch container recommended in document?
> > > I'm using environment which python=3.7.12 torch=1.12.1.
> 
> I don't ask the version, but ask the docker image you use.

Does nvidia-docker have to be used?If I have to use it, I'll try it later. Thank you very much！
