### ISSUE TITLE
lib/libth_bert.so: undefined symbol

### ISSUE THREAD

**Issue by pangsg** [NVIDIA/FasterTransformer#494]
I tried to run bert_example.py but a error raised

`lib/libth_bert.so: undefined symbol: _ZN17fastertransformer13cublasAlgoMapC1ESsSs`

I have build the FT with python bindings
Here is my build scripts:
```
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..
make -j12
```

my env info:
```
GPU: A100
CUDA: 11.6
python:3.8.10
pytorch:1.12.1
fastertransformer: v5.0
```

**Comment by pangsg** [comment]
BTW, i couldn't use the provided docker image because of the policy of my company

**Comment by byshiue** [comment]
There are some issues in the environment settings. You can refer the recommended docker image to help debugging.

**Comment by pangsg** [comment]
Because of the rule of our company, I can't download the image from nvcr.io. Could plz provide some advice for debug?

**Comment by byshiue** [comment]
It is a undefined symbol issue due to environment issue, which depends on your environment settings and we are hard to provide suggestion. 

You can try to check the cmake file and the make file generated by cmake, making sure they have linked successfully.

**Comment by pangsg** [comment]
Thanks for your advice. I have checked the built log, nothing failed in the log. Could u plz provide the requirements.txt?

**Comment by pangsg** [comment]
All Fixed.Thansk

**Comment by Siyuan011** [comment]
Hi, how do you fix it? I necountered the same problem. 
Here is my config:
GPU: A100
CUDA: 11.3
python:3.8.5
pytorch:1.12.1

**Comment by Siyuan011** [comment]
yes of course. I followed gpt_guide

**Comment by pangsg** [comment]
> yes of course. I followed gpt_guide

hmm, i followed the guide and fixed the bug. The git is necessary
