### ISSUE TITLE
The whole vit network as a trt plugin operator?

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/FasterTransformer#497]
Hi. 
I only want to use this part of the code vit plugin, what should I do.

**Comment by byshiue** [comment]
Sorry. I don't get you point.

**Comment by ywfwyht** [comment]
@byshiue  Sorry, my language expression is as bad as English.
I have two questions. The first one is about the vit tensorrt_plugin, the whole vit network as a plugin or split vit into multiple plugin operators?   The second is that I only want to reuse the vit tensorrt_plugin. How can I modify the code for myself。

**Comment by byshiue** [comment]
1. FT encapsulates whole vit network as a plugin. 
2. You can refer the example to understand how to use the vit tensorrt plugin.
