### ISSUE TITLE
What changes in the output of a conversion if multiple DSM are set?

### ISSUE THREAD

**Issue by Chris113113** [NVIDIA/FasterTransformer#507]
Following the T5 conversion guide I see:

"By default, -DSM is set by 70, 75, 80 and 86. When users set more kinds of -DSM, it requires longer time to compile. So, we suggest setting the -DSM for the device you use only. Here, we use xx as an example due to convenience."

Does this mean that we can build FasterTransformer for multiple DSM, convert a model, and then run it on GPUs using any of those DSM architectures and expect the same results?

How does the model use the proper instructions at runtime? Is that done by the fastertransformer_backend?

**Comment by byshiue** [comment]
> Does this mean that we can build FasterTransformer for multiple DSM, convert a model, and then run it on GPUs using any of those DSM architectures and expect the same results?

Yes, you can build once and run on different GPUs. 

> How does the model use the proper instructions at runtime? Is that done by the fastertransformer_backend?

It is handled by cuda driver. We don't consider such problem in application level.
