### ISSUE TITLE
What does "mem_seq_len" mean in bert_example.py

### ISSUE THREAD

**Issue by pangsg** [NVIDIA/FasterTransformer#508]
I found a variable named "mem_seq_len" in bert_example.py, does it mean the true seqlen of input for bert model?

**Comment by byshiue** [comment]
> I found a variable named "mem_seq_len" in bert_example.py, does it mean the true seqlen of input for bert model?

Right. It is sequence lengths of inputs.

**Comment by pangsg** [comment]
Thanks! I wonder that fastertransformer.Bert can accept the dynamic batch_size?

**Comment by byshiue** [comment]
Yes. It supports dynamic batch size.

**Comment by pangsg** [comment]
Thanks a lot！



发自我的iPhone


------------------ Original ------------------
From: byshiue ***@***.***&gt;
Date: Mon,Mar 20,2023 11:39 AM
To: NVIDIA/FasterTransformer ***@***.***&gt;
Cc: nlp-pang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [NVIDIA/FasterTransformer] What does "mem_seq_len" mean inbert_example.py (Issue #508)





 
Yes. It supports dynamic batch size.

**Comment by pangsg** [comment]
Fixed it.Thanks for help.
