### ISSUE TITLE
Rouge accuarcy of Large-Scale OPT weight-only quantized models heavily drop

### ISSUE THREAD

**Issue by lippman1125** [NVIDIA/FasterTransformer#510]
### Branch/Tag/Commit

tag 5.3

### Docker Image Version

custom docker with py3.9+torch1.3+huggingface4.26.1

### GPU name

A100

### CUDA Driver

470.103.01

### Reproduced Steps

```shell
1. cd FasterTransformer
2. mpirun -n 8 python3 examples/pytorch/gpt/opt_summarization.py --summarize --max_ite 20 --ft_model_location ../nlp-models-fp32/ft/test/opt-1.3b/ --hf_model_name ../opt-1.3b --lib_path ./build/lib/libth_transformer.so --cache_path ../ccdv_cached/  --tensor_para_size 8 --data_type fp16 --int8_mode 1
```

**Comment by lkm2835** [comment]
Can you try `huggingface_opt_convert.py` `-weight_data_type fp16`?

**Comment by byshiue** [comment]
Can you provide the reproduced steps, including how you building docker, how converting model and how you build the project.

**Comment by lippman1125** [comment]
@lkm2835 @byshiue 
Build:
`
cd FasterTransformer && mkdir build && cd build
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
make -j 36
`
Model:
![facebook/opt-1.3b](https://huggingface.co/facebook/opt-1.3b)

Convert:
`
python3 examples/pytorch/gpt/utils/huggingface_opt_convert.py -i ../opt-1.3b -o ../nlp-models-fp16/ft/test/opt-1.3b/ -i_g 8  -weight_data_type fp16
`

Test:
`mpirun -n 8 python3 examples/pytorch/gpt/opt_summarization.py --summarize --max_ite 20 --ft_model_location ../nlp-models-fp16/ft/test/opt-1.3b/ --hf_model_name ../opt-1.3b --lib_path ./build/lib/libth_transformer.so --cache_path ../ccdv_cached/  --tensor_para_size 8 --data_type fp16 --int8_mode 1 --weights_data_type fp16`

Result:
Faster Transformers (total latency: 8.086781 sec)
rouge1 : 0.5556526976355618
rouge2 : 0.0
rougeL : 0.5586363472357527
rougeLsum : 0.5586363472357527

**Comment by lippman1125** [comment]
@lkm2835 opt-125m int8_mode is ok, It's weird.

**Comment by byshiue** [comment]
Thank you for the reproduced steps. We will take a look.

**Comment by rhenry-nv** [comment]
@lippman1125 I cannot reproduce this. I am using `nvcr.io/nvidia/pytorch:22.09-py3` when building against 5.3 tag and `nvcr.io/nvidia/pytorch:23.02-py3` when building against main.

From the build directory of FT inside the container, I run:
```
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON -DBUILD_CUTLASS_MOE=OFF -DBUILD_CUTLASS_MIXED_GEMM=OFF -DENABLE_FP8=OFF .. && make -j && pip install -r ../examples/pytorch/gpt/requirement.txt
```

And I run opt summarization using:
```
mpirun -n 8 python3 ../examples/pytorch/gpt/opt_summarization.py --summarize --max_ite 20 --ft_model_location ../models/opt-1.3b/ --hf_model_name facebook/opt-1.3b --cache_path ../models/datasets/opt_summarization/ccdv/  --tensor_para_size 8 --data_type fp16 --int8_mode 1 --weights_data_type fp16
```

Can you try using one of these containers and let me know if the issue still persists?

**Comment by lippman1125** [comment]
@byshiue something wrong with my local environment, already fixed.
