### ISSUE TITLE
Can I use cross-attention in gpt example?

### ISSUE THREAD

**Issue by pangsg** [NVIDIA/FasterTransformer#513]
Hi, sorry for lots of questions.
If i want to use cross-attention in TransformerLayer，what should i do to set it up?  I found that the foward function in gpt model doesn't support Cross-attention.

**Comment by byshiue** [comment]
You need to modify the source codes of `ParallelGptDecoding.cc` and the transformer layers classes to add cross attention.

**Comment by byshiue** [comment]
Right.

**Comment by pangsg** [comment]
Thanks for your help!

**Comment by pangsg** [comment]
> 



> You need to modify the source codes of `ParallelGptDecoding.cc` and the transformer layers classes to add cross attention.

Do you mean `ParallelGptDecoder.cc` ? I couldn't find the `ParallelGptDecoding.cc`

**Comment by byshiue** [comment]
Sorry, I mean `ParallelGpt.cc`. I have fixed it.

**Comment by pangsg** [comment]
> Sorry, I mean `ParallelGpt.cc`. I have fixed it.

Got it.Thanks a lot.
