### ISSUE TITLE
How to convert vit weights from pytorch to fastertransformer format for plugin use ?

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/FasterTransformer#519]
Hi.
How to convert my own vit weights from pytorch to fastertransformer format for plugin use, 
Is there any sample code available for reference？

**Comment by byshiue** [comment]
Here are some examples https://github.com/NVIDIA/FasterTransformer/tree/main/examples/tensorrt/vit, hoping they are helpful.

**Comment by ywfwyht** [comment]
@byshiue Hi.
Line 30 in https://github.com/NVIDIA/FasterTransformer/tree/main/examples/tensorrt/vit/infer_visiontransformer_plugin.py
`from models.modeling import VisionTransformer, CONFIGS`，Where is the models folder ？Could you provide it to me?

**Comment by ywfwyht** [comment]
@byshiue Hi.
Line 30 in https://github.com/NVIDIA/FasterTransformer/tree/main/examples/tensorrt/vit/infer_visiontransformer_plugin.py
`from models.modeling import VisionTransformer, CONFIGS`，Where is the models folder ？Could you provide it to me?

**Comment by byshiue** [comment]
These are files of vit submodule in `examples/pytorch/vit/ViT-quantization/ViT-pytorch`

**Comment by ywfwyht** [comment]
> These are files of vit submodule in `examples/pytorch/vit/ViT-quantization/ViT-pytorch`

Thanks very much.

**Comment by ywfwyht** [comment]
@byshiue bro. 
How to infer plugin shared library with C++ api.

**Comment by byshiue** [comment]
This should be a question of trt directly. You can refer this example https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/old/samples/AppPluginDynamicShape.cpp and ask in the repo if you have more question.

**Comment by proevgenii** [comment]
Did u find any way to convert pytorch weights?
I have similar question, about how to apply quantization to my finetuned ViT model ?

**Comment by ywfwyht** [comment]
> Did u find any way to convert pytorch weights? I have similar question, about how to apply quantization to my finetuned ViT model ?

You can refer to `FasterTransformer/examples/pytorch/vit/VisionTransformerWeightLoader.py`

**Comment by proevgenii** [comment]
@ywfwyht, sorry for very slow response 
But here `FasterTransformer/examples/pytorch/vit/VisionTransformerWeightLoader.py` 
in method `def load_weights(self, weight_path:str):` there is a condition: 
```
if suffix != 'npz':
            print("Unsupported weight file: Unrecognized format %s " % suffix)
```
1. So as I understand it wants to get `.npz' file as input?
 but my goal is to get this file to load FasterTransformer ViT architecture
2. Here `VisionTransformerWeightLoader.py` I can't find any method to convert pytorch weights to FasterTransformer format

Now I use hardcode to modify my torch weights dict, to satisfy requirments of this https://github.com/NVIDIA/FasterTransformer/blob/afdf9a9eb86f15363c0249117d166d6b45dbb371/examples/pytorch/vit/ViT-quantization/vit_int8.py#L399
But it seems that I missed something
