### ISSUE TITLE
`generic_activation` is using too many registers

### ISSUE THREAD

**Issue by lzhangzz** [NVIDIA/FasterTransformer#520]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/tritonserver:22.12-py3

### GPU name

A100

### CUDA Driver

515.86.01

### Reproduced Steps

I'm trying to implement the LLaMA model which requires `generic_activation` in its FFN. However, I'm getting "CUDA runtime error: too many resources requested for launch" for the kernel, which usually means launching the kernel using the configuration is taking too many registers than the SM has.

I commented out some of the branches I don't need and it works now. Using templated dispatching instead of runtime branching maybe helpful in reducing the register pressure here.

**Comment by michaelroyzen** [comment]
So you got it working for LLaMa @lzhangzz? Do you have example code that I could refer to?
