### ISSUE TITLE
update of performance data

### ISSUE THREAD

**Issue by jinluyang** [NVIDIA/FasterTransformer#523]
Hi, I found the performance data in gpt_guide.md a little old (2021). Maybe the master branch can achieve better than that? Particularly I used the multi_gpu_gpt_example to test gpt3-175B, and found the latency is 362ms on 8 A100s, with batchsize=8, input seqlen=128, output seqlen=8. That is much lower than 749ms. Wondering if there is any update about performance data, or if I didn't test it properly? 
Or maybe someone's planning to update all the documents?

**Comment by byshiue** [comment]
Do you use different random ids for different batches?

**Comment by jinluyang** [comment]
Sorry for the delay, because other people were using the A100 and I couldn't test it once more. I used same start ids for 8 sentences in one batch. And I tested just this one batch. I used "3,3,3,3,...." as input. Now that I noticed the script at examples/pytorch/gpt/utils/generate_start_ids.py, I will use new random ids to test when the GPU is available. But I still don't know why this will affect the performance.

**Comment by byshiue** [comment]
> Sorry for the delay, because other people were using the A100 and I couldn't test it once more. I used same start ids for 8 sentences in one batch. And I tested just this one batch. I used "3,3,3,3,...." as input. Now that I noticed the script at examples/pytorch/gpt/utils/generate_start_ids.py, I will use new random ids to test when the GPU is available. But I still don't know why this will affect the performance.

In GPT, we separate the inference into two stage. The first stage handles the input, and the second stage generates the response. 
In first stage, if the ids of different sentences in one batch are same, they will generate same results. So, we can remove the duplicated inputs and save the computing cost.

**Comment by jinluyang** [comment]
Hello，here are some of my latest test results. Indeed a little faster.
<html>
<body>
<style type="text/css"></style>

Batch_size | Input Seqlen | Output Seqlen | RT
-- | -- | -- | --
8 | 128 | 8 | 585.17ms
4 | 128 | 8 | 443ms
2 | 128 | 8 | 380.55ms


</body>
</html>

**Comment by jinluyang** [comment]
![image](https://user-images.githubusercontent.com/15670327/229398453-7249a2c8-9a8f-48f3-8757-e40d0db71270.png)
