### ISSUE TITLE
Unexpectedly bad scaling on inter_size in gpt model

### ISSUE THREAD

**Issue by chessgecko** [NVIDIA/FasterTransformer#552]
### Branch/Tag/Commit

main

### Docker Image Version

22.09-py3

### GPU name

A100 80gb

### CUDA Driver

470.57.02

### Reproduced Steps

I was investigating the effects of increasing inter_size on the inference speed for the below configs and found that to match a 2x increase in inter_size you need to increase the batch_size from 1 to 128, i.e

```shell
[ft_instance_hyperparameter]
max_batch_size=1 ; Use for allocate the buffer
max_seq_len=512 ; The sequence length of position embedding table, should move to model hyper-parameter
beam_width=1 ; beam width for beam search
top_k=1 ; k value for top k sampling
top_p=0 ; p value for top p sampling
temperature=1.0 ; Use for sampling
repetition_penalty=1.0 ; Use for sampling
presence_penalty=0.0  ; Only one of repetition_penalty and presence_penalty are allowed.
tensor_para_size=1
pipeline_para_size=1
data_type=fp16
sparse=0
int8_mode=0
enable_custom_all_reduce=0

model_name=cust_big
; model_name=cust_small

model_dir=../models/megatron-models/c-model/345m/1-gpu/
len_penalty=0.0
beam_search_diversity_rate=0.0
shared_contexts_ratio=1.0

[request]
request_batch_size=1    ; determine by the request
request_output_len=256   ; determine by the request
return_log_probs=false  ; return the output log probs and cumulative log probs.
context_log_probs=false ; include input contexts in the cumulative log probability computation.
remove_padding=true
context_embeddings=true

[cust_big]
head_num=32
size_per_head=128
vocab_size=51256
decoder_layers=32
start_id=1
end_id=1
inter_size=65536

[cust_small]
head_num=32
size_per_head=128
vocab_size=51256
decoder_layers=32
start_id=1
end_id=1
inter_size=32768
```

running: ./bin/multi_gpu_gpt_example
gemm: ./bin/gpt_gemm 1 1 512 32 128 65536 51256 1 1 0

When I run cust_big with request and global batch sizes = 1 I get
```shell
[INFO] request_batch_size 1 beam_width 1 head_num 32 size_per_head 128 total_output_len 264 decoder_layers 32 vocab_size 51256 FT-CPP-decoding-beamsearch-time 6218.33 ms
```

When I run cust_small with request and global batch sizes = 1 I get
```shell
[INFO] request_batch_size 1 beam_width 1 head_num 32 size_per_head 128 total_output_len 264 decoder_layers 32 vocab_size 51256 FT-CPP-decoding-beamsearch-time 3804.91 ms
```

when I run cust_small with request and global batch sizes = 128 I get
```shell
[INFO] request_batch_size 128 beam_width 1 head_num 32 size_per_head 128 total_output_len 264 decoder_layers 32 vocab_size 51256 FT-CPP-decoding-beamsearch-time 6234.36 ms
```

I'm curious if this is expected or if there is an issue in the ffn layer. I don't know quite enough to tell from poking through it myself, but naively I expected increasing the inter_size to scale about the same as increasing the batch size, or at least not 64x worse at this model size.

**Comment by byshiue** [comment]
We cannot give any comment because there is no enough information. But comparing the inter size and batch size by such way does not make sense because they work on different dimension in GEMM.

**Comment by chessgecko** [comment]
I’m happy to provide any additional information that would be useful if there is interest in investigating, there are no trained weights it was theoretical.

I guess I wouldn’t expect a perfect correlation between required flops and inference speed given cache hits/misses etc, but I’m just a little surprised you can get over 64x the flops by increasing the batch size vs the inter_size

**Comment by byshiue** [comment]
You can use cublas to measure the performance of these kinds of GEMM you are interested.

**Comment by chessgecko** [comment]
I’m quite interested, do you have any pointers on where to start/examples? I’m hoping this is relatively simple since inter_size only touches the two linear layers
