### ISSUE TITLE
GPT decoder implementation issue

### ISSUE THREAD

**Issue by sungmin-yun** [NVIDIA/FasterTransformer#555]
Hi,

The line number 298 in GptJDecoder.cc:

        TensorMap self_attention_output_tensors{
            {"hidden_features", Tensor{MEMORY_GPU, data_type, {local_batch_size, hidden_units_}, self_attn_output_}},
            {"key_cache", Tensor{MEMORY_GPU, data_type, self_k_cache_size, k_cache.getPtrWithOffset(cache_offset)}},
            {"value_cache", Tensor{MEMORY_GPU, data_type, self_v_cache_size, v_cache.getPtrWithOffset(cache_offset)}}};

        self_attention_layer_->forward(&self_attention_output_tensors,
                                       &self_attention_input_tensors,
                                       &gpt_decoder_layer_weight->at(l).self_attention_weights);

        TensorMap ffn_input_tensors(
            {{"ffn_input", Tensor{MEMORY_GPU, data_type, {local_batch_size, hidden_units_}, decoder_normed_input_}}});
        TensorMap ffn_output_tensors(
            {{"ffn_output", Tensor{MEMORY_GPU, data_type, {local_batch_size, hidden_units_}, ffn_output_}}});
        ffn_layer_->forward(&ffn_output_tensors, &ffn_input_tensors, &gpt_decoder_layer_weight->at(l).ffn_weights);

Input tensor of FFN should be the output of attention layer, which is "self_attn_output_".

But in the code, input tensor of FFN is "decoder_normed_input_" , which is the output of the first normalized layer in the decoder.

Is this an implementation mistake?

If so, it may not affect the computing performance, but the output of decoder may not be what you intended.

**Comment by byshiue** [comment]
This is model architecture of GPT-J, there is no mistake.

**Comment by sungmin-yun** [comment]
Okay. Thankyou!
