### ISSUE TITLE
build error in cublasWrapper.cc 

### ISSUE THREAD

**Issue by Jervint** [NVIDIA/FasterTransformer#556]
### Branch/Tag/Commit

main

### Docker Image Version

cuda-11.3

### GPU name

t4,a100

### CUDA Driver

cuda-11.3

### Reproduced Steps

```shell
When building faster-transformer with cuda-11.3, I will get error like that:
"""
/code/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc: In member function ‘void fastertransformer::cublasMMWrapper::_Int8Gemm(int, int, int, const int8_t*, int, const int8_t*, int, void*, int, const void*, int, bool)’:
/code/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc:1019:34: error: ‘CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST’ was not declared in this scope
             per_column_scaling ? CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST : CUBLASLT_POINTER_MODE_DEVICE;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/code/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc:1019:34: note: suggested alternative: ‘CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_ZERO’
             per_column_scaling ? CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST : CUBLASLT_POINTER_MODE_DEVICE;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_ZERO
"""
it caused by missing symbol 'CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST' in cublasLt.h
According CUDA's release note, CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST has been added in cublasLt in version 11.4.2;
the related code have been added to FasterTransformer in https://github.com/NVIDIA/FasterTransformer/commit/b672f49e256ba7a2d4fc9691d270b60b7fc1a2ff#diff-d2dca7ee43714aee606adb6d18859b598580a7c595faf731884aec0fa46c5fef
```

**Comment by xshaun** [comment]
also met the issue. I found the cublasLt.h in cuda11.3 had not support `CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST`, but cuda11.6 supports well, and we can find its definition in /??/cuda/include/cublasLt.h:
```
/** alpha pointer targets an array in device memory, beta is a single value in host memory. */
CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST = 4,  
```

**Comment by byshiue** [comment]
Can you share the docker image you use to reproduce this issue? 
In FT, we have a check here https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987 to make sure the codes are only compiled after cublas > 11.4.0.2

**Comment by xshaun** [comment]
> Can you share the docker image you use to reproduce this issue?
> In FT, we have a check here https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987 to make sure the codes are only compiled after cublas > 11.4.0.2

Thanks @byshiue for your reply and I can reproduce this issue in a docker container (ubuntu20.04) where  I manually install cuda-11.3 following the [official guide](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#:~:text=Go%20to%3A%20NVIDIA%20cuDNN%20home%20page.%20Click%20Download.,Select%20the%20cuDNN%20version%20you%20want%20to%20install.). If installed cuda-11.7, it works well. I do not set `CUBLAS_VERSION` variable explicitly  and I am not sure if the program can find the `CUBLAS_VERSION` correctly, for example by nvcc, before `cublasMMWrapper.cc#L987`?

**Comment by byshiue** [comment]
The macro is defined in `cublas_api.h`.

**Comment by xshaun** [comment]
Haha, found it. 

the `CUBLAS_VERSION ` is defined to **110402** in `cublas_api.h`, shown as:
```
  85 #define CUBLAS_VER_MAJOR 11
  86 #define CUBLAS_VER_MINOR 4
  87 #define CUBLAS_VER_PATCH 2
  88 #define CUBLAS_VER_BUILD 10064
  89 #define CUBLAS_VERSION  (CUBLAS_VER_MAJOR * 1000 + \                                                                                                                
  90                          CUBLAS_VER_MINOR *  100 + \
  91                          CUBLAS_VER_PATCH)
```

at [https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987), the condition is <=`11402 `
```
#if (CUBLAS_VERSION) <= 11402
    FT_CHECK_WITH_INFO(false, "CUBLAS version too low.");
#else
```

**Comment by byshiue** [comment]
> Haha, found it.
> 
> the `CUBLAS_VERSION ` is defined to **110402** in `cublas_api.h`, shown as:
> 
> ```
>   85 #define CUBLAS_VER_MAJOR 11
>   86 #define CUBLAS_VER_MINOR 4
>   87 #define CUBLAS_VER_PATCH 2
>   88 #define CUBLAS_VER_BUILD 10064
>   89 #define CUBLAS_VERSION  (CUBLAS_VER_MAJOR * 1000 + \                                                                                                                
>   90                          CUBLAS_VER_MINOR *  100 + \
>   91                          CUBLAS_VER_PATCH)
> ```
> 
> at https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987, the condition is <=`11402 `
> 
> ```
> #if (CUBLAS_VERSION) <= 11402
>     FT_CHECK_WITH_INFO(false, "CUBLAS version too low.");
> #else
> ```

CUBLAS_VER_MAJOR * 1000 is 11000, but not 110000.

**Comment by xshaun** [comment]
> > Haha, found it.
> > the `CUBLAS_VERSION ` is defined to **110402** in `cublas_api.h`, shown as:
> > ```
> >   85 #define CUBLAS_VER_MAJOR 11
> >   86 #define CUBLAS_VER_MINOR 4
> >   87 #define CUBLAS_VER_PATCH 2
> >   88 #define CUBLAS_VER_BUILD 10064
> >   89 #define CUBLAS_VERSION  (CUBLAS_VER_MAJOR * 1000 + \                                                                                                                
> >   90                          CUBLAS_VER_MINOR *  100 + \
> >   91                          CUBLAS_VER_PATCH)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > at https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/utils/cublasMMWrapper.cc#L987, the condition is <=`11402 `
> > ```
> > #if (CUBLAS_VERSION) <= 11402
> >     FT_CHECK_WITH_INFO(false, "CUBLAS version too low.");
> > #else
> > ```
> 
> CUBLAS_VER_MAJOR * 1000 is 11000, but not 110000.
😂!! sorry for the stupid math error. 


I reproduced it again and found that the CUBLAS_VERSION does not also meets **<=11402** in cuda-11.3.
`nvcc --version`  command gives
```
cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```
but, `cat /usr/local/cuda/include/cublas_api.h | grep -n10 CUBLAS_VERSION` looks like
```
85 #define CUBLAS_VER_MAJOR 11
86 #define CUBLAS_VER_MINOR 5
87 #define CUBLAS_VER_PATCH 1
88 #define CUBLAS_VER_BUILD 109
89 #define CUBLAS_VERSION  (CUBLAS_VER_MAJOR * 1000 + \                                                                                                                
90                          CUBLAS_VER_MINOR *  100 + \
91                          CUBLAS_VER_PATCH)
```

**Comment by byshiue** [comment]
You should check do you install the cublas correctly because the feature is added in cublas 11.4, which is shown here https://docs.nvidia.com/cuda/archive/11.5.1/cuda-toolkit-release-notes/index.html#cublas-11.4.2.

**Comment by Jervint** [comment]
> You should check do you install the cublas correctly because the feature is added in cublas 11.4, which is shown here https://docs.nvidia.com/cuda/archive/11.5.1/cuda-toolkit-release-notes/index.html#cublas-11.4.2.

the title 'cublas-11.4.2' may only means the update info of cublas in cuda-11.4.2. The cublas's version in cuda-11.4.2  is 11601 , so the macro doesn't work.
![image](https://user-images.githubusercontent.com/20737207/232666860-34cac334-d032-4830-971c-8c17f8e5536b.png)

**Comment by byshiue** [comment]
Thank you for the feedback. You are right. That means the release note of cuda 11.4, but not cublas 11.4.2. 

We have checked the version and change it to 11.6.1 in this commit https://github.com/NVIDIA/FasterTransformer/commit/a6ef7af16c094ac2bb55a3b821dc85d0f0240e08.
