### ISSUE TITLE
How to use vit-Plugin Shared Libraries?

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/FasterTransformer#559]
Hi. 
Now , I added a hybrid layer to my Vit model. So how to export a complete engine with onnx file(include hybrid layer) and vit-plugin.so file.

**Comment by ywfwyht** [comment]
> Create a dummy node(transformer) in your onnx, align your vit impl with FasterTransformer ViT, maybe modify current repo.
@lix19937 
Thanks for your reply, Do you have a reference example？

**Comment by ywfwyht** [comment]
@lix19937 Please, Help me see what kind of mistake this is？
```
ERROR: 3: [executionContext.cpp::resolveSlots::1541] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::1541, condition: allInputDimensionsSpecified(routine)
)
ERROR: 3: [executionContext.cpp::resolveSlots::1541] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::1541, condition: allInputDimensionsSpecified(routine)
)
ERROR: 2: [executionContext.cpp::enqueueInternal::391] Error Code 2: Internal Error (Could not resolve slots: )
```

**Comment by lix19937** [comment]
@ywfwyht  Sorry, reply late,  the error seems a tensorrt issue,  `allInputDimensionsSpecified`  you can `check you dims setting`( dynamic shape or not), and use the latest version of `trt 8.6`
