### ISSUE TITLE
opt smoothquant & tensor parallelism.

### ISSUE THREAD

**Issue by shhn1** [NVIDIA/FasterTransformer#578]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:21.11-py3

### GPU name

A100

### CUDA Driver

cuda 11.8

### Reproduced Steps

```shell
When I set TP=1, the smoothquant int8 model is 20% faster than fp16. After setting TP=4, the perf of int8 model is basically the same as fp16. I don't quite understand why this happens?

The steps I performed are as follows：
1. ./bin/multi_gpu_gpt_example    # config.ini  tensor_para_size=1
2. mpirun -n 4 --allow-run-as-root ./bin/multi_gpu_gpt_example  # config.ini  tensor_para_size=4
```

**Comment by byshiue** [comment]
The benefit of int8 highly depends on model size, tensor parallel size and problem size. When these sizes are not large enough, the overhead of using int8 may be larger or same to benefit of using int8.

**Comment by shhn1** [comment]
Thank you for your reply! I have verified it on opt-30b. As the size of the model increases, the advantages of int8 quantization are indeed reflected.
