### ISSUE TITLE
torch.nn.init.normal_ in pytorch/gpt.py GPTWeights.__init__ is slow

### ISSUE THREAD

**Issue by eval-dev** [NVIDIA/FasterTransformer#583]
### Branch/Tag/Commit

v5.3

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

A100

### CUDA Driver

470

### Reproduced Steps

```shell
GPT model, weight data type: fp16, infer data type: fp16

profile result:


12896135 function calls (12833705 primitive calls) in 496.400 seconds
 
  Ordered by: cumulative time
 
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  466.549  466.549 gpt.py(__init__)
      396    0.001    0.000  465.188    1.175 gpt.py:180(<lambda>)
      396    0.001    0.000  465.187    1.175 init.py:140(normal_)
      396    0.003    0.000  465.186    1.175 init.py:17(_no_grad_normal_)
      396  465.178    1.175  465.178    1.175 {method 'normal_' of 'torch._C._TensorBase' objects}
      ...

```

Can see `self._map(lambda w: torch.nn.init.normal_(w, mean=0., std=1.))` is very slow and takes long time. https://github.com/NVIDIA/FasterTransformer/blob/release/v5.3_tag/examples/pytorch/gpt/utils/gpt.py#L180

Is weight init necessary? It seems to be a redundant operation since the weights are later loaded from ckpt. I tried remove this line and the inference looks good. Can anyone help confirm if it is safe not to init the weight tensors?
```

**Comment by byshiue** [comment]
We keep the init weight to let users running benchmark with random weight. If you don't need them, you can remove them and it is fine.

**Comment by eval-dev** [comment]
> We keep the init weight to let users running benchmark with random weight. If you don't need them, you can remove them and it is fine.

Thanks @byshiue for the input
