### ISSUE TITLE
GptNeoX fails to stop inference when encountering end_id

### ISSUE THREAD

**Issue by SeibertronSS** [NVIDIA/FasterTransformer#631]
I accelerated GptNeoX with FT and deployed with Triton. But I found that GptNeoX can't stop inference when encountering end_id.

**Comment by hmzo** [comment]
hello, have you fixed this bug? @SeibertronSS

**Comment by SeibertronSS** [comment]
> hello, have you fixed this bug? @SeibertronSS

Just use the latest FasterBackend code

**Comment by SeibertronSS** [comment]
> hello, have you fixed this bug? @SeibertronSS

Just use the latest FasterTransformer code
