### ISSUE TITLE
Why there is a dequantization and a quantization at the end of the fused multi-head attention module

### ISSUE THREAD

**Issue by woskii** [NVIDIA/FasterTransformer#65]
In the [encoder_guide](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/encoder_guide.md), the Fig.3 shows the workflow of int8 inference including int8v1 and int8v2. At the end of Fused Multi-head attention, there is a deQ&Q before Proj Gemm. Why does FT need to do this? I wonder maybe why not quantize the result of Batch Gemm 2 directly？

**Comment by byshiue** [comment]
The first "dequantization" is the scale for Batch Gemm 2, while the second "quantization" is the scale of Proj Gemm. 
But in the codes, we can fuse these two scale into one, and hence there is no additional overhead.
