### ISSUE TITLE
distillation_loss_scale

### ISSUE THREAD

**Issue by Qiancj0605** [NVIDIA/FasterTransformer#73]
@byshiue  Hello，When making a BERT model distillation, distillation_loss_scale does this factor set so much（10000）, will it cause LOSS unstable?

**Comment by Qiancj0605** [comment]
Is it a bit big like this fluctuation? @byshiue
![image](https://user-images.githubusercontent.com/34846384/117639792-e3444b00-b1b6-11eb-818b-4fb3a4f068ab.png)

**Comment by byshiue** [comment]
What's the final accuracy in this case?

**Comment by Qiancj0605** [comment]
No Accuracy Related Logs，Only LOSS Related Logs.
![Uploading image.png…]()

**Comment by byshiue** [comment]
Can you run your model on some testing set like SQuAD?

**Comment by byshiue** [comment]
The loss in your case is not normal. 
You may need to adjust the loss_scale in your case, it is a hyper-parameter.

**Comment by Qiancj0605** [comment]
Thanks,i try it.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
