### ISSUE TITLE
About Effective FasterTransformer 

### ISSUE THREAD

**Issue by wellinxu** [NVIDIA/FasterTransformer#75]
Does Effective FasterTransformer  support tiny-bert？ tiny-bert-config:4-layers,312-hidden_size, 12-head_nums.
https://github.com/NVIDIA/FasterTransformer/blob/main/docs/encoder_guide.md#model-architecture

Why Effective FasterTransformer is faster than FasterTransformer when seq_len is same?
https://github.com/NVIDIA/FasterTransformer/blob/main/docs/encoder_guide.md#encoder-performance-on-v100-and-tensorflow

Thanks!

**Comment by byshiue** [comment]
I think size per head 26 does not work. We only focus on size per head 32, 64, 96 and 128.
Effective FT will remove the useless padding. Here, the active seqlen is only half of max seqlen. So, the size of gemm in Effective FT is smaller and hence faster.

**Comment by wellinxu** [comment]
@byshiue Thanks!

**Comment by byshiue** [comment]
Close this issue because it is inactivated. Feel free to re-open this issue if you still have any problem.
