### ISSUE TITLE
"Attention" is  " q*k^T " than do softmax  .  why is this  "k^T*q"

### ISSUE THREAD

**Issue by justingyym** [NVIDIA/FasterTransformer#76]
attention is  "q*k^T " than do softmax  .  why is this  "k^T*q"

open_attention.h:738

 check_cuda_error(cublasGemmStridedBatchedEx(cublas_handle,
        CUBLAS_OP_T, CUBLAS_OP_N,
        seq_len, seq_len, size_per_head,
        &alpha,
        **k_buf_**, AType_, size_per_head, seq_len * size_per_head,
        **q_buf_**, BType_, size_per_head, seq_len * size_per_head,
        &beta,
        **qk_buf_**, CType_, seq_len, seq_len * seq_len,
        batch_size * head_num,
        computeType_,
        static_cast<cublasGemmAlgo_t>(cublasBmmAlgo_[0])));
    
      attn_softmax_kernelLauncher(qk_buf_, attr_mask, batch_size, seq_len, head_num, scalar, stream);

*************************************************************************************
https://docs.nvidia.com/cuda/archive/10.0/cublas/index.html
2.8.14. cublasGemmStridedBatchedEx()
               cublasStatus_t cublasGemmStridedBatchedEx(cublasHandle_t handle,
                                          cublasOperation_t transa, 
                                          cublasOperation_t transb,
                                          int m, 
                                          int n, 
                                          int k,
                                          const void    *alpha,
                                          const void     *A, 
                                          cudaDataType_t Atype, 
                                          int lda,
                                          long long int strideA,
                                          const void     *B, 
                                          cudaDataType_t Btype, 
                                          int ldb,
                                          long long int strideB,
                                          const void    *beta,
                                          void           *C, 
                                          cudaDataType_t Ctype, 
                                          int ldc,
                                          long long int strideC,
                                          int batchCount,
                                          cudaDataType_t computeType, 
                                          cublasGemmAlgo_t algo)

C + i * strideC = α op ( A + i * strideA ) op ( B + i * strideB ) + β ( C + i * strideC ) ,  for i  ∈ [ 0 , b a t c h C o u n t − 1 ]

**Comment by byshiue** [comment]
Since cublas is column major. When we put data in such format, the real computation would be "q*k^T"

**Comment by byshiue** [comment]
Close this issue because it is inactivated. Feel free to re-open this issue if you still have any problem.
