### ISSUE TITLE
Does FasterTransformer support bert with relative position embedding

### ISSUE THREAD

**Issue by trouble-maker007** [NVIDIA/FasterTransformer#77]
I have train a bert with relative position embedding, that improve the performance, I doubt that does FasterTransformer support relative position embedding like [nezha](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/NEZHA-TensorFlow), [roformer](https://github.com/ZhuiyiTechnology/roformer)

**Comment by byshiue** [comment]
Currently, BERT of FT accepts the results after embedding. Namely, FT does not contains the part of position embedding, it is handled by TensorFlow/PyTorch or others. So, there is no effect if you want to use relative position embedding.

**Comment by trouble-maker007** [comment]
@byshiue that means that I just add the relative position embedding code in the modeling.py, it is ok?

**Comment by byshiue** [comment]
Yes.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Comment by Lijiadong** [comment]
@byshiue [nezha attention layer](https://github.com/huawei-noah/Pretrained-Language-Model/blob/4624dbadfe00e871789b509fe10232c77086d1de/NEZHA-PyTorch/modeling_nezha.py#L366) is different from bert attention layer, nezha attention layer contains embedding. Is there any way to use FT for nezha encoder?

**Comment by byshiue** [comment]
> @byshiue [nezha attention layer](https://github.com/huawei-noah/Pretrained-Language-Model/blob/4624dbadfe00e871789b509fe10232c77086d1de/NEZHA-PyTorch/modeling_nezha.py#L366) is different from bert attention layer, nezha attention layer contains embedding. Is there any way to use FT for nezha encoder?

There is no simple way to support it. You need to modify source codes of FT.
