### ISSUE TITLE
FasterTransformer 4.0 vs 3.1

### ISSUE THREAD

**Issue by aaddai** [NVIDIA/FasterTransformer#78]
I have run the cpp API sample: 'decoding_beamsearch_sample' and found the decoding of v4.0 gets 2.0x speedup compare to v3.1 on Tesla T4.  But I noticed a few inconsistencies about 'beam_width' in decoder module of v4.0, when beam_width > 1.
const int m = args_.batch_size_ * args_.beam_width_ in embedding_lookup kernel and topk_softmax kernel.
But in openDecoder, ‘l_parallel_param_.local_batch_size’  is set as ‘DecoderInitParam::request_batch_size’, without beam_width.
In fact, I have compared the outputs of each 'layer' in decoder of v4.0 with v3.1, and there are a few difference.
How to use 'beam_width' in inference sence?

**Comment by byshiue** [comment]
For open_decoder, the `batch_size` already contains the `beam_width` because `beam_width` is meaningless in decoder.
Namely, `batch_size` of decoder = `batch_size*beam_width` of decoding.

**Comment by aaddai** [comment]
but I have tracked \b batch_size in open_decoder, \b bean_width has missing, batch_size of decoder != batch_size*beam_width of decoding.
In fact， [batch, beam] of input as [16, 4] and [64, 1] get different time consuming in 'decoder'.

**Comment by byshiue** [comment]
> but I have tracked 'batch_size' in open_decoder, 'beam_width' has missing, batch_size of decoder != batch_size*beam_width of decoding in v4.0.
> In fact， [batch, beam] of input as [16, 4] and [64, 1] get different time consuming in 'decoder' in v4.0.

If you mean that the `batch_size*beam_width` of decoding_beamsearch.h does not equal to `batch_size` in open_decoder.h in `decoding_beamsearch_sample.cc`, this is a bug at https://github.com/NVIDIA/FasterTransformer/blob/main/sample/cpp/decoding_beamsearch_sample.cc#L124, where we set the batch_size of decoder param as batch_size, but not batch_size * beam_width.
