### ISSUE TITLE
gpt float16 output accuracy potential issue

### ISSUE THREAD

**Issue by gyin-ai** [NVIDIA/FasterTransformer#83]
model: openai gpt2 124M

```
./bin/gpt_gemm 1 1 12 64 50257 32 1 1
```
1. output accuracy (FT float16 vs openai tf) 
decoding: top k 1, top_p 0.0, temperature 1
input: [google translate]
openai tf: [to English]
FT float16: [: true]

gpt2 interactive mode: https://github.com/openai/gpt-2/blob/master/src/interactive_conditional_samples.py

**Comment by byshiue** [comment]
The outputs are often different under FP32 and FP16. Especially, GPT is an auto-regressive module, and hence the results would be very different if we generate different results at any step.

**Comment by gyin-ai** [comment]
> The outputs are often different under FP32 and FP16. Especially, GPT is an auto-regressive module, and hence the results would be very different if we generate different results at any step.

Seq2seq is usually very stable even if we use FP16 or even INT8, which uses the argmax. This can be noticed in lightseq and ctranslate2. The above result looks like randomly generated results.

**Comment by byshiue** [comment]
> > The outputs are often different under FP32 and FP16. Especially, GPT is an auto-regressive module, and hence the results would be very different if we generate different results at any step.
> 
> Sequence generation is usually very stable even if we use FP16 or even INT8 for most examples, since it uses the argmax to get the possible token. This can be noticed and verified in lightseq, ctranslate2 and onnx. The above result looks like randomly generated results.
> 
> Have we done any relevance validation against GPT float16 in fastertransformer?

If the results are different, but makes sense under FP16, it is normal.
If the results does not make sense, then there are some problems.

For validation under FP16, we can only verify by the results directly. Do you have any data about the stableness of sequence generation? For seq2seq, we find that the results of FP16 are different to FP32, but the bleu score would be close.

**Comment by gyin-ai** [comment]
`For validation under FP16, we can only verify by the results directly.` Do you mean we have Bleu score result comparison on GPT model?

**Comment by byshiue** [comment]
It is hard to verify the BLEU for GPT model. We only verify the BLEU for encoder+decoder model.

**Comment by gyin-ai** [comment]
Verified the result with high confidence based on cumulative log probability score. The result would be the same. Can I ask how we can populate the cumulative log score from FT?
