### ISSUE TITLE
About decoder v4.0

### ISSUE THREAD

**Issue by aaddai** [NVIDIA/FasterTransformer#85]
Init all  weights and biases in 'decoder_beamsearch.cc '   with the same initial_value,  v3.1 and v4.0 get different output. Someone has the same problem？

**Comment by byshiue** [comment]
We have optimize the kernel of decoder in v4.0, and hence the results may be little different. 
Do the difference make sense?

**Comment by aaddai** [comment]
> We have optimize the kernel of decoder in v4.0, and hence the results may be little different.
> Do the difference make sense?

I try to depoly FT v4.0 in inference sence and get wrong output. In order to slove the problem, I compare the decoder's intermediate output of V3.1 and v4.0, and find diff of  decoder_self_attn_output is obviously. I want to make sure this has an impact.
I have tried v3.1 and got wrong output too.

**Comment by byshiue** [comment]
The format of cache are different in v3.1 and v4.0. So, if you don't convert the format of v4.0, then the differences are normal. 
If you tried v3.1 and got wrong output, it means that there are some problems in your integration.

**Comment by aaddai** [comment]
> The format of cache are different in v3.1 and v4.0. So, if you don't convert the format of v4.0, then the differences are normal.
> If you tried v3.1 and got wrong output, it means that there are some problems in your integration.

how to  convert the format of cache of v4.0? 
Thanks for reply.

**Comment by byshiue** [comment]
It affects many parts, including the self attention and beam search. I suggest you to try v3.1 first if you want to check some intermediate results.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
