### ISSUE TITLE
Does size_per_head have to be a multiple of 32?

### ISSUE THREAD

**Issue by dingjingzhen** [NVIDIA/FasterTransformer#89]
hi，
  Does size_per_head have to be a multiple of 32?I found that when size_per_head=80, the result is wrong

**Comment by byshiue** [comment]
For decoder, we only verify and guarantee the correctness under some common cases, like 32, 64 and 128.

**Comment by dingjingzhen** [comment]
OK，thank you!

**Comment by byshiue** [comment]
Close this issue because it is inactivated. Feel free to re-open this issue if you still have any problem.
