### ISSUE TITLE
FasterTransformer support GPU GeForce RTX 3090?

### ISSUE THREAD

**Issue by quancq** [NVIDIA/FasterTransformer#90]
I use environment:
- Docker images nvcr.io/nvidia/pytorch:20.12-py3
- Pytorch: 1.8.0
- CUDA 11.1

I installed successfully and run pytorch sample code on GPU GeForce 2080 Ti, but with GPU GeForce 3090 (compute capability of this gpu is 8.6) i meet this problem when run ``./bin/encoder_gemm 32 32 12 64 0 0`` command:
**Device GeForce RTX 3090 
terminate called after throwing an instance of 'std::runtime_error'
  what():  [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_NOT_INITIALIZED /data/FasterTransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:595**

Could anyone help me? Thanks.

**Comment by byshiue** [comment]
Do you build the repo with sm=86? 
If not, try to add 86 at https://github.com/NVIDIA/FasterTransformer/blob/main/CMakeLists.txt#L106, and build the repo by `cmake -DSM=86 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..`.

**Comment by quancq** [comment]
> Do you build the repo with sm=86?
> If not, try to add 86 at https://github.com/NVIDIA/FasterTransformer/blob/main/CMakeLists.txt#L106, and build the repo by `cmake -DSM=86 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..`.

Thank for your solution. After add 86 and build repo again, I run successfully pytorch sample code.

**Comment by byshiue** [comment]
Close this issue because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Comment by js19950726** [comment]
Is the rtx3080 also use the -DSM=86 ??

**Comment by byshiue** [comment]
> Is the rtx3080 also use the -DSM=86 ??

Yes.
