### ISSUE TITLE
relative position embedding?

### ISSUE THREAD

**Issue by gyin-ai** [NVIDIA/FasterTransformer#92]
can I ask whether the relative position embedding is possible based on the current implementation?

https://github.com/huggingface/transformers/blob/61c506349134db0a0a2fd6fb2eff8e29a2f84e79/src/transformers/models/t5/modeling_t5.py#L347

**Comment by byshiue** [comment]
If the relative position embedding only affect the part of embedding, it is possible since the input of BERT is the encoded results, FT does not handle this part. For decoder, we let users put the position embedding table as input, no matter which type of embedding it is.

**Comment by 520jefferson** [comment]
> If the relative position embedding only affect the part of embedding, it is possible since the input of BERT is the encoded results, FT does not handle this part. For decoder, we let users put the position embedding table as input, no matter which type of embedding it is.

@byshiue  If i add a role embedding  in bert / gpt, whether i should modify the structure of FT to adapt the  new structure ? or maybe i can process the input outside the bert/gpt ?

**Comment by byshiue** [comment]
For the latest codes, we have relative position embedding in the T5 implementation in https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/t5/T5Encoder.cc#L274 and https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/layers/attention_layers/UnfusedAttentionLayer.cc#L189.
If you hope to use it in GPT or BERT, you need to add the relative position embedding building into them.

**Comment by 520jefferson** [comment]
> For the latest codes, we have relative position embedding in the T5 implementation in https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/models/t5/T5Encoder.cc#L274 and https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/layers/attention_layers/UnfusedAttentionLayer.cc#L189. If you hope to use it in GPT or BERT, you need to add the relative position embedding building into them.

Sorry, i still have some confusion, Let me clear myself.  Is the nunber of embedding should be fixed? i  want to add another embedding in the T5's input, is that okay?

**Comment by byshiue** [comment]
What's the meaning of "number of embedding"? Do you want to use two embedding at the same time?

**Comment by 520jefferson** [comment]
![image](https://user-images.githubusercontent.com/5691554/148897051-b219e591-4f54-43a7-8ab2-291e4db68dc3.png)
As shown in the figure above, except the Token and Position embedding, if i  Role and Type embedding int the same time as input, is that okay?

**Comment by byshiue** [comment]
You need to modify the source codes. FT does not know how to choose the index from the type and role embedding.

**Comment by 520jefferson** [comment]
@byshiue If i want to use triton inference server with t5，is there a doc ? i just find https://github.com/triton-inference-server/fastertransformer_backend which support gpt not t5.
