### ISSUE TITLE
cublas gemm seems to support int8 matrix multiplication, why encoder still use cublasLt, is cublasLt performance is better?

### ISSUE THREAD

**Issue by dingjingzhen** [NVIDIA/FasterTransformer#95]
hi,
cublas gemm seems to support int8 matrix multiplication, why encoder still use cublasLt, is cublasLt performance is better?

**Comment by byshiue** [comment]
cublas for int8 only uses CUDA core, while cublasLt can leverage the tensor core.

**Comment by dingjingzhen** [comment]
thanks for your reply！

**Comment by dingjingzhen** [comment]
One more question, why gpt did not do int8 quantization？

**Comment by byshiue** [comment]
Since we still not verify the accuracy affect of INT8 on GPT model.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
